### ISSUE TITLE
 How to convert colmap's sparse model (cameras.bin, images.bin, points3D.bin) into opensfm json format

### ISSUE THREAD

**Issue by yuancaimaiyi** [mapillary/OpenSfM#1016]
@fabianschenk 
Hello, I think the visualization department of opensfm is good. I want to convert the sparse format of colmap to opensfm format, and then use the web visualization function of opensfm to visualize colmap. Is there this part in the code?

**Comment by fabianschenk** [comment]
Hi @yuancaimaiyi ,

Please, use the code search on github! This takes ~1 minute.
