### ISSUE TITLE
Error when building with ceres on ubuntu 22.04

### ISSUE THREAD

**Issue by hanxjing** [mapillary/OpenSfM#1024]
My ceres-solver version is 2.2.0.
Part of the output in building process is as follows:

> [ 73%] Building CXX object map/CMakeFiles/map.dir/src/rig.cc.o
>       [ 73%] Building CXX object map/CMakeFiles/map.dir/src/landmark.cc.o
>       [ 74%] Building CXX object map/CMakeFiles/map.dir/src/dataviews.cc.o
>       [ 74%] Building CXX object map/CMakeFiles/map.dir/src/observation.cc.o
>       [ 75%] Building CXX object map/CMakeFiles/map.dir/src/shot.cc.o
>       [ 76%] Building CXX object map/CMakeFiles/map.dir/src/map.cc.o
>       [ 77%] Building CXX object map/CMakeFiles/map.dir/src/tracks_manager.cc.o
>       In file included from /usr/local/include/ceres/rotation.h:52,
>                        from /tmp/pip-req-build-6r3malib/opensfm/src/geometry/test/camera_functions_test.cc:2:
>       /usr/local/include/ceres/internal/euler_angles.h:84:45: error: ‘is_same_v’ is not a member of ‘std’; did you mean ‘is_same’?
>          84 |   static constexpr bool kIsParityOdd = std::is_same_v<ParityType, Odd>;
>             |                                             ^~~~~~~~~
>             |                                             is_same
>       /usr/local/include/ceres/internal/euler_angles.h:84:65: error: expected primary-expression before ‘,’ token
>          84 |   static constexpr bool kIsParityOdd = std::is_same_v<ParityType, Odd>;
>             |                                                                 ^
>       /usr/local/include/ceres/internal/euler_angles.h:84:67: error: ‘constexpr’ static data member ‘Odd’ must have an initializer
>          84 |   static constexpr bool kIsParityOdd = std::is_same_v<ParityType, Odd>;
>             |                                                                   ^~~
>       /usr/local/include/ceres/internal/euler_angles.h:84:67: error: expected ‘;’ at end of member declaration
>          84 |   static constexpr bool kIsParityOdd = std::is_same_v<ParityType, Odd>;
>             |                                                                   ^~~
>             |                                                                      ;
>       /usr/local/include/ceres/internal/euler_angles.h:84:70: error: expected unqualified-id before ‘>’ token
>          84 |   static constexpr bool kIsParityOdd = std::is_same_v<ParityType, Odd>;
>             |                                                                      ^
>       /usr/local/include/ceres/internal/euler_angles.h:86:12: error: ‘is_same_v’ is not a member of ‘std’; did you mean ‘is_same’?
>          86 |       std::is_same_v<AngleConventionType, ProperEuler>;
>             |            ^~~~~~~~~
>             |            is_same
>       /usr/local/include/ceres/internal/euler_angles.h:86:41: error: expected primary-expression before ‘,’ token
>          86 |       std::is_same_v<AngleConventionType, ProperEuler>;
>             |                                         ^
>       /usr/local/include/ceres/internal/euler_angles.h:86:43: error: ‘constexpr’ static data member ‘ProperEuler’ must have an initializer
>          86 |       std::is_same_v<AngleConventionType, ProperEuler>;
>             |                                           ^~~~~~~~~~~
>       /usr/local/include/ceres/internal/euler_angles.h:86:43: error: expected ‘;’ at end of member declaration
>          86 |       std::is_same_v<AngleConventionType, ProperEuler>;
>             |                                           ^~~~~~~~~~~
>             |                                                      ;
>       /usr/local/include/ceres/internal/euler_angles.h:86:54: error: expected unqualified-id before ‘>’ token
>          86 |       std::is_same_v<AngleConventionType, ProperEuler>;
>             |                                                      ^

...

> make[2]: *** [geometry/CMakeFiles/geometry_test.dir/build.make:90: geometry/CMakeFiles/geometry_test.dir/test/camera_functions_test.cc.o] Error 1
>       make[1]: *** [CMakeFiles/Makefile2:822: geometry/CMakeFiles/geometry_test.dir/all] Error 2
>       [ 81%] Linking CXX executable map_test
>       /usr/bin/ld: CMakeFiles/map_test.dir/test/tracks_manager_test.cc.o: in function `testing::internal::TestFactoryImpl<(anonymous namespace)::TracksManagerTest_ReturnsAllCommonObservations_Test>::CreateTest()':
>       tracks_manager_test.cc:(.text+0xe90): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
>       [ 81%] Built target map_test
>       make[2]: *** [robust/CMakeFiles/robust.dir/build.make:146: robust/CMakeFiles/robust.dir/src/instanciations.cc.o] Error 1
>       make[1]: *** [CMakeFiles/Makefile2:876: robust/CMakeFiles/robust.dir/all] Error 2
>       [ 82%] Linking CXX static library libbundle.a
>       [ 82%] Built target bundle
>       make: *** [Makefile:101: all] Error 2
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-req-build-6r3malib/setup.py", line 60, in <module>
>           build_c_extension()
>         File "/tmp/pip-req-build-6r3malib/setup.py", line 54, in build_c_extension
>           subprocess.check_call(
>         File "/home/xianjing/anaconda3/envs/2Dmap/lib/python3.9/subprocess.py", line 373, in check_call
>           raise CalledProcessError(retcode, cmd)
>       subprocess.CalledProcessError: Command '['make', '-j72']' returned non-zero exit status 2.

Do you have any idea about the problem?

**Comment by hanxjing** [comment]
I tackled this problem by installing ceres-solver 2.0.0.

**Comment by foryond** [comment]
> I tackled this problem by installing ceres-solver 2.0.0.

thanks very much! This problem has stuck me for ten days!

**Comment by KuchikiRukia7** [comment]
> > I tackled this problem by installing ceres-solver 2.0.0.
> 
> thanks very much! This problem has stuck me for ten days!

Have you successfully run the program now?
