### ISSUE TITLE
Error data and correlation similar to Metashape matrix

### ISSUE THREAD

**Issue by lupionpe** [mapillary/OpenSfM#1025]
Hello guys, I am new here.

I used to use Agisoft Metashape in my projects, and on their report there is the camera parameters and the error and correlation between them.

![image](https://github.com/mapillary/OpenSfM/assets/65565211/cf689cb0-3432-498b-9183-d8535e8e051e)

I was looking for a way to have something similar using OpenSfM.

I have done some investigation here and also try to find the in the files, such as `reconstruction.json` and `reconstruction.nvm` if I could get this information, or recalculate it, but I did not have success.

Are there any files, logs, etc where I could either find or recalculate those numbers?

Cheers
Lupion
cc: @felupion

**Comment by kielnino** [comment]
Hi @lupionpe, have you looked at the reports and statistics? A lot of information about (re)projection-errors are only available at runtime, but not saved to the final reconstruction-files. The stats for example are generated from the reconstruction objects [here](https://github.com/mapillary/OpenSfM/blob/78b795c58a4684195c6c7ab5e7d531ee484f32c6/opensfm/stats.py#L138). Maybe you can use this as a starter?

The final camera-parameters should by available from the `reconstruction.json` if I recall correctly.
