### ISSUE TITLE
Camera::PixelToNormalizedCoordinatesMany returns incorrect value?

### ISSUE THREAD

**Issue by oaa3wf** [mapillary/OpenSfM#1030]
Should Camera::PixelToNormalizedCoordinatesMany be returning norm_coords instead of px_coords?see [https://github.com/mapillary/OpenSfM/blob/7f170d0dc352340295ff480378e3ac37d0179f8e/opensfm/src/geometry/src/camera.cc#L361](https://github.com/mapillary/OpenSfM/blob/7f170d0dc352340295ff480378e3ac37d0179f8e/opensfm/src/geometry/src/camera.cc#L361)

**Comment by kielnino** [comment]
@oaa3wf Would you mind closing this issue now?
