### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by panditanvita** [mapillary/OpenSfM#107]
Hi, 

I updated some of the code in bin/match_features (removed print statements) and re-ran `python setup.py build` but it looks like the program is unaffected. I'm new to this so I imagine I'm probably missing something simple that I'm unaware of... any help appreciated!

**Comment by paulinus** [comment]
hi!
The file `bin/match_features` is an old version of the command that is actually used: `opensfm/commands/match_features.py`.  You can look at `bin/run_all` to see what's called.
I've just removed the old command. Sorry for the confusion.
