### ISSUE TITLE
Migrate from pyexiv2 to gexiv2

### ISSUE THREAD

**Issue by dakotabenjamin** [mapillary/OpenSfM#111]
Pyexiv2 has been depreciated for a while. Are there any plans to move to [Gexiv2](https://wiki.gnome.org/Projects/gexiv2) for geotagging? 

https://github.com/mapillary/OpenSfM/blob/master/opensfm/geotag_from_gpx.py#L11

**Comment by paulinus** [comment]
No plans for now, but note that this file is only used for converting videos to still images. This is a rarely used feature. `pyexiv2` is not required for OpenSfM otherwise
