### ISSUE TITLE
Differences between the master and ODM branch

### ISSUE THREAD

**Issue by xialang2012** [mapillary/OpenSfM#113]
Hi, @paulinus , what is the difference between the master branch and the ODM release, such as this one, https://github.com/mapillary/OpenSfM/releases/tag/odm-4.

**Comment by paulinus** [comment]
The odm-# releases are just a way to track what is being used in ODM. We have been making a release each time we wanted ODM to get a new version of OpenSfM.  We could probably start making regular releases independent of ODM so that it would be simpler for ODM to update to newer versions.

**Comment by xialang2012** [comment]
get it.
