### ISSUE TITLE
Fail with test data

### ISSUE THREAD

**Issue by fitoprincipe** [mapillary/OpenSfM#117]
Hello, I have installed OpenSfM using Docker, but when I run the test data (berlin), I get the following error:

_bin/run_all: line 11:  6401 Illegal instruction     (core dumped) $DIR/opensfm reconstruct $1_

**Comment by paulinus** [comment]
I'm sorry to hear. We have Travis building and testing OpenSfM using docker https://travis-ci.org/mapillary/OpenSfM
It is working well there, so i assume that your setup is different. Can you give more details that i could use to help out?
