### ISSUE TITLE
Where to start to understand this library?

### ISSUE THREAD

**Issue by hilman-dayo** [mapillary/OpenSfM#123]
I am a student and I am right now in the way of understanding the SfM and SLAM techniques (in order to reconstruct a 3D structure from images). I am really interested in this library, and want to use it to enhance my understanding and I want to start a project with it. I even want to contribute to it if I can in the future. 

So, to understand this library, where should I start? What modules is the 'backbone' of this library? Which part of modules that I need to get a good grasp on? This is because I am still a moderate programmer (I am a self-learner and mainly use python) and kind of lost in understanding this library right now. Thanks.

**Comment by paulinus** [comment]
Great that you are getting into 3d vision. Lots of fun ahead!

At the very very top level, it is important to understand which steps are used to get the recostruction done.  For this, you should start by looking at `bin/run_all` and making sure that you know what each command does at a high-level.

Then i would recommend looking at the generated files after running that command. The module `opensfm/dataset.py` contains the i/o for those files.

Then i think that the important meat is in the reconstruction part. For this, the best is probably to look at `opensfm/types.py` to see the data types that are used, and then `opensfm/reconstruct.py` to see how the incremental reconstruction pipeline is implemented.

We want to add documentation and adding a high-level overview of the library would be very useful.  In the meantime, please feel free to ask anything here.

**Comment by hilman-dayo** [comment]
Thanks for the reply! I really appreciate it.
