### ISSUE TITLE
Where (if any) are the 'global' faces recorded in reconstruction.meshed.json?

### ISSUE THREAD

**Issue by j6k4m8** [mapillary/OpenSfM#125]
Let's call the data inside the reconstruction.meshed JSON file `reconstruction`: I can see that `reconstruction.points` contains coordinate, color, and reprojection-error data. And `reconstruction.shots#faces` contains face information _for that particular shot_. It appears, however, that these faces only correspond to `reconstruction.shots#faces` in the same shot.

Does this mean that there are no global faces reconstructed? Or have I overlooked something (or perhaps run things incorrectly)?

These were generated using the Docker container's precompiled `run_all`.

(PS: Awesome tool! Hoping to contribute some more 3D mesh manipulation tools to the community.)

**Comment by j6k4m8** [comment]
> **[EDIT]**: The more I explore the code, the more it seems like this output is _just_ a pointcloud: I was confused by the use of the term `mesh` which I interpreted as explicitly having faces.
>
> Am I correct in this understanding?

**Comment by paulinus** [comment]
The `mesh` term correspond to a coarse mesh per image. This is what is used in the viewer and in Mapillary to show smoother transitions between images. It is indeed not a global mesh nor a denser one.

The closest to that that you can get in OpenSfM is a dense pointcloud. Some initial doc on how to get it is here http://opensfm.readthedocs.io/en/latest/using.html

If you want a dense textured mesh, then you can use OpenDroneMap which includes OpenSfM. Or export to openMVS which can also output dense meshes.
