### ISSUE TITLE
opensfm.io.json_dump minification

### ISSUE THREAD

**Issue by j6k4m8** [mapillary/OpenSfM#126]
Minifying the `reconstruction.meshed.json` file can dramatically reduce the filesize: In one example, my 267MB file shrunk to 63MB. The original file failed to load in the web-viewer: My minified version loaded immediately.

Is there a reason the whitespace is left in (perhaps for human-readability)? If not, I'd be happy to pull-request this change.

> For those who just want to try minifying their files too, you can run:
> ```python
> import json
> with open('reconstruction.meshed.min.json', 'w') as fh:
>     fh.write(
>         json.dumps(
>             json.loads(open('reconstruction.meshed.json', 'r').read())
>         )
>     )
> ```

**Comment by BrookRoberts** [comment]
This problem and solution both affected me too.  Ideally the reconstruction viewer would also warn you in some way that the file was too big rather than hanging.  Certainly I couldn't get a file to load at 486MB but the minified 188MB worked fine.

**Comment by paulinus** [comment]
@j6k4m8 the white space is indeed only for human-readability. Happy to accept that PR and remove it, thanks. A human can use a json formatter if he needs to read it.
