### ISSUE TITLE
Is it possible to disable the loop closure of reconstruction?

### ISSUE THREAD

**Issue by pengsongyou** [mapillary/OpenSfM#127]
Hi,

I am trying to use OpenSfM to test the quality of camera calibration. The way I am doing is to input 15 images which contain 360 degree views of an object. However, I directly set the image 1 the same as the image 15. I want to see that: if a calibration method is effective, then the estimated pose of image 1 should be quite close to image 15, vice versa. However, it turns out that OpenSfM is too robust that it will automatically remove the image 1 (maybe the system can detect if there exist same images in the dataset?). I am wondering if it has an option to (dis)activate this "loop closure" thing? Or where can I disable this functionality in OpenSfM?

Thanks in advance!

**Comment by paulinus** [comment]
Hi, there is no explicit loop closure in OpenSfM, but it can happen implicitly.  All images are matched against all others. Thus, you will get matches between image 1 and 15.

You can prevent image 1 to be matched with image 15 by limiting matching images by timestamp. Try adding
```
matching_time_neighbors: 2            # Number of images to match selected by time taken. Set to 0 to use no limit
```
to `config.yaml`. This will force matching to match each image only against the previous and next image on the sequence.

**Comment by pengsongyou** [comment]
Hi @paulinus , thanks so much for your reply!

First of all, I have 15 images in total in my dataset. I tried what you said to change `matching_time_neighbors`. When it is set to be `2`, only 10 images are used for reconstruction. When it is `4`, 14 images are used for reconstruciton. However, in all cases, the image 1 (which is the same as image 15) was not added. If what you said was correct, the image 1 should be added. Do you have any idea for this? Thank you very much!

**Comment by YanNoun** [comment]
Hi @pengsongyou , in addition to `matching_time_neighbors`, try setting `matching_order_neighbors` to 2.
