### ISSUE TITLE
No bin/mesh binary

### ISSUE THREAD

**Issue by eboudrand** [mapillary/OpenSfM#131]
It is written in [README.md](https://github.com/mapillary/OpenSfM/blob/master/README.md) : 

> Run bin/mesh data/berlin to build a reconstruction with sparse mesh that will produce smoother transitions from images

But, I cannot find "mesh" binary. Must this file be generated ?

**Comment by paulinus** [comment]
The command to compute the meshes is now `bin/opensfm mesh path_to_data` and is now run directly inside the `bin/run_all` command. The README file is outdated, sorry for the inconvenience. Will update it now.
