### ISSUE TITLE
Opensfm doesn't read exif data from PNG files

### ISSUE THREAD

**Issue by BrookRoberts** [mapillary/OpenSfM#134]
If I have a series of png files with gps exif data, opensfm will not read it and will not find any exif data.

This is caused because:
Strictly, exif data only exists on jpeg and tiff images.  However, tools such as exiftool seem to cope quite merrily with exif data on formats such as png. (since png has tags which can be used in a very similar manner).

Ideally, opensfm would read tags from png as if they were exif data and the user would notice no difference.  I'm not sure how standard png gps tags are.

**Comment by paulinus** [comment]
I don't know how png handles metadata neither. We are always loading jpegs.
In general, we don't get real photographs in png format. What is your source?
Would be a good feature to add if there is a frequent need. Otherwise, a tool or documentation for creating the `exif/` folder from outside OpenSfM might solve the infrequent use cases.

**Comment by BrookRoberts** [comment]
Source was image stream ripped from a video file.  We had chosen png because it was lossless.  tiff results in larger file size.  We had our own tool to add exif tags using exiftool, and exiftool doesn't mind adding them to pngs.

I think for now we will just use jpegs with minimum compression.  Seems like a risk that compressed images might lose useful information for finding feature points, but I don't know if this is a real worry.

**Comment by spifftek70** [comment]
Have you considered jpeg2000?

**Comment by MattWenham** [comment]
Will OpenSfM handle JEPG2000 images out-of-the-box?

**Comment by YanNoun** [comment]
@spifftek70 @MattWenham we support any file format though `OpenCV` `imread`, see https://docs.opencv.org/master/d4/da8/group__imgcodecs.html for `Jpeg2000` support. You would need to compile `OpenCV` with the proper `OPENCV_BUILD_3RDPARTY_LIBS`.
