### ISSUE TITLE
Inconsistency of image size due to orientation in exif file and imread of opencv3

### ISSUE THREAD

**Issue by profdunny** [mapillary/OpenSfM#135]
imread of opencv3 rotates an image using the orientation information in the exif file. However, it seems that image sizes in camera_models.json and reconstruction.json are inconsistent to the image size after the rotation. (When images that have exif properties such as "'Image Orientation': (0x0112) Short=Rotated 90, 'ExifImageWidth': (0xA002) Long=640, 'EXIF ExifImageLength': (0xA003) Long=480" are input, in the json files,  the image size is described as "width": 640,"height": 480.  However, for example, in 'detect_features.py', images are read from the file as numpy arrays of (640,480) and the features are extracted from the arrays. )
Is my understanding of this correct?

**Comment by paulinus** [comment]
You are right. I seems imread changed behaviour. An option has been recently added to prevent the rotation https://github.com/opencv/opencv/issues/6348#issuecomment-259655385. We should use it.

**Comment by BrookRoberts** [comment]
This breaks running the build of the Lund dataset on my system.  The output of cv2.__version__
 is '3.1.0-dev'.

I should probably update my opencv.  But seeing as you already added in a version check before using this flag, maybe it should be more specific?  I *think* this feature as introduced in 3.2.0, so a more specific version check would catch it.

**Comment by BrookRoberts** [comment]
Traceback (most recent call last):
  File "/home/brook/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/home/brook/OpenSfM/opensfm/commands/detect_features.py", line 30, in run
    detect(arg)
  File "/home/brook/OpenSfM/opensfm/commands/detect_features.py", line 50, in detect
    data.image_as_array(image), data.config, mask)
  File "/home/brook/OpenSfM/opensfm/dataset.py", line 73, in image_as_array
    return io.imread(self.__image_file(image))
  File "/home/brook/OpenSfM/opensfm/io.py", line 360, in imread
    if context.OPENCV3:
AttributeError: 'module' object has no attribute 'IMREAD_IGNORE_ORIENTATION'

**Comment by paulinus** [comment]
Sorry about the break. I've just added a catch for that exception so that you get a warning instead of an exception.
