### ISSUE TITLE
Partial reconstructions

### ISSUE THREAD

**Issue by BrookRoberts** [mapillary/OpenSfM#136]
What can you currently do with partial reconstructions and opensfm?  I have a few use cases, possibly I can achieve all of these without any code modifications, but I'm not sure:

I make a 'finished' reconstruction from some images, then later want to add some more images to the reconstruction that have been taken.
I make a reconstruction from some images, and want to make several bigger reconstructions from this base, each time adding a new set of images to this initial reconstruction.
I make a reconstruction from some images, that I am very happy with and want to use as 'ground truth'.  I then have some other images, and would like to use opensfm to find the location of these new images (but I don't want to move the original points, just use them to find some locations).

Could you tell me if I can acheive this currently, or alternatively, maybe point me in the right direction to get this sort of stuff working?  Shoud be possible to find a good way for each of these more limited use cases to do something faster than an entire new reconstruction.

**Comment by YanNoun** [comment]
@BrookRoberts we don't support extending a reconstruction, but that definitely would be a nice feature.

**Comment by YanNoun** [comment]
Closing as it duplicates https://github.com/mapillary/OpenSfM/issues/115 and https://github.com/mapillary/OpenSfM/issues/129
