### ISSUE TITLE
cv2.IMREAD_IGNORE_ORIENTATION not available in cv2 3.1.0

### ISSUE THREAD

**Issue by mattbrown11** [mapillary/OpenSfM#138]
My run is failing at line 360 in io.py because cv2 version 3.1.0 does not appear to have a IMREAD_IGNORE_ORIENTATION attribute.  I am on Ubuntu 14.04 if that helps.

**Comment by paulinus** [comment]
is it possible for you to update to opencv 3.2?
they added that feature on that version.
we could add a patch for 3.1, but that would only work for orientation: 1

**Comment by mattbrown11** [comment]
I upgraded to 3.2, and it works fine now.  For reference, I am using Python 2.7.12 |Anaconda 4.2.0 (64-bit).  The standard "conda install opencv" is at 3.1.0, but using

$conda install -c menpo opencv3

worked well.
