### ISSUE TITLE
Viewer stuck "loading"

### ISSUE THREAD

**Issue by mattbrown11** [mapillary/OpenSfM#139]
I follwed the instructions in the README.md and ran on the Berlin data set.  It seems to have finished without issue and created a number of files including reconstruction.meshed.json.

I ran 

$sudo python -m SimpleHTTPServer

from the main OpenSfM folder and then used Mozilla to browse

http://localhost:8000/viewer/reconstruction.html#file=/data/berlin/reconstruction.meshed.json

However, it is stuck at the loading animation.

I am on Ubuntu 14.04.  Any ideas?  Thanks.

**Comment by paulinus** [comment]
you can make sure that the file `data/berlin/reconstruction.meshed.json`
exists.
If it does, check the javascript console for errors
Also, no need to use `sudo` here

**Comment by mattbrown11** [comment]
After updating from cv2 3.10 to 3.2.0 as discussed in my issue #138 seemed to fix things.  I guess it wasn't fully completing the SfM operations.  Now the viewer works.  Thanks.

**Comment by paulinus** [comment]
glad to hear, thanks for reporting @mattbrown11
