### ISSUE TITLE
Segmentation fault when using SURF or SIFT

### ISSUE THREAD

**Issue by zwn** [mapillary/OpenSfM#140]
Trying to detect SURF or SIFT features in the berlin dataset gives me a seg fault. AKAZE and HAHOG work fine. It fails on line [features.py#L144](https://github.com/mapillary/OpenSfM/blob/5fc86b9890cca83f630dafc656c3278b7ae8542e/opensfm/features.py#L144).

I am working with docker image as used for travis or ubuntu 16.04 system with dependencies installed.

**Comment by edgarriba** [comment]
@zwn Could you check somehow whether you detect feature points before extracting the descriptors?

**Comment by zwn** [comment]
Commenting out the lines with `setDouble` and `setInt` lets me call `detector.detect` and that segfaults as well. I am not able to find any documentation for the cv2 python api :worried: . How is one supposed to check if the call 
```python
detector = cv2.FeatureDetector_create('SURF')
```
returns a valid object? I guess it is somehow related to the (non)free parts of opencv but I was under the impression that the separation was done only in version 3 of opencv.

**Comment by edgarriba** [comment]
right, the line that your pointing is for opencv 2.x Try to update to a latest version

**Comment by zwn** [comment]
Well, I am using what is in https://github.com/paulinus/opensfm-docker-base/blob/master/Dockerfile - is not the supported configuration?

**Comment by zwn** [comment]
The behavior is even worse when number of processes is > 1. Then it just hangs forever and cannot be killed by Ctrl-C.

But I found https://github.com/paulinus/opensfm-docker-base/blob/opencv3/Dockerfile and the result is better. It does not crash :wink: and it does not hang when using multiple processes:
```
root@4809ce85f4de:/tmp/repo2# ./bin/opensfm detect_features data/berlin/
2017-02-07 13:00:18,986 Extracting ROOT_SURF features for image 02.jpg
2017-02-07 13:00:19,174 OpenCV Contrib modules are required to extract SURF features
Traceback (most recent call last):
  File "./bin/opensfm", line 34, in <module>
    command.run(args)
  File "/tmp/repo2/opensfm/commands/detect_features.py", line 30, in run
    detect(arg)
  File "/tmp/repo2/opensfm/commands/detect_features.py", line 46, in detect
    data.image_as_array(image), data.config)
  File "/tmp/repo2/opensfm/features.py", line 234, in extract_features
    points, desc = extract_features_surf(image, config)
  File "/tmp/repo2/opensfm/features.py", line 131, in extract_features_surf
    detector = cv2.xfeatures2d.SURF_create()
AttributeError: 'module' object has no attribute 'xfeatures2d'
```
Maybe there isn't a way to do the same for opencv 2.

**Comment by edgarriba** [comment]
this docker file doesn't install contrib modules, which contain xfeatures2d

https://github.com/opencv/opencv_contrib

**Comment by paulinus** [comment]
Thanks for reporting, there are two issues here.

The first is that opencv2's SIFT and SURF segfault when running from  https://github.com/paulinus/opensfm-docker-base
It does not happen outside docker. I need to investigate what is happening there.  In the meantime, you can either not use docker or not use SIFT. HAHOG will give you equivalent results.

The second is that the docker image https://github.com/paulinus/opensfm-docker-base/blob/opencv3/Dockerfile uses opencv3 and does not install the contrib modules as @edgarriba pointed out. I'll add those, but for the moment just don't use that docker image.

**Comment by zwn** [comment]
As for the segfault - it does happen to me outside of docker too (on ubuntu 16.04).

**Comment by paulinus** [comment]
Ok, thanks for trying. It looks like a bug in opencv2. Works on osx, seems to fail on ubuntu. I won't have the time to look at it anytime soon, sorry.

Looking forward, I think it is better to concentrate on fixing the opencv3 case.

**Comment by jtlz2** [comment]
@paulinus Is there a workaround for using SIFT within Docker? :\

**Comment by jtlz2** [comment]
@paulinus Sorry to bother - is this fixed on opencv3 or is it still an issue there? Thanks!

**Comment by paulinus** [comment]
@jtlz2, SIFT on opencv3 inside docker works fine.

You need to build the docker image for opencv3. You can do so by editing the first line of the `Dockerfile` to
```
FROM paulinus/opensfm-docker-base:opencv3
```
then build the image normally with
```
docker build -t mapillary/opensfm -f Dockerfile .
```

**Comment by paulinus** [comment]
I'm closing this issue since we will not work on fixing SIFT in opencv2 and works fine with opencv3
