### ISSUE TITLE
Some questions about triangulation

### ISSUE THREAD

**Issue by shinsumicco** [mapillary/OpenSfM#141]
Hello,
I am a student and I am interested in SfM. I'd like to understand this library because I want to apply the library to some cases. So, I'm reading the source codes and I got some questions about triangulation process.

(1)
(a)This library uses the OpenGV function ([pyopengv.triangulation_triangulate](https://github.com/mapillary/OpenSfM/blob/3cc44ecbc09afb9da2b0a24f971d10d3102bafb9/opensfm/reconstruction.py#L246)) for triangulation in '[_two_view_reconstruction_inliers](https://github.com/mapillary/OpenSfM/blob/3cc44ecbc09afb9da2b0a24f971d10d3102bafb9/opensfm/reconstruction.py#L245)' function.
(b)But, the function for triangulation made of Eigen ([triangulate_bearings_midpoint](https://github.com/mapillary/OpenSfM/blob/e9a0ea573a572d4f73f235232c75d094f5f9d779/opensfm/src/csfm.cc#L81), [TriangulateBearingsMidpoint](https://github.com/mapillary/OpenSfM/blob/3cc44ecbc09afb9da2b0a24f971d10d3102bafb9/opensfm/src/multiview.cc#L159-L213)) is prepared in this library, and the library uses it in '[TrackTriangulator](https://github.com/mapillary/OpenSfM/blob/master/opensfm/reconstruction.py#L447)' class.

I think these functions have the same workings. Would you tell me why you use two different functions in (a) and in (b)?

(2)
[In bootstrap_reconstruction](https://github.com/mapillary/OpenSfM/blob/3cc44ecbc09afb9da2b0a24f971d10d3102bafb9/opensfm/reconstruction.py#L367-L369), bundle adjusting a single camera is done, and the retriangulate function is going, although the triangulation using 2 images ([triangulate_shot_features](https://github.com/mapillary/OpenSfM/blob/3cc44ecbc09afb9da2b0a24f971d10d3102bafb9/opensfm/reconstruction.py#L361)) has done before these processes (single camera bundle adjust and retriangulate).

Would you tell me why the single camera bundle adjustment and the retriangulation is to be done after the triangulation using 2 images?

Thank you very much for making time.

**Comment by paulinus** [comment]
hi @corikicchi, good that you are interested in SfM

The reason for (1) is that opengv triangulation only works for 2 images. The one implemented in opensfm is for n views.

The reason for (2) is that the `triangulate_shot_features` does additional checks on the points to what is done in `two_view_reconstruction`. In particular, it checks that the triangulated points are seen from a sufficiently large angle (`triangulation_min_ray_angle`). Also, notice that the points are never explicitly triangulated in `two_view_reconstruction` even if opengv needs to do that internally.

please let me know if that solve your questions. Thanks.

**Comment by corikicchi** [comment]
Thank you for the response.

I understood the reason for (1).

About (2), after triangulate_shot_features(...), [`bundle_single_view`](https://github.com/mapillary/OpenSfM/blob/3cc44ecbc09afb9da2b0a24f971d10d3102bafb9/opensfm/reconstruction.py#L367) and [`retriangulate`](https://github.com/mapillary/OpenSfM/blob/3cc44ecbc09afb9da2b0a24f971d10d3102bafb9/opensfm/reconstruction.py#L368) are called. It seems that `bundle_single_view` performs bundle adjustment of a rotation vector and a transition vector of shot 2, and `retriangulate` does re-triangulatation of 3D points using two images (shot 1 and 2).
(Please tell me if I'm saying something wrong.)
I think that bundle adjustment of camera pose and 3D points can be executed all at once. Would you tell me why the bundle adjustment of camera pose is performed alone, but the one of 3D points isn't done?

Thank you for making time for me.

**Comment by hy9be** [comment]
@shinsumicco Did you figured out about (2)? I am a bit confused about ``bundle_single_view`` and ``retriangulate``.

**Comment by shinsumicco** [comment]
@hy9be 
I think [`bundle_single_view`](https://github.com/mapillary/OpenSfM/blob/master/opensfm/reconstruction.py#L183-L234) executes **motion-only bundle adjustment**, which only optimizes the camera pose of `shot_id` under the **constant** 3D points and the **constant** intrinsic parameters of the camera.
After the pose optimization of `im2`, all the 3D points are re-triangulated, using the optimized new camera pose. Then, the camera pose is optimized again.
It seems that executing pose-optimization and re-triangulation separately results in more stable optimization of the camera pose of `im2`.
In addition, I think it consumes less time than local or global bundle adjustment.
As far as I know, [COLMAP](https://colmap.github.io/) also adopts re-triangulation procedure.
