### ISSUE TITLE
failed to do reconstructions

### ISSUE THREAD

**Issue by xialang2012** [mapillary/OpenSfM#143]
Hi @paulinus , please see this dataset if possible, I have failed to get correct result with errors. as below

> 2017-02-15 23:36:35,363 Good tracks: 12431
> 2017-02-15 23:36:36,203 Starting incremental reconstruction
> 2017-02-15 23:36:36,566 0 partial reconstructions in total.

You can find it here. http://modis-typechoupload.stor.sinaapp.com/image.zip

Those images are satellite images for the same area.
More parameters I used to run OpenSfM
```
processes: 8           
depthmap_min_consistent_views: 2     
depthmap_save_debug_files: yes     
feature_min_frames: 8000     
feature_process_size: 4096   
```

**Comment by paulinus** [comment]
Hi @xialang2012, thanks for testing.

There seems to be no change of perspective between those images. They all appear to be taken from the same place or to have been rectified to look like that.

For SfM to work, images taken from different points of view are required.  If you have access to the original, unrectified, satelite images you can try running on those.

**Comment by xialang2012** [comment]
There should be small change of each perspective between those images. The result shown in Softscan here
![qq 20170217105635](https://cloud.githubusercontent.com/assets/14291651/23050855/d27fa742-f4ff-11e6-84e3-741bd0f36a8c.jpg)
but the dense points produced by the Softscan is quite poor.

**Comment by paulinus** [comment]
If there's any change of perspective, it is tiny and not visible to the naked eye.  Standard SfM methods won't work for that case. So OpenSfM will not produce any output. Sorry.

You should try with images with larger baseline (say 5 degrees).

Not sure what Softscan does. It might just be outputting a flat surface.

**Comment by xialang2012** [comment]
Thanks, I will try another dataset.
