### ISSUE TITLE
Undistort fails for panoramas using OpenCV 3

### ISSUE THREAD

**Issue by paulinus** [mapillary/OpenSfM#146]
## Environment
Master branch
Mac osx
OpenCV 3.2.0

## Steps to reproduce:
Run `bin/opensfm undistort dataset` for a dataset containing equirectangular cameras.

## Expected result
Get an undistorted reconstruction and images

## Actual result 
```
$ bin/opensfm undistort dataset
OpenCV Error: Assertion failed (dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX) in remap, file /Users/paulinus/pro/opencv/modules/imgproc/src/imgwarp.cpp, line 4956
Traceback (most recent call last):
  File "bin/opensfm", line 34, in <module>
    command.run(args)
  File "/Users/paulinus/pro/OpenSfM/opensfm/commands/undistort.py", line 27, in run
    self.undistort_images(graph, reconstructions[0], data)
  File "/Users/paulinus/pro/OpenSfM/opensfm/commands/undistort.py", line 53, in undistort_images
    image, shot, subshot)
  File "/Users/paulinus/pro/OpenSfM/opensfm/commands/undistort.py", line 136, in render_perspective_view_of_a_panorama
    cv2.INTER_LINEAR)
cv2.error: /Users/paulinus/pro/opencv/modules/imgproc/src/imgwarp.cpp:4956: error: (-215) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function remap
```

**Comment by shreyaj** [comment]
@paulinus I am getting a similar error while using 360 images. Did you resolve it?

**Comment by paulinus** [comment]
I did not resolve it yet, sorry. The only workaround right now is to use OpenCV 2, if you work with 360 images.

**Comment by FarazKhalidZaki** [comment]
Hi @paulinus, can you please give me an idea that how to use OpenCV 2 to work with 360 images.

**Comment by paulinus** [comment]
@FarazKhalidZaki reconstruction from 360 images works out of the box. You should put the images in a project and [run OpenSfM normally](http://opensfm.readthedocs.io/en/latest/using.html).

You should make sure that the images are properly detected as 360 images. We use the [gpano metadata](https://developers.google.com/streetview/spherical-metadata) to detect panoramas.

To check that it has detected the panoramas open the `camera_models.json` file and check that the camera `projection_type` is `equirectangular`. If it is not, you can override the detection using [this procedure](http://opensfm.readthedocs.io/en/latest/using.html#providing-your-own-camera-parameters)

**Comment by dshahrokhian** [comment]
I just spent the entire night trying to fix this. Just wanted to share the solution that ended-up working for me: 

1. The line throwing the error is an assertion. Comment the line throwing the error: 
`<opencv folder>/modules/imgproc/src/imgwarp.cpp:4956: error: (-215) dst.cols < SHRT_MAX && dst.rows < SHRT_MAX && src.cols < SHRT_MAX && src.rows < SHRT_MAX in function remap`
2. Recompile OpenCV
3. Install it again

**Comment by cmidler** [comment]
Any update on this? Running into this error still in November 2017.

**Comment by paulinus** [comment]
@cmidler I've just pushed a fix for this. Can you verify that it works for you? thanks

**Comment by cmidler** [comment]
Pulled it down and it now works with opencv3.  Thanks!
