### ISSUE TITLE
Error when I run bin/data_all

### ISSUE THREAD

**Issue by Mudin** [mapillary/OpenSfM#149]
Environment:

macOS Sierra, 10.12.3
OpenCV 3.1.0
master branch

Issue:

I installed everything successfully and when I run the command `bin/run_all data/berlin/` it showing this issue:

ImportError: dlopen(/usr/local/lib/python2.7/site-packages/cv2.so, 2): Library not loaded: lib/libopencv_shape.3.1.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/cv2.so
  Reason: unsafe use of relative rpath lib/libopencv_shape.3.1.dylib in /usr/local/lib/python2.7/site-packages/cv2.so with restricted binary

**Comment by paulinus** [comment]
@Mudin, I have not seen this error before. From the text, it looks like a build problem in OpenCV. How did you install OpenCV?

**Comment by paulinus** [comment]
closing this for now. Let me know if you need further help
