### ISSUE TITLE
OpenSFM setup.py file returning error after building via Docker

### ISSUE THREAD

**Issue by bigw124** [mapillary/OpenSfM#150]
I am having an issue building OpenSFM. I am getting an error from running the setup.py file.

First, I am running Ubuntu 16.04 on VirtualBox. I installed Docker and ran 

    docker pull freakthemighty/opensfm

This image was successfully built. 

Additionally, I cloned the OpenSFM repository into my home folder. 

Next, I am supposed to build by running this in the main folder:

    python setup.py build

This is the resulting error

    walter@VirtualUbuntu:~$ python setup.py build
    Configuring...
    Traceback (most recent call last):
      File "setup.py", line 21, in <module>
        subprocess.Popen(['cmake','../opensfm/src'], cwd='cmake_build').wait()
      File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

**Comment by bigw124** [comment]
After doing some research, I discovered that I didn't have CMake installed. I installed Cmake and then reran setup.py and it worked this time! 

I thought the point of Docker was to have all the installations in one place. Not trying to be rude, I just honestly don't understand Docker that well. Is this an issue with the Dockerfile or am I missing something else?

Thanks,
Walter

**Comment by bigw124** [comment]
So I discovered I first need to run the docker before building. But this required cloning the git into the docker. Is that not part of the docker itself?

**Comment by bigw124** [comment]
I added the following to my Dockerfile before building and it appears to build OpenSfM correctly. You just need to run the docker image named docker-opensfm as follows: docker run -ti docker-opensfm


#Clone the OpenSfM Repository
RUN git clone https://github.com/mapillary/OpenSfM.git

#Add additional functions that for some reason didn't come with the docker file
Run apt-get update \ 
    && apt-get install python-networkx \ 
    python-exif \
    python-xmltodict

#Automatically build OpenSfM so that its prebuilt in the docker
Run cd OpenSfM && python setup.py build

**Comment by paulinus** [comment]
@bigw124 did you get what you needed from the answer [here](http://forum.mapillary.com/t/opensfm-setup-py-file-returning-error-after-building-via-docker/869) ?

**Comment by YanNoun** [comment]
No answer for a while, closing.
