### ISSUE TITLE
What is the file "track.csv"?

### ISSUE THREAD

**Issue by bryanibit** [mapillary/OpenSfM#152]
Hello! There is a file called track.csv produced by create_track.py.  I want to know the content about that. According to the code `tracks_graph.add_edge(image, str(track_id), feature=(x,y), feature_id=featureid, feature_color=(float(r),float(g),float(b)))`, I think the meaning of track.csv (the following line)

DSC07698.JPG	35782	4600	-0.470603	-0.127038	68	84	48
image name                    track_id     feature.x          feature.y         color.x/y/z

I don't know why the feature.x/y could be negative. Wish I could have an answer. Thank you.

**Comment by bryanibit** [comment]
![figure_1](https://cloud.githubusercontent.com/assets/13713063/24078880/84351780-0cb4-11e7-8ef9-7e3b8e30a328.png)
I used Berlin dataset, and then I got the result using the following words.
`import matplotlib.pyplot as plt  
 nx.draw(tracks_graph)
 plt.show()`
I still don't understand that due to so many covering objects.

**Comment by zwn** [comment]
> I don't know why the feature.x/y could be negative. Wish I could have an answer. Thank you.

The feature points are in normalized image coordinates, meaning the range is (-1,1).

**Comment by bryanibit** [comment]
The origin is located in the center of the photo. Thank you for your answer.

**Comment by paulinus** [comment]
Yes, the position of feature points is stored in normalized image coordinates. I've just added the definition of those in the documentation WIP http://opensfm.readthedocs.io/en/latest/geometry.html#coordinate-systems

**Comment by bryanibit** [comment]
@paulinus The doc needs to be finished as soon as possible, which is very useful for the new comers to understand the detail of the project, I think. Especially,  we need to add explanations about create_track, reconstruction and mesh, the three python file.
