### ISSUE TITLE
csfm.triangulate_bearings()

### ISSUE THREAD

**Issue by bryanibit** [mapillary/OpenSfM#156]
In 'reconstruction.py', there is a function called 'e, X = csfm.triangulate_bearings()'. The input of the function is undistorted feature point coordinates and rotation & translation matrix for each image. The output is 'e' and 'X', and then 'X' is added to reconstruction struct. I wonder what the 'X' presents. Is 'X' presents 3D feature points?

**Comment by paulinus** [comment]
Yes, `X` is the triangulated 3D point

**Comment by bryanibit** [comment]
what coordinate is `x` represented in? And where is the origin (0,0,0) of the coordinate? It is the camera coordinate system of the first image?

**Comment by YanNoun** [comment]
@bryanibit X is represented in the world coordinate frame.
