### ISSUE TITLE
Optimazation seen from the changing number of inliers in the process of reconstruction

### ISSUE THREAD

**Issue by bryanibit** [mapillary/OpenSfM#157]
I used data/berlin dataset to step debug the OpenSFM (old version but similar to the current one). I found the change of the number of inliers in reconstruction. The function 'two_view_reconstruction(p1, p2, camera1, camera2, threshold)' has two inlier filtering: the first result is 1143 and the second is 1148. Finally the function returns R, t and inliers. I wonder why we need to try twice inlier filtering. In the following, 'triangulate_shot_features(graph, reconstruction, shot_id, reproj_threshold, min_ray_angle)' adds 3D points to reconstruction structures and the number of inliers becomes 1119. What happened in the processing of the function? Wish gurus could give some explainations. Thank you!

**Comment by paulinus** [comment]
The two_view_reconstruction function does the reconstruction in two steps. First, it computes the pose using ransac, and then it refines the pose using non-linear optimization. The pose resulting from the non-linear optimization may have a different number of outliers than the one after ransac.

The pose is later used to triangulate points. When triangulating in addition to a small reprojection error, a minimal angle between the viewing rays is required. Thus, the number of triangulated points is often smaller than the number of inliers of the pose estimation.

I hope this solves your doubts. Cool that you look at the details @bryanibit !

**Comment by bryanibit** [comment]
Thank you for your explanations, which help me so much.

**Comment by bryanibit** [comment]
I would like to add something useful to 'http://opensfm.readthedocs.io/en/latest/using.html' after more understanding of the OpenSFM code. @paulinus
