### ISSUE TITLE
Cant correctly read XMP from equirectangular images

### ISSUE THREAD

**Issue by qpoisson** [mapillary/OpenSfM#158]
I have some equirectangular images. 

I check XMP in them with exiv2
 "exiv2 -px test_equirectangular.jpg" gives
 "Xmp.GPano.ProjectionType    XmpText    15  equirectangular"

In OpenSfm  exif.get_gpano_from_xmp() returns
('gpano: ', OrderedDict([(u'@rdf:about', u''), (u'@xmlns:GPano', u'http://ns.google.com/photos/1.0/panorama/'), (u'@GPano:ProjectionType', u'equirectangular')]))

Note the extra '@' character before GPano:ProjectionType, 
 It makes gpano.get('GPano:ProjectionType', 'perspective')  take the default value 'perspective'

I dont know where the extra '@' come from. Is this the issue in the original images or OpenSfm ?

**Comment by paulinus** [comment]
I can take a look. Can you share the original image?

**Comment by qpoisson** [comment]
@paulinus sure. please find below the image
![1](https://cloud.githubusercontent.com/assets/3370013/24680687/d34b814c-1989-11e7-8243-d264781a81ab.jpg)

**Comment by paulinus** [comment]
The gpano information in this image is stored as attributes of the `rdf:Description` tag, while it usually is stored as sub-tags.
This is the data on that image
```
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2"> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> <rdf:Description rdf:about="" xmlns:GPano="http://ns.google.com/photos/1.0/panorama/" GPano:ProjectionType="equirectangular"/> </rdf:RDF> </x:xmpmeta>
```
and this is the data on an image from a Ricoh theta
```
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.1.0-jc003">
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<rdf:Description xmlns:GPano="http://ns.google.com/photos/1.0/panorama/" about="">
<GPano:ProjectionType>equirectangular</GPano:ProjectionType>
<GPano:UsePanoramaViewer>True</GPano:UsePanoramaViewer>
<GPano:CroppedAreaImageWidthPixels>2048</GPano:CroppedAreaImageWidthPixels>
<GPano:CroppedAreaImageHeightPixels>1024</GPano:CroppedAreaImageHeightPixels>
<GPano:FullPanoWidthPixels>2048</GPano:FullPanoWidthPixels>
<GPano:FullPanoHeightPixels>1024</GPano:FullPanoHeightPixels>
<GPano:CroppedAreaLeftPixels>0</GPano:CroppedAreaLeftPixels>
<GPano:CroppedAreaTopPixels>0</GPano:CroppedAreaTopPixels>
<GPano:PoseHeadingDegrees>22.5</GPano:PoseHeadingDegrees>
<GPano:PosePitchDegrees>0.0</GPano:PosePitchDegrees>
<GPano:PoseRollDegrees>0.0</GPano:PoseRollDegrees>
</rdf:Description>
</rdf:RDF>
</x:xmpmeta>
```

Where does the image come from?
We can modify the code to accept both formats if that is a frequent case.

**Comment by YanNoun** [comment]
No answer for a while, closing.
