### ISSUE TITLE
Building on OS X 10.9 fails at "python setup.py build_ext --inplace"

### ISSUE THREAD

**Issue by chenosaurus** [mapillary/OpenSfM#16]
running build_ext
building 'opensfm.csfm' extension
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include/eigen3 -Iopensfm/src/third_party -Iopensfm/src/third_party/akaze/lib -Iopensfm/src/third_party/vlfeat -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c opensfm/src/csfm.cc -o build/temp.macosx-10.6-intel-2.7/opensfm/src/csfm.o -std=c++11
In file included from opensfm/src/csfm.cc:12:
In file included from opensfm/src/bundle.h:12:
In file included from /usr/local/include/ceres/ceres.h:37:
In file included from /usr/local/include/ceres/autodiff_cost_function.h:134:
In file included from /usr/local/include/ceres/sized_cost_function.h:41:
In file included from /usr/local/include/ceres/types.h:42:
/usr/local/include/ceres/internal/port.h:62:7: error: no member named 'shared_ptr' in namespace 'std'; did you mean 'boost::shared_ptr'?
using std::shared_ptr;
      ^~~~~
/usr/local/include/boost/smart_ptr/shared_ptr.hpp:722:36: note: 'boost::shared_ptr' declared here
    template<class Y> friend class shared_ptr;
                                   ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1

**Comment by paulinus** [comment]
thanks for reporting. I have no osx 10.9 close to debug.  According to [this](http://stackoverflow.com/questions/13445742/apple-and-shared-ptr), it seems related to clang using libstdc++.

Can you try compiling with the option -stdlib=libc++ ?

**Comment by chenosaurus** [comment]
hmm, a different error that doesn't really make sense ;(  Running that command directly works tho.  It only fails when running thru "python setup.py build_ext --inplace"

running build_ext
building 'opensfm.csfm' extension
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include/eigen3 -Iopensfm/src/third_party -Iopensfm/src/third_party/akaze/lib -Iopensfm/src/third_party/vlfeat -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c opensfm/src/csfm.cc -o build/temp.macosx-10.6-intel-2.7/opensfm/src/csfm.o -stdlib=libc++
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
error: command '/usr/bin/clang' failed with exit status 1

**Comment by paulinus** [comment]
It seems the -std=c++11 is missing on the last command.  Try using both -std=c++11 and  -stdlib=libc++

**Comment by chenosaurus** [comment]
I updated setup.py ln 107 to be:
    extra_compile_args=['-std=c++11', '-stdlib=libc++'],

still getting same error.  


$ python setup.py build_ext --inplace
running build_ext
building 'opensfm.csfm' extension
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include/eigen3 -Iopensfm/src/third_party -Iopensfm/src/third_party/akaze/lib -Iopensfm/src/third_party/vlfeat -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c opensfm/src/csfm.cc -o build/temp.macosx-10.6-intel-2.7/opensfm/src/csfm.o -std=c++11 -stdlib=libc++
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
error: command '/usr/bin/clang' failed with exit status 1

**Comment by chenosaurus** [comment]
Perhaps OS X is not the best env for working on this, I will try this in linux

**Comment by paulinus** [comment]
We do use OS X, should be no problem. It is weird that running the compilation line manually works, and not within setup.py.  Can you try building with cmake?

**Comment by chenosaurus** [comment]
This fixed the issue:

extra_compile_args=['-std=c++11', '-stdlib=libc++', '-mmacosx-version-min=10.7'],

now hitting a missing library, should be easier to fix:

/usr/bin/clang++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-2.7/opensfm/src/csfm.o -L/usr/local/lib -Lbuild/temp.macosx-10.6-intel-2.7 -lceres -lglog -lgflags -lboost_python -lvl -lmv -lakaze -o /Users/dchen/workspace/3rd-party/OpenSfM/opensfm/csfm.so
ld: library not found for -lvl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang++' failed with exit status 1

**Comment by chenosaurus** [comment]
Do you have any information on installing visualization library in os x?

**Comment by paulinus** [comment]
So vl is one of the static libraries generated by setup.py itself. Should be build when running

    python setup.py build_clib

before

    python setup.py build_ext --inplace

**Comment by chenosaurus** [comment]
Ah gotcha, got it built, thank you for the assistance!

**Comment by paulinus** [comment]
Cool, I've added the flags. Thanks for reporting!
