### ISSUE TITLE
bundle_single_view() function explainations

### ISSUE THREAD

**Issue by bryanibit** [mapillary/OpenSfM#162]
There is a function called bundle_single_view(graph, reconstruction, shot_id, config) in reconstruction.py. In OpenSFM, the function is called after finding space relationship and 3D points between first two images. Due to the encapsulation of csfm, I do not understand the feature of the function. I guess that the function tries to adjust the camera and points for the second image based on the rotation and translation with respect to the first image. Could you please settle my questions on detailed Info? @paulinus

**Comment by paulinus** [comment]
bundle_single_view adjusts the position of a single shot while keeping all other shot and points fixed. Its goal is to refine the position of a camera after it has first been computed. It is used after bootstrapping the reconstruction with 2 images and also each time an image is added to the reconstruction.

**Comment by bryanibit** [comment]
Thank you, @paulinus ! To be honest, I wonder how GPS positions are applied to process of Bundle Adjustment. For example, the following is showed the detail of bundle_single_view:
`ba.add_shot(
        str(shot_id), str(camera_id),
        r[0], r[1], r[2],
        t[0], t[1], t[2],
        g[0], g[1], g[2],
        shot['gps_dop'], False
    )`

**Comment by paulinus** [comment]
GPS position is stored in `g` and ends up being used during bundle [here](https://github.com/mapillary/OpenSfM/blob/master/opensfm/src/bundle.h#L508-L528)
We minimize the distance between the camera center (`-R^t t`) and the GPS position.

**Comment by bryanibit** [comment]
When executing `ba = csfm.BundleAdjuster()` and  `ba.run()`, the bundle adjustment minimizes the error between positions and camera centers .
