### ISSUE TITLE
What are preemptive features?

### ISSUE THREAD

**Issue by zwn** [mapillary/OpenSfM#163]
I see from the code base that there are regular and preemptive features (and lots of associated config). What is the difference between these two and what are they good for? Thanks.

**Comment by pmoulon** [comment]
Hi @zwn Preemptive features is a subset of the feature used to perform a first pass to find the best matching image pairs.
See here https://github.com/mapillary/OpenSfM/blob/079608da6284af05a431a09b91766f631038a284/opensfm/dataset.py#L293

The concept of preemptive matching have been introduced in the VSFM paper.
See section 3 there http://ccwu.me/vsfm/vsfm.pdf

**Comment by zwn** [comment]
Thanks @pmoulon! Yet another paper to read :wink:
