### ISSUE TITLE
Distortion coeficient up to K3 and additionally P1 and P2

### ISSUE THREAD

**Issue by specyfick** [mapillary/OpenSfM#165]
I'm playing with OpenDroneMap. I'm using a highly distorted images from GoPro Hero 3 Black.
Unfortunately distortions coefficients are passed to algorithm for K1 and K2.
Undistortion results are rather poor ,due to the fact that to cv2.undistort only K1 and K2 are passed, P1 and P2 are assumed zero, K3 zero to.
I've calibrated images with other tool. Poor results with K1 and K2.
After I calibrated it with additionally P1 and P2 and K2 coefs, results are nice.
I will try to code something with opensfm in undistort.py, but I'm not good in it.
Please do it that way, that people can pass distortion coefs K1 K2 K3 and P1 and P2 from file to all sfm algorithm, when using their own cameras, not well defined in files.

Some results.
Distorted image:
![cal2_1](https://cloud.githubusercontent.com/assets/25548431/25071514/55b54170-22ba-11e7-88a3-0a066199b8c0.JPG)

Rectified image with K1 and K2, P1 and P2 coefs. Can see still radial in the center.
![cal2__rect1-k2](https://cloud.githubusercontent.com/assets/25548431/25071516/55b8ca20-22ba-11e7-8553-c082e9ac7baa.JPG)

Rectified image with K1 and K2 and **K3** P1 and P2 coefs additionally gamma (alpha skew) estimates. Can see radial distortion eliminated in the center.
![cal2__rect1](https://cloud.githubusercontent.com/assets/25548431/25071515/55b7fec4-22ba-11e7-9fbe-e69a99f18dc1.JPG)

As we estimate more coefs a model is better. There are more coef K4 and K5. The callibration would be even better.
Please consider this improvement.
Best regards.
Pawel

**Comment by lamerman** [comment]
I vote for this issue, it's something to be done. For Galaxy S7 it's also impossible to undistort the image correctly without it.

**Comment by lamerman** [comment]
I implemented, but has not yet uploaded the K3 addition and after this improvement "Final cost" of bundle adjustment decreased for one order of magnitude for Galaxy S7. The latest requires three parameters for calibration. 

@paulinus is this patch needed in general? I then would prepare it properly. Why I ask maybe someone is already working on it and there is no sense in mine.

**Comment by paulinus** [comment]
@lamerman a patch would be greatly appreciated. One important thing that we will need to take care of is that it should still be possible to use only two distortion parameters. It will require some thinking on whether we add a new camera projection model or make the `perspective` one configurable.

**Comment by lamerman** [comment]
@paulinus I created a PR #225 . It has k3 working for perspective camera. The patch is not finished 100%, but please have a look at the general idea, whether it's ok to implement it like this.
