### ISSUE TITLE
code explaination about 'detect_features' in opensfm/bin

### ISSUE THREAD

**Issue by bryanibit** [mapillary/OpenSfM#166]
@paulinus I found the variable `p_unsorted` is a matrix of NumFeatures * 6. I wonder that the variable presents translation and rotation corresponding to the origin of the image, just like 
`T = frame(1:2) ;
 A = reshape(frame(3:6),2,2)) ;` ,where, frame is keypoint.
The first two ones of the variable are x and y, I do not know if the understanding is right.

**Comment by paulinus** [comment]
Yes, that is the case for the HAHOG features. For SIFT and SURF, `p_unsorted` is of size NumFeatures * 4.

We only use the first 3 columns of that matrix and assume they correspond to x, y and scale.

**Comment by bryanibit** [comment]
Thank you! I got it! After extracting hahog feature, order the feature points and descriptors according to size (scale).
