### ISSUE TITLE
Use OpenSfM exported result inside OpenMVS

### ISSUE THREAD

**Issue by btchouston** [mapillary/OpenSfM#167]
Hi all, 
I have a problem when i try to import the result produced by "export_openmvs" command inside OpenMVS. 
When i export, OpenSfM create a folder named "openmvs", and put the result file "scene.mvs" inside. 
But when i try to use that file inside OpenMVS, i get the following result : 
> 11:18:17 [App     ] Build date: Mar 17 2017, 11:50:31
> 11:18:17 [App     ] CPU: Intel(R) Core(TM) i3 CPU       M 370  @ 2.40GHz
> 11:18:17 [App     ] RAM: 7.60GB Physical Memory 5.70GB Virtual Memory
> 11:18:17 [App     ] OS: Linux 3.13.0-93-generic (x86_64)
> 11:18:17 [App     ] warning: no AVX compatible CPU or OS detected
> 11:18:17 [App     ] Command line: scene.mvs
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> Abandon (core dumped)

Can someone help to know what is hapening there ? Am i making a mistake ?
Tank you.

**Comment by paulinus** [comment]
Closing this one since the problem was discussed in https://github.com/cdcseacave/openMVS/issues/209
The solution is to update `Interface.h` https://github.com/mapillary/OpenSfM/issues/169
