### ISSUE TITLE
Error on extract_metadata

### ISSUE THREAD

**Issue by givanfp** [mapillary/OpenSfM#171]
Extracting exif metadata from the image attached gives the following error:
```
Traceback (most recent call last):
  File "env\Scripts\opensfm", line 34, in <module>
    command.run(args)
  File "C:\src\notebooks\env\lib\site-packages\opensfm\commands\extract_metadata.py", line 29, in run
    d = exif.extract_exif_from_file(data.load_image(image))
  File "C:\src\notebooks\env\lib\site-packages\opensfm\exif.py", line 84, in extract_exif_from_file
    exif_data = EXIF(fileobj)
  File "C:\src\notebooks\env\lib\site-packages\opensfm\exif.py", line 122, in __init__
    self.tags = exifread.process_file(fileobj, details=False)
  File "C:\src\notebooks\env\lib\site-packages\exifread\__init__.py", line 72, in process_file
    ord_(data[base + 3]))
IndexError: string index out of range
```

I tracked down the problem to the mode in wich image files are opened in dataset.py Line 68.

```
def load_image(self, image):
      return open(self.__image_file(image))
```

If the file mode is specified as read binary

```
def load_image(self, image):
      return open(self.__image_file(image), 'rb')
```
the exif is read witohut issues, but I'm not sure about the impact of this change in other parts.

![img_0600_geotag](https://cloud.githubusercontent.com/assets/1028460/25826742/55968d46-341e-11e7-9dc8-11f6bfcd4f96.JPG)

**Comment by paulinus** [comment]
The change you suggest looks good @givanfp, thanks! It will only affect windows.

Are you managing to get OpenSfM to work on windows? Please let us know how it works.

**Comment by givanfp** [comment]
@paulinus , it works with minimal changes, mostly in c++ libs code and static/shared linking, assuming VS 2015 is used, it has better c++11 support. The biggest work is on compiling all the other dependencies...
This changes are on my fork https://github.com/givanfp/OpenSfM. I didn't find any issues running in single process so far. Let me know if you would like to merge some of this changes on your repo so I can clean up and wrap the windows only code in #defines.
Thank you very much for the great work on giving us an OSS alternative!!
