### ISSUE TITLE
undefined symbol: _ZN2cv7imwriteERKSsRKNS_11_InputArrayERKSt6vectorIiSaIiEE

### ISSUE THREAD

**Issue by fuenwang** [mapillary/OpenSfM#173]
Hi:
I have used opensfm many times in Ubuntu14.04. However, in Ubuntu16.04 after I finish 
python setup.py build and create csfm.so. I got error when import csfm in python
ImportError: ./csfm.so: undefined symbol: _ZN2cv7imwriteERKSsRKNS_11_InputArrayERKSt6vectorIiSaIiEE
The version of my Opencv is 2.4.9.1, is this the root cause?
I have no idea how to deal with this. Thanks.

**Comment by paulinus** [comment]
This seems to be a problem with finding the opencv library that was used to compile `csfm.so`. Did you install your own version of opencv or are you using the one that comes with ubuntu?
