### ISSUE TITLE
Generate a mesh file with faces

### ISSUE THREAD

**Issue by btchouston** [mapillary/OpenSfM#176]
Hi All, 
I am trying to generate a mesh file with faces, using OpenSfM. 
My question is : **can i use "faces" field that is inside "reconstruction.meshed.json" to add faces to the current generated mesh file ?**

_Note : The current mesh have only vertices_

Tank you.

**Comment by paulinus** [comment]
The faces in `reconstruction.meshed.json` are triangles whose vertices are from the sparse set of reconstructed points. That mesh is in general quite coarse and noisy.

If you need something more detailed, you need to run the dense reconstruction. The output will be a denser set of points from which you can build a mesh.

**Comment by belavina** [comment]
I don't think there is complete implementation of surface reconstruction pipeline (correct me if I am wrong). @paulinus  Is there a way to export depth maps to openMVS format (to complete meshing)? export_mvs command seems to export sparse cloud.

**Comment by paulinus** [comment]
There is no way to export the depth map. As you say, you can export the sparse reconstruction and let openMVS build the depth map and the meshes.

**Comment by cmidler** [comment]
Are there plans to be able to send a dense point cloud to openMVS?  I am getting vastly different results from the dense cloud I get from openSFM in comparison to openMVS. The cloud from openSFM seems to show more detail in my instance.

**Comment by paulinus** [comment]
@cmidler i've never tried using the point cloud generated by OpenSfM as an input for openMVS to generate the mesh. When i've needed a mesh, i've used openMVS from the start and let it generate the point cloud.

OpenMVS point cloud should be similar to OpenSfM's one. If you observe it otherwise, it might be that exporting is not working properly. Do you have an example to share?

**Comment by cmidler** [comment]
You can see the example via the dropbox link: https://www.dropbox.com/s/8kyguw42it73wah/example.zip?dl=0

I am attempting to reconstruct a living room from 8 pictures in the room taken from the middle of each wall and corner looking at the opposing wall and corner respectively. I've also attached the dense point cloud ply from opensfm: merged.ply and openmvs: scene_dense.ply along with the output mvs file generated via the export_mvs call: scene.mvs. The images and config.yaml are also there.

**Comment by paulinus** [comment]
What is happening here is that there is little overlap between the images. If you take more images, say 30, you will get much better results both with OpenSfM and with openMVS.

When generating the dense point cloud, there are consistency checks that require a point to be seen from multiple images. In opensfm you can configure the minimum number of images and in your `config.yaml` it is set to 2
```
depthmap_min_consistent_views: 2      # Min number of views that should reconstruct a point for it to be valid
```
openMVS default is set to 3, and that is why you are getting fewer points there.

Best is to take more images and to set the parameter to 3.

**Comment by cmidler** [comment]
Thank you for the quick response. Do you have any documentation on a best practices for different types of images and configuration files? I see the config.py file which has the defaults, but I haven't found great documentation for what everything means and when I should use which parameters.  I could easily see interior room pictures differing in their requirements vastly from street images or aerial images.

Thanks again!

**Comment by YanNoun** [comment]
@cmidler you can use the OpenMVS export script that is currently used by OpenDroneMap : https://github.com/mapillary/OpenSfM/blob/master/opensfm/actions/export_openmvs.py
