### ISSUE TITLE
export bundle produces two bundle files

### ISSUE THREAD

**Issue by xialang2012** [mapillary/OpenSfM#189]
It seems the current update produces two bundle files when using export_bundler, e.g. bundle_r000.out and bundle_r001.out. 

The reason for this may due to the current update results in larger camera track file for tracks.csv than before. @paulinus

**Comment by paulinus** [comment]
`export_bundler` creates one bundle.out file for each reconstruction. If you get two files, it means that not all images did get connected into a single reconstruction. So you got two independent reconstructions.
