### ISSUE TITLE
Can OpenSfM export to OpenMVS when projection type is equirectangular?

### ISSUE THREAD

**Issue by happyfrank** [mapillary/OpenSfM#192]
as the title says.

**Comment by paulinus** [comment]
It can now, @happyfrank

When undistorting a reconstruction, equirectangular cameras are converted to 6 perspective cameras (the faces of a cube map).

Exporting openmvs will export the generated perspective views.

This will work on current master. Commit https://github.com/mapillary/OpenSfM/commit/a8cb97ee57b20f109e2502acc1e499605e828edb fixes the exporter to use the undistorted reconstruction.

**Comment by happyfrank** [comment]
Thanks. ^v^ @paulinus
