### ISSUE TITLE
Bundle Adjustment seems like no use much.

### ISSUE THREAD

**Issue by bryanibit** [mapillary/OpenSfM#193]
There are some photos output from before and after BA. 

![baim1](https://user-images.githubusercontent.com/13713063/27811695-91b5ece6-609b-11e7-8578-f88a98e1ee7f.jpg)
![im1](https://user-images.githubusercontent.com/13713063/27811977-0b939eb2-609e-11e7-94c8-e22e95509346.jpg)
![baim2](https://user-images.githubusercontent.com/13713063/27811990-16221386-609e-11e7-9f0d-0c019efc7529.jpg)
![im2](https://user-images.githubusercontent.com/13713063/27812069-9bfcf692-609e-11e7-82ec-d3a86b708650.jpg)

BAim presents 2d points (which are common tracks for the two images through RANSAC and optimization and shown with red color) and 3D points reprojected back to image (green color) after BA in bootstrap_reconstruction function. The two images called "im*.jpg" presents 2d points (red) and 3D points reprojected back to image (green) before BA in bootstrap_reconstruction function. 
I also provide the images from dataset, the same with above operation.
https://drive.google.com/drive/folders/0B5ZS23gtIE-hUVpYSzRkR1dLUnM?usp=sharing

**Comment by paulinus** [comment]
Hi @bryanibit,

I'm not sure to understand the experiment. Are you saying that the reprojected points do not move match after applying BA?

That would be normal since BA is supposed to do small adjustments to make everything fit better. Depending on how good the reconstruction is before BA, it can happen that BA does move things very little.

**Comment by bryanibit** [comment]
@paulinus I am so glad for your reply. The reprojected points do not match feature points in the images. In other words, I wanna see big or obvious movement after BA. What should I do? Do I need to choose two images with false matches?

**Comment by YanNoun** [comment]
@bryanibit as mentioned, the bundle adjustment doesn't do magic if the reconstruction is already good enough. Try adding some decent noise to the input 3D points if you want to observe some decent improvment.
