### ISSUE TITLE
Tips for achieving denser reconstructions

### ISSUE THREAD

**Issue by sola92** [mapillary/OpenSfM#202]
Right now, the dense reconstructions are still pretty sparse; it seems like like not enough features are being extracted. What factors play into improving dense reconstructions. Any tips for how to improve this?

Data set for reference:
[dataset.zip](https://github.com/mapillary/OpenSfM/files/1164384/dataset.zip)

**Comment by erikreed** [comment]
Have you tried exporting to openMVS and running `DensifyPointCloud` to produce a dense .ply? 

Pau has a nice writeup on it: http://blog.mapillary.com/update/2016/10/31/denser-3d-point-clouds-in-opensfm.html

**Comment by paulinus** [comment]
For this example, the object has little texture. The way the pictures are taken is good, with lots of overlap, but since the object is shiny and textureless, there are few points that can be reconstructed.
