### ISSUE TITLE
Indoor support?

### ISSUE THREAD

**Issue by mudin3i** [mapillary/OpenSfM#203]
Hello. Thanks for the awesome work!

This is really cool.
But I have an issue when I try to use for indoor.
I have few photos taken by Ricoh Theta. But the result is not good.
I tried to change config and retake photos several times.
Does it make positioning and auto rotation for indoor 360 images?
What is the best configuration for this situation?

Thanks in advance

**Comment by foolsmate** [comment]
Is there an actual camera model for the specific camera that you are using?

**Comment by paulinus** [comment]
Hey @Mudin, OpenSfM can handle equirectangular images like the ones from the Ricoh Theta. One important thing to check is that the images are actually detected as being equirectangular. Could you check that the `projection_type` field in the `camera_models.json` is set to `equirectangular`?

If it is not, you can follow the instructions here http://opensfm.readthedocs.io/en/latest/using.html?highlight=camera_models#providing-your-own-camera-parameters to override the detected parameters. You can rename the `camera_models.json` file to `camera_models_overrides.json` and replace `perspective` with `equirectangular` in it.

**Comment by YanNoun** [comment]
No answer for a while, closing.
