### ISSUE TITLE
Nothing happens after feature extraction

### ISSUE THREAD

**Issue by bulyginlev** [mapillary/OpenSfM#208]
Hello.

I run opensfm with dockerfile. When I try to use SIFT or SURF on my dataset, nothing happens after the extraction. HaHOG works fine. OpenCV in python do sift and surf on my dataset good.

```
root@1686262c26bd:/source/OpenSfM/bin# sh opensfm_run_all ../data/chair_light_224
opensfm_run_all: 5: opensfm_run_all: Bad substitution
libdc1394 error: Failed to initialize libdc1394
2017-08-25 19:22:29,395 Extracting focal lengths for image 2.jpg
2017-08-25 19:22:29,398 Extracting focal lengths for image 1.jpg
2017-08-25 19:22:29,399 Extracting focal lengths for image 3.jpg
libdc1394 error: Failed to initialize libdc1394
2017-08-25 19:22:29,615 Extracting ROOT_SIFT features for image 2.jpg
2017-08-25 19:22:29,615 Extracting ROOT_SIFT features for image 1.jpg
2017-08-25 19:22:29,616 Extracting ROOT_SIFT features for image 3.jpg
```
I waited few hours, but nothing happens.

SIFT and SURF work fine on other datasets including Berlin.

My images: 
![3](https://user-images.githubusercontent.com/29382809/29729421-b84288b6-89e4-11e7-825b-37e706a365f3.jpg)
![1](https://user-images.githubusercontent.com/29382809/29729422-b8452468-89e4-11e7-9e34-23bc5e106ad9.jpg)
![2](https://user-images.githubusercontent.com/29382809/29729423-b848af02-89e4-11e7-8bc5-1b940d4d079f.jpg)

What I can do to fix this error? Thank you.

**Comment by paulinus** [comment]
@bulyginlev, SIFT and SURF might not be available on the default opencv installation used in the dockerfile. If you want to use those you might need to install OpenCV from source. In any case, HAHOG will give similar results.

Note however that it is likely that no feature descriptor will find any matching for those images. The low resolution, the noise, and the wide-baseline make it really hard to find correspondences. If you really need to use that camera, you could try taking more pictures closer to each other and lightning the scene up.
