### ISSUE TITLE
Example 360 panoramas

### ISSUE THREAD

**Issue by tejaswidp** [mapillary/OpenSfM#209]
It would be great if you could add sample 360 panoramas for demonstrating SfM, similar to the berlin dataset.

**Comment by paulinus** [comment]
Hey, here is an example taken with an LG360 by @oscarlorentzon 

https://www.dropbox.com/sh/3vabbmrhqqbagp5/AABi14O2tWMbxAX91jaaQY77a?dl=0

It includes a `camera_models_overrides.json` file which is necessary for some cameras and might be hard to get right.

Also added a link to the docs here http://opensfm.readthedocs.io/en/latest/using.html#providing-your-own-camera-parameters
