### ISSUE TITLE
OpenSfM crashes if there's any images with no features

### ISSUE THREAD

**Issue by shooshx** [mapillary/OpenSfM#218]
When I'm running OpenSfM on a large set of images and for one image it fails to extract any features, for instance due to the image being completely blank white or black, the matching phase fails when it tries to look for the features file.  
What is the best way to deal with this? features side to produce an empty file or matching side to handle this case correctly?

**Comment by YanNoun** [comment]
@shooshx no-features images are now handled and shouldn't cause a crash.
