### ISSUE TITLE
Change weighting of GPS position 

### ISSUE THREAD

**Issue by KommandorKeen** [mapillary/OpenSfM#219]
HI There,
I am injecting RTK GPS positions into my EXIF headers.
Where do I need to tweak my configs to make best use of this.
OR
What additional info do I need to add to the EXIF header to ensure the current scripts utilise this fully?

I am using EXIFtool for the injection and have confirmed that the precision held within the exif is millimetre or better:

I am using Open SFM as part of the OpenDroneMap pipeline/workflkow..

Thanks in advance for your insight and wisdom!

**Comment by YanNoun** [comment]
@KommandorKeen you can control the GPS accuracy by controlling the `{gps : {dop` value in the EXIF files : https://www.opensfm.org/docs/using.html#providing-additional-metadata

If you plan to injecting it directly in the EXIF with EXIFTool, then the tag `GPSDOP` is the one that is read : https://github.com/mapillary/OpenSfM/blob/master/opensfm/exif.py#L343
