### ISSUE TITLE
Dense depth map pixels' neighbour images.

### ISSUE THREAD

**Issue by danng007** [mapillary/OpenSfM#221]
Hi,

I'm looking inside the convert sparse depth image to dense depth image part. I want to know is that possible to get all pixels' neighbour image id and each image's pixel position. ( **I want to know a point 3D's 2D location in each correlated image.**)
In depthmap.cc the most close one is in PruneDepthmap function, but seems it only give the most reliable neighbour rather than all possible neighbours? Many neighbours deleted in the iteration of PathMatchUpdatePixel() function. 
Thanks so much if you can help me.

Best,
Wantao

**Comment by YanNoun** [comment]
@danng007 All neighbors are only stored during the depthmaps computation, then only the most reliable is stored. However, all neighbors images of a given image are computed here : https://github.com/mapillary/OpenSfM/blob/master/opensfm/dense.py#L31
