### ISSUE TITLE
Translating reconstruction.json shots to real world positions

### ISSUE THREAD

**Issue by jjordan007** [mapillary/OpenSfM#222]
I am trying to get real distances between my camera "shots". I am looking at the reconstruction.json but am unclear what coordinate system is used. My images do not have GPS data but is that something I need for generating in world coordinates. Or am I going the wrong path and should be looking at another file?

Thank you,
Josh

**Comment by danng007** [comment]
Hi, I'm currently researching the same problem here. In the output there is one reconstruction.nvm comes from reconstruction.json. The coordinate of shots has little bit different between the two files. And nvm's coordinates calculated in types.py: get_origin function. In this function, the comment wrote: "The origin of the pose in world coordinates.". So I guess maybe it's the final world coordinate for each shot's centre? 
I'm not 100% sure, just give a clue, and please also reply me if you got any more idea.

**Comment by bryanibit** [comment]
The coordinate system in reconstruction.json file is based on one of the two-view initialization. The center of the coordinate is its camera center. The x-axis is downward and the y-axis is rightward. Of course, the z-axis is forward. The scale is in pixel, I think.

**Comment by jjordan007** [comment]
danng007 - I do not see the .nvm.  I only see reconstruction.json and reconstruction.meshed.json. I ran opensfm_run_all, opensfm undistort, and opensfm compute_depth_maps. Is there something I need to run?

bryanbit - Please forgive my ignorance, but I think I am misunderstanding. If it is pixels wouldn't I be able to translate to real world with a scalar. To try it, I ran 2 datasets. One with cameras 1 ft apart and another 2 ft apart. I calculated the average distance (~3.5 units) for 1 ft. So i figured for 2 ft it would be ~7.0 units but got ~3.47. Is this not the way it works?

**Comment by angussmitchell** [comment]
Did anyone end up finding a way to transform the reconstruction.json's coordinate system to a GPS coordinate system?

I'm still confused as to why the reconstruction.json shots has a property called "gps_position" that is not in fact GPS, but some Cartesian image coordinate system

**Comment by angussmitchell** [comment]
Update: the command "export_geocoords" may provide some relief for this issue:

https://github.com/mapillary/OpenSfM/blob/master/opensfm/commands/export_geocoords.py

**Comment by jjordan007** [comment]
I am unsure what the GPS system is because mine is all zeros. I ended up using the rotation and translation arrays from the reconstruction.json with opticalCenter, rotate, makeRotationAxis, and applyMatrix4 (from viewer/reconstruction.html) to get relative 3D coordinates.

I was never able to to figure out why scaling was inconsistent so used two shots with a known distance between them and scaled everything by that.

**Comment by YanNoun** [comment]
@jjordan007 @danng007 @bryanibit as @angussmitchell mentioned, `export_geocoords` wille xport the reconstruction in geographical coordinates.
