### ISSUE TITLE
how to show the imagePlane projection image a little smaller and a little before

### ISSUE THREAD

**Issue by smeeteday** [mapillary/OpenSfM#227]
In opensfm's reconstruction.html
The imagePlane display is too large.
The display position is also displayed behind the pointcloud position much later.
To show a little smaller a little before
What should I do?

**Comment by paulinus** [comment]
There is a slider to set the size of the image plane under the "Controls" tab.
Otherwise, you may want to load the `reconstruction.meshed.json` so that a coarse mesh is used instead of a plane.

**Comment by smeeteday** [comment]
thank you,so much.

Corresponds to shot_id in reconstruction.meshed.json
I use vertixes to display ImagePlane frustumically.
However, it is displayed in the atmosphere where the bottom of the frustum faces upward.
The bottom edge of the image of the camera held horizontally becomes horizontal.
Originally the bottom part, gradually downward, like a slide
I want to display so that it goes gently downward.
