### ISSUE TITLE
build on centOS

### ISSUE THREAD

**Issue by epifanio** [mapillary/OpenSfM#23]
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16)
trying to build i got this from python setp.py install :  
https://gist.github.com/anonymous/abc9f3a7725ec8c72519
that-s the same as : 
https://gist.github.com/anonymous/a4ad4bd0d6ae56a22b92

Thanks for any advice.

**Comment by paulinus** [comment]
That seems to be a problem with the gflags namespace. Depending newer versions of gflags use the gflags namespace and old ones use the google namespace. We added a patch for this, but it seems to fail in your case.

I've just modified the patch. Can you retry with the last commit on master?

**Comment by epifanio** [comment]
thanks to look into this.
I tried on a fresh clone, but the error persist.
Attaching the complete log : 
https://gist.github.com/e63b99e9307488e4e501

**Comment by paulinus** [comment]
i tried another way of supporting both namespaces. Could you try again?
thanks

**Comment by epifanio** [comment]
Thanks @paulinus , the build now works fine.
I tried to run the example from the data/berlin directory : 

```
[root@qi-gis-02 OpenSfM]# ls 
bin  build  cmake_build  config.yaml  data  LICENSE  opensfm  README.md  requirements.txt  setup.py  viewer
[root@qi-gis-02 OpenSfM]# ls data/
berlin
[root@qi-gis-02 OpenSfM]# bin/run_all data/berlin/
Extracting focal lengths for image 01.jpg
Extracting focal lengths for image 02.jpg
Extracting focal lengths for image 03.jpg
Extracting SIFT features for image 01.jpg
bin/run_all: line 7:  8898 Segmentation fault      (core dumped) $DIR/detect_features $1
[root@qi-gis-02 OpenSfM]# 
```

I did a build from where i left before, I'll try again with a clean clone.
Any hints on how to debug the segfault ? (enabling flasgs for debug in cmake?)
Thanks!

**Comment by godspeed1989** [comment]
One better solution for gflags namespace problem :)

```diff
-#ifndef gflags
-namespace gflags=google;
-#endif
+// gflags 2.1 issue: namespace google was changed to gflags without warning.
+// Luckily we will be able to use GFLAGS_GFAGS_H_ to detect if it is version
+// 2.1. If yes, we will add a temporary solution to redirect the namespace.
+// TODO: Once gflags solves the problem in a more elegant way, let's remove
+// the following hack.
+#ifndef GFLAGS_GFLAGS_H_
+namespace gflags = google;
+#endif  // GFLAGS_GFLAGS_H_
```

from https://github.com/BVLC/caffe/commit/148eb67d66e584041c499b6ef4ae9e47916dd12b

**Comment by epifanio** [comment]
Guys, Is this issue the good place where to continue debugging the segfault problem, or should I open a new issue for it ?

**Comment by paulinus** [comment]
@epifanio lets continue debugging here.  Two things to try:

1. Use another feature type to see if the problem is on the SIFT code. Edit `data/berlin/config.yaml` and replace SIFT by AKAZE, HAHOG or SURF.
2. Compile with debug info:
  - on the `cmake_build` directory, run `cmake -DCMAKE_BUILD_TYPE=Debug`. Then `make`
  - then run python inside gdb (`gdb python`). And run the feature detection script (`run bin/detect_features data/berlin`)
  - if it segfaults, run `bt` to get the backtrace an see which function is segfaulting.

@godspeed1989 thanks for finding this solution. Do you want to put it on a PR?

**Comment by epifanio** [comment]
I enabled debug in ```setup.py``` with : ```subprocess.Popen(['cmake','../opensfm/src', '-DCMAKE_BUILD_TYPE=Debug'], cwd='cmake_build').wait()``` 
The segfault happen with all three methods, this the gdb output : 

https://gist.github.com/467ff69f3a4473030452

It looks like OpenCV has problems, it is a src build .. i'l try to make a fresh build (i'm using OpenCV master from git, can be an issue ?)

**Comment by epifanio** [comment]
Maybe the build is looking for the wrong opencv .. i found 2 cersion are installed on my system :  

```
[root@qi-gis-02 OpenSfM]# /usr/local/lib/libopencv_core.so #tab
libopencv_core.so         libopencv_core.so.2.4.10  libopencv_core.so.3.0.0   
libopencv_core.so.2.4     libopencv_core.so.3.0     
```

It should use the 3.0 while the 2.x is picked up .. i guess i have 2 option: 
* remove opencv2.x
* force the cmake in opensfm to use libopencv.so.3.x instead of .2. 
i'll try to work on this.

**Comment by epifanio** [comment]
few progresses, i manually removed opencv from my system (t was messy with 3 different installation, yum system, src built V2 and src built V3) i then reinstalled opencv (git master) and reinstalled OpenSfm (fresh clone) . Now trying to run the OpenSfM example i run in this error : 

```
[root@qi-gis-02 OpenSfM]# bin/run_all data/berlin/
Extracting focal lengths for image 01.jpg
Extracting focal lengths for image 02.jpg
Extracting focal lengths for image 03.jpg
Extracting SIFT features for image 01.jpg
Traceback (most recent call last):
  File "/usr/local/src/OpenSfM/bin/detect_features", line 53, in <module>
    detect(image)
  File "/usr/local/src/OpenSfM/bin/detect_features", line 20, in detect
    p_unsorted, f_unsorted = features.extract_feature(data.image_as_array(image, grayscale=True), data.config)
  File "/usr/local/src/OpenSfM/opensfm/features.py", line 192, in extract_feature
    return extract_features_sift(image, config)
  File "/usr/local/src/OpenSfM/opensfm/features.py", line 79, in extract_features_sift
    detector = cv2.FeatureDetector_create('SIFT')
AttributeError: 'module' object has no attribute 'FeatureDetector_create'
[root@qi-gis-02 OpenSfM]# 
```

seems taht this is an incompability between OpenSfM and latest OpenCV, @paulinus can you confim this ? if yes ..  What you suggest to do? is it possible to have OpenSfM working with latest OpenCV or should I revert to a previouse version ? 

Thanks a lot!

**Comment by paulinus** [comment]
@epifanio, did you install opencv version 3 from git?  We are using version 2 of opencv. Version 3 is not backward compatible. That might explain the crashes.

**Comment by epifanio** [comment]
@paulinus i rebuilt opencv sable (2.4.x) and rebuilt OpenSfM from a fresh clone, this the build log :  
```https://gist.github.com/9de7d90d7057e3e65b74```
some progresses with the test, here is the log : 
```https://gist.github.com/955d2f70e105d16a78cc```

This the error:

```
2015-04-18 17:33:50,380 Good tracks: 1269
Traceback (most recent call last):
  File "/usr/local/src/OpenSfM/bin/create_tracks", line 46, in <module>
    data.save_tracks_graph(tracks_graph)
  File "/usr/local/src/OpenSfM/opensfm/dataset.py", line 313, in save_tracks_graph
    fout.write('%s\t%d\t%d\t%g\t%g\t%d\t%d\t%d\n' % (image, track, fid, x, y, r, g, b))
TypeError: %d format: a number is required, not str
```

**Comment by paulinus** [comment]
@epifanio Nice that you got the build working! The error was caused by recent changes in how we store the tracks. Last commits should fix the issue just as you did. Thanks!
