### ISSUE TITLE
Why is imagePlaneOld Mesh necessary? in reconstruction.html

### ISSUE THREAD

**Issue by smeeteday** [mapillary/OpenSfM#230]
In addition to imagePlane Mesh
Why is it necessary to use imagePlaneOld Mesh?
And when dispose the material and geometry of imagePlane
Why not remove imagePlane Mesh?

**Comment by paulinus** [comment]
When moving from one image to another, `imagePlaneOld` is the mesh for the previous image. That is needed to do a smooth transition between the two textures.

The geometry and material are disposed right before being replaced by the geometry and material of the new image. The Mesh object, which uses the geometry and material, is reused.

**Comment by smeeteday** [comment]
Sincerely yours.
thank you.
