### ISSUE TITLE
explanation of tracks.csv file

### ISSUE THREAD

**Issue by angussmitchell** [mapillary/OpenSfM#243]
Hi, It would be great if someone could explain what each field in the "tracks.csv" file signifies. 

For example, the [kungsgatanparken](https://www.dropbox.com/sh/3vabbmrhqqbagp5/AABi14O2tWMbxAX91jaaQY77a?dl=0) 360 dataset results:

`05.jpg	14478	14445	0.174087	-0.0307692	57	63	79 `

I can't seem to make much sense of any of these values, seeing as none seem to match up to image coordinates, or GPS coordinates.

The reason for wanting to know this is that I would like to export the camera locations for use in geolocating imagery. If I can figure out what the tracks.csv file contains, I can do this myself. 

It should also be noted that this information is not contained within [the docs](http://opensfm.readthedocs.io/en/latest/). 

Thanks in advance

**Comment by agmarrugo** [comment]
Is it normalized image coordinates?

**Comment by angussmitchell** [comment]
@agmarrugo Yes I think that the fourth and fifth fields could be normalized image coordinates as defined in [the docs](http://opensfm.readthedocs.io/en/latest/geometry.html). Thanks for the tip, now I just need to figure out what the last three (57 63 79), and the second and third (14478 14445) fields mean.

**Comment by paulinus** [comment]
Each row represents one image feature, and has the following values:
`image, track_id, feature_id, x, y, r, g, b`

The functions writing and reading the tracks are here https://github.com/mapillary/OpenSfM/blob/796db7f9c5ed64600e0669ea86850649ca68e8aa/opensfm/dataset.py#L490-L513

I'm sorry there are no docs on that. The format has not changed in a long while but, if possible, it is better not to rely on it being like this forever. What do you want to do with the file?

**Comment by angussmitchell** [comment]
Thanks @paulinus, this information is valuable. I just wanted to know about how the point information was stored, because I want to do some processing with the intermediate results - most importantly I want to export the camera locations to get a geo-referenced path for the cameras (which I now realize is not done with the tracks.csv file. Thanks for you're answer.

**Comment by paulinus** [comment]
@angussmitchell, in which coordinate system do you want to export the camera path?
We have an open issue, #199, which we plan to work on soon.

**Comment by angussmitchell** [comment]
@paulinus 
I'd preferably like to export the camera path in UTM GPS coordinates (where GPS coordinates are provided by the user).  Thanks for making me aware of the issue, that will be a very useful feature!

**Comment by JKViswanadham14** [comment]
I am not able to read tracks.csv file. can some one help me with a code?

**Comment by FreakTheMighty** [comment]
@paulinus what does a `track_id` provide here? 

Given the format, `image, track_id, feature_id, x, y, r, g, b`, I would think that any `feature_id` found across multiple `image` keys, would be a track.

Thanks in advance for the help.
