### ISSUE TITLE
Running Step3: Go to the root of the project and run bin/opensfm_run_all data/DATASET_NAME

### ISSUE THREAD

**Issue by ShilongLIU** [mapillary/OpenSfM#245]
Hi All,

When I completed the previous setup and I was running this line; however, everytime I will came across the issue that: Traceback (most recent call last):
  File "/Users/Shalon/Desktop/Geointeractive/OpenSFM/OpenSfM/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/Users/Shalon/Desktop/Geointeractive/OpenSFM/OpenSfM/opensfm/commands/__init__.py", line 1, in <module>
    import extract_metadata
ModuleNotFoundError: No module named 'extract_metadata'

Has anybody came across issue?
I tried changing PYTHONPATH to both python2 and 3.

**Comment by ShilongLIU** [comment]
The thing is under that folder, I do can find that module called 'extract_metadata'; however not sure why it's always reminding me this error.

**Comment by paulinus** [comment]
Not seen it before. Are you using python 2?
Currently, OpenSfM runs only on python 2.

**Comment by ShilongLIU** [comment]
This helps a lot!
