### ISSUE TITLE
When I use pip install -r requirements.txt, I encounter  a problem

### ISSUE THREAD

**Issue by AlphaSunny** [mapillary/OpenSfM#246]
![default](https://user-images.githubusercontent.com/32600242/33524071-99b9379a-d850-11e7-983a-38ff52f0b2e6.PNG)

when I encounter this problem, i just try to use python setup.py build. another problem burns.

**Comment by paulinus** [comment]
closing this one seems it looks redundant with #247. Lets use the other one issue
