### ISSUE TITLE
Cmake - CMake Error at modules/FindNumPy.cmake:62

### ISSUE THREAD

**Issue by ShilongLIU** [mapillary/OpenSfM#248]
Hi All,

I am doing the set up, following the readme instruction. 
However, when I was running this line: sudo cmake .. -DBUILD_TESTS=OFF -DBUILD_PYTHON=ON

There is always one error: CMake Error at modules/FindNumPy.cmake:62 (message):
  NumPy import failure:

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

  ImportError: No module named numpy

Call Stack (most recent call first):
  python/CMakeLists.txt:9 (find_package)

If need, I later will provide the whole CMakeOutput.log.

I am sure that I have installed numpy, since I can import this library under python3.

**Comment by ShilongLIU** [comment]
If anybody knows the solution, pls offer me a hint. Much appreciation for that!

**Comment by nicozorza** [comment]
I'm dealing with the same issue. Did you resolve it? I'm using python2.7 with numpy correctly installed.
