### ISSUE TITLE
loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value

### ISSUE THREAD

**Issue by AaronQi0731** [mapillary/OpenSfM#250]
The warning about "loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value" will cause any bad influences of the result of reconstruction?

**Comment by paulinus** [comment]
Hi @AaronQi0731, this warning can be safely ignored.

You check the details here https://github.com/tomMoral/loky/issues/103
