### ISSUE TITLE
About a params submodel.

### ISSUE THREAD

**Issue by AaronQi0731** [mapillary/OpenSfM#251]
Dear pau

I quite do not understand about the meaning of these params below (the params see below), I would like to know what is the meaning of submodel? and the submodel size are including 80 images, so what is the meaning and influence about this number? it is means submodel only contain 80 images or what? I would like to know these three questions. Many thx. 

# Params for submodel split and merge
 submodel_size: 80                                                   # Average number of images per submodel
 submodel_overlap: 30.0                                              # Radius of the overlapping region between submodels
 submodels_relpath: "submodels"                                      # Relative path to the submodels directory
 submodel_relpath_template: "submodels/submodel_%04d"                # Template to generate the relative path to a submodel directory
 submodel_images_relpath_template: "submodels/submodel_%04d/images"  # Template to generate the relative path to a submodel images directory
 submodel_use_symlinks: yes                                          # Symlink global features and matches to be reused on each submodel

These from opensfm/config.py

Thanks again.

**Comment by paulinus** [comment]
@AaronQi0731 we have just added documentation for the split and merge pipeline here http://opensfm.readthedocs.io/en/latest/large.html
It should answer your questions.
Please note that this an optional feature that should only be needed for reconstructions of large areas. It is also new so expect some level of instability.

**Comment by AaronQi0731** [comment]
Dear pau.
thanks your answer. There is an new question about library of environment. The OpenSfM is able to running in the newest version of SuitSpare? cause the version of this library of my computer is 4.5.5, and the newest version of SuitSpare is 5.1.0. So if update it, that will cause any problem of the OpenSfM? Many Thx.

**Comment by paulinus** [comment]
I don't know if Ceres supports SuiteSparse version 5 already. [In the doc](http://ceres-solver.org/installation.html#linux), they still recommend version 4 but it could be that it works.

**Comment by AaronQi0731** [comment]
I already update the SuiteSparse to 5.1.0. It is work and the result is very good. thank you pau
