### ISSUE TITLE
Error during 'match_candidates_from_meta data

### ISSUE THREAD

**Issue by theriny** [mapillary/OpenSfM#256]
The `report` object tries to use the `d`, `t`, and `o` objects which are not set to anything in one case.

To fix, after line 100 (`pairs = combinations(images, 2)`), add the following:

```python
d = set()
t = set()
o = set()
```

Here is a partial of the data set that gave the error.

[mtndew - Copy (2).zip](https://github.com/mapillary/OpenSfM/files/1580758/mtndew.-.Copy.2.zip)

**Comment by paulinus** [comment]
Fixed in current master. Thanks for reporting, @theriny!
