### ISSUE TITLE
how to localize the traffic sign by using the opensfm?

### ISSUE THREAD

**Issue by xierunhua** [mapillary/OpenSfM#261]
Hi,
I think it's amazing in mapillary, is that I upload the pictures, and mapillary recognize the traffic sign, I wonder how to do it? sfm can reconstruct the 3D point, and how can we recognize the object( like traffic sign), and get the object's location(L, B)?

**Comment by paulinus** [comment]
Hi @MagyAndy, OpenSfM is a Structure from Motion library that finds the camera positions and reconstructs point cloud representations of the scene. It does not do any object detection or recognition. You will need another tool for that.

**Comment by MagyAndy** [comment]
thank you for your answer. it seems a long way to walk.
