### ISSUE TITLE
AttributeError: 'SphericalCamera' object has no attribute 'focal'

### ISSUE THREAD

**Issue by ggliu-ggliu** [mapillary/OpenSfM#265]
HI ,
I tried 3D modeling based the spherical 360 images dataset downloaded from the following link.
[https://www.dropbox.com/sh/3vabbmrhqqbagp5/AABi14O2tWMbxAX91jaaQY77a?dl=0](url)
I encounter some errors and I list them and respectively commands as followed.
Command 1:
>$ bin/opensfm export_visualsfm data/kungsgatanparken

Error 1:
`Traceback (most recent call last):
File "bin/opensfm", line 34, in <module>
command.run(args)
File "/Users/liuluguang/OpenSfM/opensfm/commands/export_visualsfm.py", line 23, in run
self.export(reconstructions[0], graph, data)
File "/Users/liuluguang/OpenSfM/opensfm/commands/export_visualsfm.py", line 32, in export
shot.camera.focal * max(shot.camera.width, shot.camera.height),
AttributeError: 'SphericalCamera' object has no attribute 'focal'`

Command 2:

> $ bin/export_pmvs data/kungsgatanparken 

Error 2:
`Converting dataset [data/kungsgatanparken] to PMVS dir [data/kungsgatanparken/pmvs]
Reconstruction 0
Image: 05.jpg 00000000
Traceback (most recent call last):
File "bin/export_pmvs", line 84, in <module>
K = camera.get_K_in_pixel_coordinates(original_w, original_h)
AttributeError: 'SphericalCamera' object has no attribute 'get_K_in_pixel_coordinates'`

Command 3:

> $ bin/export_bundler data/kungsgatanparken

Error 3:
`Traceback (most recent call last):
File "bin/export_bundler", line 40, in <module>
io.export_bundler(data.images(), reconstructions, track_graph, bundle_file_path, list_file_path)
File "/Users/liuluguang/OpenSfM/opensfm/io.py", line 496, in export_bundler
focal = camera.focal * scale
AttributeError: 'SphericalCamera' object has no attribute 'focal'`

Would please kindly explain to why I encounter these errors and if there is any solution available?

**Comment by paulinus** [comment]
Hi @ggliu-ggliu, exporting does not work for 360 cameras because the formats into which it exports do not support 360 cameras.

What would you like to do with the exported files?

**Comment by ggliu-ggliu** [comment]
@paulinus Thank you for your reply. I intend to use the exported data to build an indoor model.Do you have any other solutions?

**Comment by paulinus** [comment]
I've added the `--undistorted` option to those exporters so that instead of exporting the initial reconstruction, which may contain 360 images, they export the `undistorted_reconstruction.json` which has only perspective images. Spherical images are transformed to 6 perspective images in the undistorted reconstruction.

With this change, you will be able to export to those formats.

I would also look at exporting to [openMVS](https://github.com/cdcseacave/openMVS) using `bin/opensfm export_openmvs dataset`. Then, you can use openMVS to build a dense mesh.

**Comment by ggliu-ggliu** [comment]
thank you @paulinus .
