### ISSUE TITLE
export_gecoocords command producing unexpected output

### ISSUE THREAD

**Issue by angussmitchell** [mapillary/OpenSfM#267]
Running the export_geocoords command on the lund (or any) dataset with the reconstruction flag - i.e.

`bin/opensfm export_geocoords data/lund/ --proj "+proj=merc +ellps=WGS84 +datum=WGS84" --reconstruction`

Produces unexpected output in the reconstruction.geocoords.json - i.e. 

> "016.jpg": {
                "orientation": 1, 
                "camera": "v2 unknown unknown 1024 768 perspective 0.9722", 
                "gps_position": [
                    5.863564368645349, 
                    -27.43093781641437, 
                    1.9999383324757218
                ], 
                "gps_dop": 5.0, 
                "rotation": [
                    1.5096153179337133, 
                    0.22653784504363125, 
                    -0.2464005033281606
                ], 
                "translation": [
                    -2051459.7445896205, 
                    -175206.9959466306, 
                    -3770937.7235005521
                ], 
                "capture_time": 0.0
            }, 
            "017.jpg": {
                "orientation": 1, 
                "camera": "v2 unknown unknown 1024 768 perspective 0.9722", 
                "gps_position": [
                    9.007399068638371, 
                    -11.039743714525684, 
                    1.9999841023236513
                ], 
                "gps_dop": 5.0, 
                "rotation": [
                    1.4693785921110423, 
                    0.2269363875237741, 
                    -0.2801665058144418
                ], 
                "translation": [
                    -2143181.9890748425, 
                    -293506.54960965388, 
                    -3712125.1767064296
                ], 
                "capture_time": 0.0

From reading the source, it looks like the translation field should contain the shot's position in GPS (WGS84, as I've defined in the proj.4 string). As you can see above, the values seem wrong (way too big). 

Does anyone what what the issue is here? Is the export_geocoords command not yet working, am I entering the proj.4 string wrong or am I looking at the wrong output? 

Any help would be greatly appreciated!

**Comment by paulinus** [comment]
The numbers do look too big. Not sure what the problem is yet but wanted to comment some things.

1- Reconstructions should be exported only to metric coordinates. Exporting reconstructions to WGS84 angular coordinates will not work since those are not metric.

2- I'm interested in knowing use cases for exporting the `reconstruction.json` file to geospatial coordinates systems.

3- The camera translation is not the position of the camera. It is the translation from world coordinates to camera coordinates (some comments on this [here](http://opensfm.readthedocs.io/en/latest/cam_coord_system.html#where-is-the-camera)). It has the same magnitude though, so the numbers still look too large.

**Comment by angussmitchell** [comment]
Thanks @paulinus, your comments are enlightening as always. 

1- I'll make sure I use UTM or something else metric in the future. I'm sure the values are just too large because the proj4 string is wrong- I'll validate this soon. 

2- transforming the reconstruction.json  to a geospatial coordinate system is useful for geotagging images (knowing where a particular shot is). It's nice to get the whole reconstruction in this format, rather than just getting the transformation matrix, and having to transform individual shots or points furthur down the line. 

3-I was assuming that after export_geocoords is applied, the world coordinate system would align with the nominated metric proj4 coordinate system (which I see now is not true). If we need to find the camera's position then, does rotation need to be applied before translation to get the final position of the camera? If we want to find the position of the camera can we use `pose.get_origin()` ?

Thanks again for your insight

**Comment by paulinus** [comment]
I think that for the use case "get the new coordinates of the images after SfM" we should have another option on the `export_geocoords` script. That option should just print a CSV with that info.

That would be simpler than exporting `reconstruction.json` which also contains the points and assumes coords are metric. Also manipulating the UTM coords to convert between camera translation and camera origin becomes numerically unstable with large UTM coords. So better to get the origins in UTM directly from the script.

We have an old script to do something similar `https://github.com/mapillary/OpenSfM/blob/master/bin/update_geotag` but it writes the result in the exif of the image. I think writing the result as a CSV should be more usable.

**Comment by paulinus** [comment]
I've added a `--image-positions` options to export the image positions directly to CSV file.

**Comment by angussmitchell** [comment]
Thanks @paulinus, that's very useful (to be able to output a csv file). Also thanks for the info on the old exif script. 

p.s. there is a spelling mistake in the output of the csv, it outputs as "image_geocoords.tsv"

Thanks again!
