### ISSUE TITLE
Ubuntu 16.04 installation error

### ISSUE THREAD

**Issue by KhaledGabr** [mapillary/OpenSfM#269]
Hi all,
Thanks for creating this project, it looks really interesting.

I just had problems with installing it, After running the setup.py build command, I get this error

```
CMake Error at CMakeLists.txt:46 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Did anyone face a similar issue ? 

Thanks in advance.

**Comment by paulinus** [comment]
Hi @KhaledGabr, it looks like you do not have OpenCV installed. You should follow the instructions [here](https://github.com/mapillary/OpenSfM#installing-dependencies-on-ubuntu) to install the requirements before building opensfm.

**Comment by KhaledGabr** [comment]
Thank you so much @paulinus . Docker is unbelievably wonderful.

I couldn't figure out how to install it manually due to some weird dependency errors. But Docker did the job in seconds.

**Comment by YangJae96** [comment]
Thank you so much. I had a same problem right now...
