### ISSUE TITLE
Display error: website continuously loading without displaying image

### ISSUE THREAD

**Issue by Jekyll1021** [mapillary/OpenSfM#271]
[reconstruction.meshed.json.zip](https://github.com/mapillary/OpenSfM/files/1650345/reconstruction.meshed.json.zip)
I've been trying to visualize the points extracted using this json file. However when I browse `http://localhost:8000/viewer/reconstruction.html#file=/data/DATASET_NAME/reconstruction.meshed.json` it just loads but not displaying anything after waiting for a few hours. I wonder:

1. is this problem in viewer potentially caused by an unsuccessful build(Numpy Import Error)? If so/not what exactly is the problem?
2. does this json file contain information that we expected to see?
3. any chance there is a documentation for the meaning/datatype of the features listed in this json file?

**Comment by Jekyll1021** [comment]
Is there any way to visualize the sparse point cloud in reconstruction.meshed.json without using the website?

**Comment by paulinus** [comment]
In case you didn't, you need to replace `DATASET_NAME` by `berlin` in the url.
Otherwise, you can also export the sparse reconstruction to a PLY file and open in meshlab, for example.
To export, use `bin/opensfm export_ply DATASET_PATH`. This will create the `reconstruction.ply` file.

**Comment by Jekyll1021** [comment]
Warning: Warning: There are gl errors: invalid framebuffer operation
There are gl errors: invalid framebuffer operation
Opened mesh /Users/Xenon/reconstruction.ply in 35 msec
All files opened in 79 msec

I got this when trying to open the reconstructed ply file with meshlab. Could you provide any hint on what could be the problem?

**Comment by Jekyll1021** [comment]
Sorry for the last followup. That one is just a warning message specific for all OSX system. Now it's working fine. Thank you!
