### ISSUE TITLE
segfault when running detect_features (ubuntu, 14.04 x64)

### ISSUE THREAD

**Issue by lolz0r** [mapillary/OpenSfM#28]
Hi all,
I cloned from the mainline brnach and I was able to get the project to compile successfully! 

Unfortunately when I run:
`bin/run_all data/berlin`

I get the following output:
`~/projects/OpenSfM$ bin/run_all data/berlin
Extracting focal lengths for image 01.jpg
Extracting focal lengths for image 03.jpg
Extracting focal lengths for image 02.jpg
Extracting SIFT features for image 01.jpg
bin/run_all: line 7:   419 Segmentation fault      (core dumped) $DIR/detect_features $1`

Thank you for any help you may have.

**Comment by paulinus** [comment]
Can you check what version of OpenCV do you have installed?

**Comment by lolz0r** [comment]
I have 2.4.8 installed:
  dpkg -l | grep libopencv
ii  libopencv-calib3d-dev:amd64                           2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-calib3d
ii  libopencv-calib3d2.4:amd64                            2.4.8+dfsg1-2ubuntu1                                amd64        computer vision Camera Calibration library
ii  libopencv-contrib-dev:amd64                           2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-contrib
ii  libopencv-contrib2.4:amd64                            2.4.8+dfsg1-2ubuntu1                                amd64        computer vision contrib library
ii  libopencv-core-dev:amd64                              2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-core
ii  libopencv-core2.4:amd64                               2.4.8+dfsg1-2ubuntu1                                amd64        computer vision core library
ii  libopencv-dev                                         2.4.8+dfsg1-2ubuntu1                                amd64        development files for opencv
ii  libopencv-features2d-dev:amd64                        2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-features2d
ii  libopencv-features2d2.4:amd64                         2.4.8+dfsg1-2ubuntu1                                amd64        computer vision Feature Detection and Descriptor Extraction library
ii  libopencv-flann-dev:amd64                             2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-flann
ii  libopencv-flann2.4:amd64                              2.4.8+dfsg1-2ubuntu1                                amd64        computer vision Clustering and Search in Multi-Dimensional spaces library
ii  libopencv-gpu-dev:amd64                               2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-gpu2.4
ii  libopencv-gpu2.4:amd64                                2.4.8+dfsg1-2ubuntu1                                amd64        computer vision GPU library
ii  libopencv-highgui-dev:amd64                           2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-highgui
ii  libopencv-highgui2.4:amd64                            2.4.8+dfsg1-2ubuntu1                                amd64        computer vision High-level GUI and Media I/O library
ii  libopencv-imgproc-dev:amd64                           2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-imgproc
ii  libopencv-imgproc2.4:amd64                            2.4.8+dfsg1-2ubuntu1                                amd64        computer vision Image Processing library
ii  libopencv-legacy-dev:amd64                            2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-legacy
ii  libopencv-legacy2.4:amd64                             2.4.8+dfsg1-2ubuntu1                                amd64        computer vision legacy library
ii  libopencv-ml-dev:amd64                                2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-ml
ii  libopencv-ml2.4:amd64                                 2.4.8+dfsg1-2ubuntu1                                amd64        computer vision Machine Learning library
ii  libopencv-objdetect-dev:amd64                         2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-objdetect
ii  libopencv-objdetect2.4:amd64                          2.4.8+dfsg1-2ubuntu1                                amd64        computer vision Object Detection library
ii  libopencv-ocl-dev:amd64                               2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-ocl2.4
ii  libopencv-ocl2.4:amd64                                2.4.8+dfsg1-2ubuntu1                                amd64        computer vision OpenCL support library
ii  libopencv-photo-dev:amd64                             2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-photo2.4
ii  libopencv-photo2.4:amd64                              2.4.8+dfsg1-2ubuntu1                                amd64        computer vision computational photography library
ii  libopencv-stitching-dev:amd64                         2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-stitching2.4
ii  libopencv-stitching2.4:amd64                          2.4.8+dfsg1-2ubuntu1                                amd64        computer vision image stitching library
ii  libopencv-superres-dev:amd64                          2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-superres2.4
ii  libopencv-superres2.4:amd64                           2.4.8+dfsg1-2ubuntu1                                amd64        computer vision Super Resolution library
ii  libopencv-ts-dev:amd64                                2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-ts2.4
ii  libopencv-ts2.4:amd64                                 2.4.8+dfsg1-2ubuntu1                                amd64        computer vision ts library
ii  libopencv-video-dev:amd64                             2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-video
ii  libopencv-video2.4:amd64                              2.4.8+dfsg1-2ubuntu1                                amd64        computer vision Video analysis library
ii  libopencv-videostab-dev:amd64                         2.4.8+dfsg1-2ubuntu1                                amd64        development files for libopencv-videostab2.4
ii  libopencv-videostab2.4:amd64                          2.4.8+dfsg1-2ubuntu1                                amd64        computer vision video stabilization library
ii  libopencv2.4-java                                     2.4.8+dfsg1-2ubuntu1                                all          Java bindings for the computer vision library
ii  libopencv2.4-jni                                      2.4.8+dfsg1-2ubuntu1                                amd64        Java jni library for the computer vision library

**Comment by paulinus** [comment]
Finally got to try the install on a fresh ubuntu 14.04. The problem you encountered is that OpenCV package provided by Ubuntu [does not include SIFT](http://stackoverflow.com/questions/18561910/opencv-python-cant-use-surf-sift).
You can either install OpenCV by downloading and building from source, or just use another feature type.  I'm going to set HAHOG as default.
