### ISSUE TITLE
Unable to build partial reconstructions

### ISSUE THREAD

**Issue by theriny** [mapillary/OpenSfM#281]
I get the following error when I run 'bin/opensfm_run_all data/mydata'

`2018-02-02 21:10:30,677 DEBUG: frames10.jpg - frames8.jpg has 7 candidate matches
2018-02-02 21:10:31,048 DEBUG: frames10.jpg - frames9.jpg has 8 candidate matches
libdc1394 error: Failed to initialize libdc1394
2018-02-02 21:10:31,618 INFO: reading features
2018-02-02 21:10:31,842 DEBUG: Merging features onto tracks
2018-02-02 21:10:31,863 DEBUG: Good tracks: 4846
libdc1394 error: Failed to initialize libdc1394
2018-02-02 21:10:32,225 INFO: Starting incremental reconstruction
libdc1394 error: Failed to initialize libdc1394
libdc1394 error: Failed to initialize libdc1394
libdc1394 error: Failed to initialize libdc1394
libdc1394 error: Failed to initialize libdc1394
libdc1394 error: Failed to initialize libdc1394
2018-02-02 21:10:33,488 INFO: 0 partial reconstructions in total.
libdc1394 error: Failed to initialize libdc1394
Traceback (most recent call last):
  File "/source/OpenSfM/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/source/OpenSfM/opensfm/commands/mesh.py", line 22, in run
    reconstructions = data.load_reconstruction()
  File "/source/OpenSfM/opensfm/dataset.py", line 368, in load_reconstruction
    with open(self.__reconstruction_file(filename)) as fin:
IOError: [Errno 2] No such file or directory: 'data/reconstruction.json'`

Even though I get Good tracks, still receiving error. Here is my data set.
![frames0](https://user-images.githubusercontent.com/17436806/35755167-daa133f6-082b-11e8-8269-407e882f879a.jpg)
![frames1](https://user-images.githubusercontent.com/17436806/35755168-dab221f2-082b-11e8-854b-480922ccc1b0.jpg)
![frames2](https://user-images.githubusercontent.com/17436806/35755170-dac20090-082b-11e8-9d53-5b8b9efa966e.jpg)
![frames3](https://user-images.githubusercontent.com/17436806/35755171-dacfa880-082b-11e8-9b6c-497124c6de2e.jpg)
![frames4](https://user-images.githubusercontent.com/17436806/35755173-dadc308c-082b-11e8-9877-6f470061e6e1.jpg)
![frames5](https://user-images.githubusercontent.com/17436806/35755174-daefd90c-082b-11e8-9e93-6999db9b977a.jpg)
![frames6](https://user-images.githubusercontent.com/17436806/35755175-dafc0920-082b-11e8-974e-fc75aaed1364.jpg)
![frames7](https://user-images.githubusercontent.com/17436806/35755176-db0b25d6-082b-11e8-9c6c-a22edc4983ad.jpg)
![frames8](https://user-images.githubusercontent.com/17436806/35755177-db1b1ed2-082b-11e8-9bd3-46eae1cc17f0.jpg)
![frames9](https://user-images.githubusercontent.com/17436806/35755178-db2905d8-082b-11e8-9d8a-55efc7ba4130.jpg)
![frames10](https://user-images.githubusercontent.com/17436806/35755179-db35fe28-082b-11e8-92d7-a00a7ef6f270.jpg)
![frames11](https://user-images.githubusercontent.com/17436806/35755180-db4762e4-082b-11e8-9344-35529b6c780c.jpg)
![frames12](https://user-images.githubusercontent.com/17436806/35755181-db55cadc-082b-11e8-9bcc-c18c32feaf49.jpg)
![frames13](https://user-images.githubusercontent.com/17436806/35755182-db659f52-082b-11e8-88ce-19d7397cb28b.jpg)

PS: Already tried items from here: https://github.com/mapillary/OpenSfM/issues/76

Still same errors.

**Comment by paulinus** [comment]
Hi @theriny, I gave a try to the dataset. There are too few images get a reconstruction. If you are taking images all around the object, you should take at least 30. This help the algorithm to find correspondences between the images.

**Comment by YanNoun** [comment]
No answer for a while, closing.
