### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by mabrowning** [mapillary/OpenSfM#283]
I'm looking to package OpenSfM for homebrew ([working formula here](https://github.com/mabrowning/homebrew-core/tree/opensfm)). They (understandably) prefer to package releases rather than HEAD. Any idea when the next release will be? 

When it is released, could the OpenGV package be versioned/tagged/released as well?

**Comment by mabrowning** [comment]
While the homebrew folks *may* accept a formula with a "resource" (secondary download) of OpenGV pointing to an arbitrary git commit, they are much more likely to accept it referring to a tag or published release of OpenGV, even if it is named `opensfm-v0.2.0` or similar.

Thanks!

**Comment by paulinus** [comment]
@mabrowning, I've made a new release of OpenSfM 
 https://github.com/mapillary/OpenSfM/releases/tag/v0.2.0
As you suggested, I've also created a release for opengv on my fork 
 https://github.com/paulinus/opengv/releases/tag/opensfm-v0.2.0

I hope this helps you in building the formula.

**Comment by YanNoun** [comment]
@mabrowning current released version is https://github.com/mapillary/OpenSfM/releases/tag/v0.5.1. A new one shall arrive soon.
