### ISSUE TITLE
Fixing one camera to real value

### ISSUE THREAD

**Issue by jololhuet** [mapillary/OpenSfM#289]
Hey, I was wondering if it was possible to fix one of the cameras rotation / translation and start the reconstruction from that. That is infer all others cameras matrices and re-compute the 3d points positions.

**Comment by paulinus** [comment]
It would be possible but would require modifying the code. If you only want to fix one camera, a simpler solution would be to run the reconstruction normally, then rotate and translate the reconstruction so that that camera is at the position you want it to be.

**Comment by YanNoun** [comment]
It is a duplicate  of https://github.com/mapillary/OpenSfM/issues/129 and https://github.com/mapillary/OpenSfM/issues/180, so I'm closing.
