### ISSUE TITLE
errors running "python setup.py build" on OSX

### ISSUE THREAD

**Issue by michaelgli** [mapillary/OpenSfM#29]
I got errors at the end for csfm. Here is the full log:
My OSX is Darwin guangs-Mac-mini.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

Any ideas?
Thanks. -michael

guangs-Mac-mini:openSFM guangli$ python setup.py build
Configuring...
-- The C compiler identification is AppleClang 6.1.0.6020049
-- The CXX compiler identification is AppleClang 6.1.0.6020049
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- A library with BLAS API found.
-- Found AMD library: /usr/local/lib/libamd.a
-- Found AMD header in: /usr/local/include
-- Found CAMD library: /usr/local/lib/libcamd.a
-- Found CAMD header in: /usr/local/include
-- Found COLAMD library: /usr/local/lib/libcolamd.a
-- Found COLAMD header in: /usr/local/include
-- Found CCOLAMD library: /usr/local/lib/libccolamd.a
-- Found CCOLAMD header in: /usr/local/include
-- Found CHOLMOD library: /usr/local/lib/libcholmod.a
-- Found CHOLMOD header in: /usr/local/include
-- Found SuiteSparseQR library: /usr/local/lib/libspqr.a
-- Found SuiteSparseQR header in: /usr/local/include
-- Found Intel Thread Building Blocks (TBB) library: /usr/local/lib/libtbb.dylib, assuming SuiteSparseQR was compiled with TBB.
-- Found Intel Thread Building Blocks (TBB) Malloc library: /usr/local/lib/libtbbmalloc.dylib
-- Found SuiteSparse_config library: /usr/local/lib/libsuitesparseconfig.a
-- Found SuiteSparse_config header in: /usr/local/include
-- Did not find METIS library (optional SuiteSparse dependency)
-- Found SuiteSparse: TRUE (found version "4.2.1") 
-- Found Eigen: /usr/local/include/eigen3 (found version "3.2.4") 
-- Found ceres: /usr/local/lib/libceres.dylib  
-- Found Gflags: /usr/local/include  
-- Found Glog: /usr/local/include  
-- Could NOT find Boost
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.6") 
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.6") 
-- Found NumPy: version "1.9.2" /usr/local/lib/python2.7/site-packages/numpy/core/include
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   csfm

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/guangli/openSFM/cmake_build
Compiling extension...
Scanning dependencies of target mv
Scanning dependencies of target akaze
Scanning dependencies of target vl
[  2%] [  4%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/AKAZE.cpp.o
Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/fed.cpp.o
[  6%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/aib.c.o
[  8%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/array.c.o
[ 10%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/nldiffusion_functions.cpp.o
[ 12%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/covdet.c.o
[ 14%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/multiview/fundamental.cc.o
[ 16%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/dsift.c.o
/Users/guangli/openSFM/opensfm/src/third_party/vlfeat/vl/dsift.c:265:26: warning: using floating point absolute value function 'fabsf' when
      argument is of integer type [-Wabsolute-value]
    *kerIter++ = (1.0F - fabsf(x) / binSize) *
                         ^
/Users/guangli/openSFM/opensfm/src/third_party/vlfeat/vl/dsift.c:265:26: note: use function 'abs' instead
    *kerIter++ = (1.0F - fabsf(x) / binSize) *
                         ^~~~~
                         abs
1 warning generated.
[ 18%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/fisher.c.o
[ 20%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/generic.c.o
[ 22%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/getopt_long.c.o
[ 24%] [ 26%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/multiview/projection.cc.o
Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/gmm.c.o
[ 28%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/hikmeans.c.o
[ 30%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/hog.c.o
[ 32%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/homkermap.c.o
[ 34%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/host.c.o
[ 36%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/utils.cpp.o
[ 38%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/ikmeans.c.o
[ 40%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/imopv.c.o
[ 42%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/imopv_sse2.c.o
[ 44%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/kdtree.c.o
[ 46%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/kmeans.c.o
Linking CXX static library libakaze.a
[ 46%] Built target akaze
[ 48%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/multiview/five_point.cc.o
[ 50%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/lbp.c.o
[ 52%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/liop.c.o
[ 54%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mathop.c.o
[ 56%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mathop_avx.c.o
[ 58%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/multiview/robust_five_point.cc.o
[ 60%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mathop_sse2.c.o
[ 62%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mser.c.o
[ 64%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/pgm.c.o
/Users/guangli/openSFM/opensfm/src/third_party/vlfeat/vl/pgm.c:236:18: warning: comparison of constant 65536 with boolean expression is
      always false [-Wtautological-constant-out-of-range-compare]
  if(! max_value >= 65536) {
     ~~~~~~~~~~~ ^  ~~~~~
1 warning generated.
[ 66%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/quickshift.c.o
[ 68%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/random.c.o
[ 70%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/rodrigues.c.o
[ 72%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/scalespace.c.o
[ 74%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/sift.c.o
[ 76%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/slic.c.o
[ 78%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/stringop.c.o
[ 80%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/svm.c.o
[ 82%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/svmdataset.c.o
[ 84%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/vlad.c.o
[ 86%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/multiview/triangulation.cc.o
Linking C static library libvl.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvl.a(mathop_avx.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvl.a(mathop_avx.c.o) has no symbols
[ 86%] Built target vl
[ 88%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/multiview/conditioning.cc.o
[ 90%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/multiview/panography.cc.o
[ 92%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/multiview/panography_kernel.cc.o
[ 94%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/multiview/robust_panography.cc.o
[ 96%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/numeric/numeric.cc.o
[ 98%] Building CXX object CMakeFiles/mv.dir/third_party/libmv/numeric/poly.cc.o
Linking CXX static library libmv.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmv.a(poly.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmv.a(poly.cc.o) has no symbols
[ 98%] Built target mv
Scanning dependencies of target csfm
make[2]: *** No rule to make target `/libboost_python.a', needed by `/Users/guangli/openSFM/opensfm/csfm.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[100%] Building CXX object CMakeFiles/csfm.dir/csfm.cc.o
make[1]: *** [CMakeFiles/csfm.dir/all] Error 2
make: *** [all] Error 2
Building package
running build
running build_py

**Comment by paulinus** [comment]
Cmake is not finding boost-python. Can you check if it's installed?

**Comment by michaelgli** [comment]
You're right, after I run "brew install boost-python", it's compiling.
Thanks a lot!
-michael

**Comment by paulinus** [comment]
no problem. I've set the dependency as required now, so you get a better error from cmake.
