### ISSUE TITLE
Multiple saving of reconstructions

### ISSUE THREAD

**Issue by vagran** [mapillary/OpenSfM#290]
Check this place in code:
https://github.com/mapillary/OpenSfM/blob/1c7dd29cbc7eace93d38dc26befb51233892bade/opensfm/reconstruction.py#L1105
It looks suspicious that all reconstructions are saved after each new reconstruction is solved. Actually it just rewrites the reconstruction file multiple times. Probably this sorting and saving should be indented left to be out of reconstruction loop. This doesn't have any visible problems, just found confusing place during the code research. So it either should be fixed or some comment added (explaining the reason for such behavior) to avoid confusion.

**Comment by paulinus** [comment]
The reconstructions are saved after each iteration merely so that you can look at them while the rest is being computed. It could be done outside the loop but the cost of it is minimal and is helpful when waiting for large reconstructions to finish. Thanks for looking at it.
