### ISSUE TITLE
Incorrect units in description

### ISSUE THREAD

**Issue by vagran** [mapillary/OpenSfM#291]
The following parameter:
https://github.com/mapillary/OpenSfM/blob/1c7dd29cbc7eace93d38dc26befb51233892bade/opensfm/config.py#L65
probably is incorrectly described. According to code, it is not in pixels but in radians.
"triangulation_threshold" is in radians as well. I am not sure about "five_point_algo_threshold", it is definitely not pixels as described but might be part of image width.

**Comment by mlopezantequera** [comment]
Related to: #286

**Comment by paulinus** [comment]
@vagran you are right the threshold is in radians. The comments were outdated and I've just updated them. Thanks for pointing it out.
