### ISSUE TITLE
Aligning reconstruction with ground plane

### ISSUE THREAD

**Issue by angussmitchell** [mapillary/OpenSfM#292]
I've recently been testing OpenSfM using my own perspective and 360 equirectangular image datasets. My input imagery is not geotagged, and I do not provide ground control points. The datasets are large and linear, therefore I use frequent local bundle adjustment and infrequent global bundle adjustment. All other setting are default. 

I've found that the reconstructions created using perspective imagery are aligned nicely with the ground plane, with the reconstruction lying on the xy plane, and the 'up' direction in the z axis. I've found however, that my 360 reconstructions are aligned in a seemingly arbitrary orientation (not on the xy plane, with 'up' not in the z axis).  

I'm wondering if some ground plane alignment is implemented in the perspective imagery, but not in the 360 imagery? If so, how would you suggest one achieve proper orientation of the 360 reconstructions? 

Thanks for your time

**Comment by GeoEngTechEL** [comment]
I have a trial with 360 Imagery, fellows of mapillary: https://widestreet-ai.weebly.com/

**Comment by floscher** [comment]
> I have a trial with 360 Imagery, fellows of mapillary: https://widestreet-ai.weebly.com/

@GeoEngTechEL What is this WideStreet AI? You invited me to join the repository, but it is just a simple fork of WebODM by OpenDroneMap without any changes by you!
Except from buzzwords I don't see much on that website that describes what your product does. When charging people 300 £, I'd expect something with more substance to it and that does not look like taking an open source project and putting a price tag and some fancy marketing speak onto it.

cc @pierotofy @DenisCarriere @kgonzago @mapillary

**Comment by angussmitchell** [comment]
The issue was that un-geotagged imagery doesn't seem to go through ground plane estimation. This seems fair enough really seeing as there aren't any coordinates provided, and therefore no way to know.
