### ISSUE TITLE
reconstruction not using much cpu?

### ISSUE THREAD

**Issue by fredlllll** [mapillary/OpenSfM#294]
im looking into how i can speed up processing and i noticed that reconstruction is using multiple processes, but they only use 3-5% of a cpu

https://i.imgur.com/cX2fPWj.png

this is a 32 core machine on aws, so not that cheap that i want it to run singlethreaded stuff if it isnt necessary. what are these processes waiting for?

**Comment by paulinus** [comment]
During the `reconstruct` we mainly use only 1 processor since the reconstruction algorithm is incremental. We do use multiple processes at the beginning when searching for good image pairs to bootstrap the reconstruction. It could be that loky kept those processes alive after they are no longer needed.

**Comment by paulinus** [comment]
They do not stay alive when I test on my machine.

**Comment by fredlllll** [comment]
the processes were only there for a short time, but had constantly low cpu usage during that time. was just wondering why

**Comment by fredlllll** [comment]
ok i got a new issue with reconstruction. you said its only using 1 processor.. https://i.imgur.com/tiYRMKL.png but what is this?

a ton of cpu is used by many threads, but most of the time is spent in kernel mode. so i guess a lot of synchronization is done?

**Comment by juvinski** [comment]
Hi,
I was doing some tests comparing 2 machines - one with 2 cpus and other with 16 cpus.
This is a collect of context switching from both machines
2 CPUS
08:54:41 PM 1.00 415.00
08:54:42 PM 0.00 425.00
08:54:43 PM 0.00 379.00
08:54:44 PM 0.00 384.00
08:54:45 PM 7.00 1411.00


16 CPUS
08:54:46 PM 0.00 47305.00
08:54:47 PM 0.00 101913.00
08:54:48 PM 0.00 90899.00
08:54:49 PM 0.00 76952.00
08:54:50 PM 0.00 480.00
08:54:51 PM 0.00 74289.00
08:54:52 PM 0.00 91450.00
08:54:53 PM 0.00 90964.00
08:54:54 PM 0.00 43103.00
08:54:55 PM 0.00 1841.00
Average: 0.00 61919.60

**Comment by fredlllll** [comment]
^ this is maybe a bit out of context. this is apparently happening during the reconstruction step and would explain the heavy kernel mode usage i see in my screenshot. now the question is what the hell is opensfm doing there?

**Comment by juvinski** [comment]
Another detail @fredlllll running for instance textrecon, the context switching is pretty low - around 150 per second and textrecon is running faster than the 2 processors machine.

**Comment by YanNoun** [comment]
@fredlllll the screenshot you posted seems to show an issue with OpenDroneMap. OpenSfM also switched from multiprocessing to multithreading, which is solving many multiprocess + RAM consumption issues.
