### ISSUE TITLE
[Improvement] Handle EXIF DOP zero values

### ISSUE THREAD

**Issue by pierotofy** [mapillary/OpenSfM#298]
When a camera vendor incorrectly sets the GPS DOP exif tag of an image to zero, OpenSfM currently throws a division by zero error.

Details here: http://community.opendronemap.org/t/float-divison-by-zero-error/317/4

While a solution is to remove the offending exif tag, adding the necessary logic to handle zero values on DOP tags could make OpenSfM more robust.

**Comment by paulinus** [comment]
Thanks for the warning. It is fixed in current master, https://github.com/mapillary/OpenSfM/commit/e6c260467ddf6f66f4f97a42acd5685b2ae05f71

This was happening when averaging the lat, lons to chose a reference. We added a check for that case.
