### ISSUE TITLE
Am I getting the right result

### ISSUE THREAD

**Issue by michaelgli** [mapillary/OpenSfM#30]
I run the data/berlin example. Am I getting the correct result?
![screen shot 2015-05-16 at 3 31 32 pm](https://cloud.githubusercontent.com/assets/12475528/7667865/8002ea56-fbe1-11e4-9d09-bb5f3406d73d.png)

Thanks,
-michael

**Comment by paulinus** [comment]
Yes, you get a sparse set of points on the facade. Things you can do from there:
- Use datasets with more images
- Click twice on an image to see it. Then use arrows to move between images.
- Run bin/mesh data/berlin to build a reconstruction with sparse mesh that will produce smoother transitions from images

**Comment by michaelgli** [comment]
OK. I will play with it more with some sample images.
Thanks for the information. 
-michael

**Comment by michaelgli** [comment]
Do you guys have a set of images that will produce some good results? I have tried some of my images, and it couldn't produce the reconstruction. I really want to try some sample images that will produce good results.
Thanks,
-michael

**Comment by paulinus** [comment]
Can you share the images you used? thanks!

**Comment by michaelgli** [comment]
I was trying to use a test set images from here:
http://3dflow.net/zephyr-tutorial/3DF_Zephyr_Tutorial_01_Dataset.zip
It has 64 images, each image is 7M, very big.
openSFM couldn't finish processing. So I stopped it, then I picked the
first 4 pictures. openSFM couldn't reconstruct with 4 pictures.

I also tried the 2 sample pictures from a book:
https://camo.githubusercontent.com/dcf4872f4a4a1e1ddfc729f95631bea459125dcd/68747470733a2f2f7261772e6769746875622e636f6d2f4d6173746572696e674f70656e43562f636f64652f6d61737465722f43686170746572345f53747275637475726546726f6d4d6f74696f6e2f73637265656e73686f742e706e67

openSFM couldn't reconstruct either.

I just want to make sure that I'm using openSFM correctly.


Thanks,
-michael

**Comment by paulinus** [comment]
We've used Christoph Strecha's fountain images for testing in the past. They should work and give you something like 
![image](https://cloud.githubusercontent.com/assets/841954/7682542/0ad1e73e-fd79-11e4-9f9b-69d5f52cba58.png)
If they don't, there's a bug. I'll investigate and come back to you.

**Comment by michaelgli** [comment]
That looks great!

I'm attaching the 2 images I'm using to make sure we're using the same
images.

Thanks for your investigation.

**Comment by paulinus** [comment]
did you forget the attachment?

**Comment by michaelgli** [comment]
Gmail doesn't show attachment very well.

It was attached. Let me attach again.

**Comment by paulinus** [comment]
github is probably not passing the attachments. Send to pau.gargallo at gmail directly, please.

Also, for the first dataset, the problem is the missing focal length information on the images' EXIF. We currently only support images for which we can extract the focal length from the EXIF data.

**Comment by paulinus** [comment]
Closed since we sorted this by mail
