### ISSUE TITLE
extracting trajectory from images?

### ISSUE THREAD

**Issue by fredlllll** [mapillary/OpenSfM#304]
im trying to find a faster way to create orthomosaic maps from drone flight data. apparently map2dfusion is really nice for that, but it requires the trajectory of the images, so position (which i can get from gps) and the orientation as a quaternion. i tried using orb-slam but it doesnt cooperate at all.

so can i extract the trajectory using opensfm? (without doing the costly reconstruction step)

**Comment by paulinus** [comment]
Finding the trajectory is the main task of the reconstruction process, so you can not get it without it.

For fast, real-time trajectory estimation you will need to use a SLAM tool. ORB-SLAM2 is a good one. That is assuming that you are capturing video.

I did not try the map2dfusion but I would assume that it does the reconstruction/SLAM part by itself. Could it be that only an approximate trajectory from the GPS is required as input?

**Comment by fredlllll** [comment]
i tried orb slam but the results are unusable, also its not a video, just random images taken with a drone.

it requires position and orientation. gps does not give me the orientation. and some images are taken horizontally, so i cant just say they all point down and hope for the best =/

**Comment by paulinus** [comment]
ok, SLAM will not work for random images

**Comment by immuhammadadil** [comment]
Is there any way we can extract mosaic generated by Map2DFusion to external file?

**Comment by YanNoun** [comment]
No answer in a while, closing.
