### ISSUE TITLE
link error python setup.py build

### ISSUE THREAD

**Issue by samidh15** [mapillary/OpenSfM#308]
Hello,
I am getting the following error when running setup.py:
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [depthmap_test] Error 1
make[1]: *** [CMakeFiles/depthmap_test.dir/all] Error 2

This did not stop me from running the berlin images, but I get the warning--
/Users/schatter/.virtualenvs/gurus/lib/python2.7/site-packages/loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value
  "increase its maximal value", RuntimeWarning)
2018-04-11 14:09:38,668 DEBUG: Undistorting image 02.jpg
/Users/schatter/.virtualenvs/gurus/lib/python2.7/site-packages/loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value
  "increase its maximal value", RuntimeWarning)
2018-04-11 14:09:39,594 DEBUG: Undistorting image 01.jpg
/Users/schatter/.virtualenvs/gurus/lib/python2.7/site-packages/loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value
  "increase its maximal value", RuntimeWarning)
2018-04-11 14:09:40,639 DEBUG: Undistorting image 03.jpg
2018-04-11 14:09:42,721 INFO: Computing neighbors
/Users/schatter/.virtualenvs/gurus/lib/python2.7/site-packages/loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value
  "increase its maximal value", RuntimeWarning)
2018-04-11 14:09:43,800 INFO: Using precomputed raw depthmap 02.jpg
/Users/schatter/.virtualenvs/gurus/lib/python2.7/site-packages/loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value
  "increase its maximal value", RuntimeWarning)
2018-04-11 14:09:44,602 INFO: Using precomputed raw depthmap 01.jpg
/Users/schatter/.virtualenvs/gurus/lib/python2.7/site-packages/loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value
  "increase its maximal value", RuntimeWarning)
2018-04-11 14:09:45,381 INFO: Using precomputed raw depthmap 03.jpg
/Users/schatter/.virtualenvs/gurus/lib/python2.7/site-packages/loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value
  "increase its maximal value", RuntimeWarning)
2018-04-11 14:09:46,438 INFO: Using precomputed clean depthmap 02.jpg
/Users/schatter/.virtualenvs/gurus/lib/python2.7/site-packages/loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value
  "increase its maximal value", RuntimeWarning)
2018-04-11 14:09:47,211 INFO: Using precomputed clean depthmap 01.jpg
/Users/schatter/.virtualenvs/gurus/lib/python2.7/site-packages/loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value
  "increase its maximal value", RuntimeWarning)
2018-04-11 14:09:48,091 INFO: Using precomputed clean depthmap 03.jpg
/Users/schatter/.virtualenvs/gurus/lib/python2.7/site-packages/loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value
  "increase its maximal value", RuntimeWarning)
2018-04-11 14:09:49,171 INFO: Using precomputed pruned depthmap 02.jpg
/Users/schatter/.virtualenvs/gurus/lib/python2.7/site-packages/loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value
  "increase its maximal value", RuntimeWarning)
2018-04-11 14:09:50,006 INFO: Using precomputed pruned depthmap 01.jpg
/Users/schatter/.virtualenvs/gurus/lib/python2.7/site-packages/loky/backend/semlock.py:217: RuntimeWarning: semaphore are broken on OSX, release might increase its maximal value
  "increase its maximal value", RuntimeWarning)
2018-04-11 14:09:50,849 INFO: Using precomputed pruned depthmap 03.jpg
2018-04-11 14:09:50,960 INFO: Merging depthmaps

Not sure what is wrong. My OS is macOS Sierra. I am using python 2.7.14, and gcc version is 7.3.0.

**Comment by Geo-fortune** [comment]
after compile opencv2, i also generate this problem

**Comment by paulinus** [comment]
Nothing is wrong, no worries. The messages you see are warnings from the external library loky. Loky produces this rather noisy warning on macOS but can be safely ignored.
