### ISSUE TITLE
Mapping from XYZ point cloud to GPS (Lat, Lon, Alt)

### ISSUE THREAD

**Issue by agmarrugo** [mapillary/OpenSfM#313]
We're trying to use OpenSfM as a way to obtain topographic information from a terrain in order to build a Digital Elevation Map. We're using a DJI Phantom 3 Pro Drone. We have obtained metric XYZ (sparse and dense) point clouds which seem accurate enough for our purposes. However, we'd like to register these point clouds to a real-world coordinate system in (lat, lon, alt). 

Using the tools provided in OpenSfM we convert back to (lat, lon, alt) with ``geo.lla_from_topocentric``, however, the GPS reference seems to be always (``0,0,0``).

1. Does the reference change when using Ground Control Points (GCPs)? The images have GPS coordinates embedded in the EXIF information. 

When we convert to ``lla`` we get a point cloud in geocoords which we view, for example on Google Earth, but it seems like all the points are crammed together and do not extend throughout the whole area we shot. Does using GCPs solve this issue? Can we trust the GPS from a Drone?

Here's a screenshot
https://www.dropbox.com/s/rk8fyc4j2bfs1im/MAPA.png?dl=0

**Comment by paulinus** [comment]
When the images have GPS information, the reference should be their average value. If you are getting the reference at `(0, 0, 0)` it means something is not working properly.

Can you send here the contents of `refenence_lla.json` and one of the `.exif` files in the `exif/` folder?

Ground control points will help in aligning the reconstruction better but using only the image GPS tag should work better than what you are getting.

**Comment by agmarrugo** [comment]
These are the contents of `reference_lla.json`

    {
    "latitude": 0.0, 
    "altitude": 0, 
    "longitude": 0.0
    }

And the contents of an `.exif` file

    {
    "width": 4000, 
    "camera": "v2 dji fc300x 4000 3000 perspective 0.5555", 
    "projection_type": "perspective", 
    "orientation": 1, 
    "focal_ratio": 0.5555555555555556, 
    "make": "DJI", 
    "gps": {
        "latitude": 10.365362611111111, 
        "altitude": 72.467, 
        "longitude": -75.46290950000001
    }, 
    "model": "FC300X", 
    "capture_time": 1521889399.0, 
    "height": 3000
    }

**Comment by paulinus** [comment]
It is strange that the reference is at `0,0,0` when the gps data is available. Maybe the reference was generated on a previous run before the data was available.

Can you delete the `reference_lla.json` file and rerun the reconstruction? This will regenerate the file. If the reference is again 0. You've found a bug.

**Comment by agmarrugo** [comment]
Well, it turns out you are right. The reference was indeed generated on a previous failed run.  Running it again, we do indeed get a reference that's different and is similar to the GPS coordinates found in the image files. However, we have the following doubt about the reference. 

We've verified how the reference is computed. The function `invent_reference_lla` found in `OpenSfM/opensfm/dataset.py` creates the `reference_lla.json` which it sets to `(0,0,0)` as default if there are no images or the images do not have GPS information. However, it computes the average lat, lon, and alt, but it only uses the average values for lat and lon, it sets it this way

    reference = {'latitude': lat, 'longitude': lon, 'altitude': 0}  # Set altitude manually. 

Is this done on purpose. If yes, then why bother computing the average alt value? Is this `0` altitude equivalent to sea level altitude?

Another related aspect about the reconstruction parameters is the `use_altitude_tag`. If set to `no` we get reconstruction points with a negative altitude, when set to `yes` we get points with positive altitude. We have noticed that the tag is not used in `invent_reference_lla`, but instead it's used in `reconstruction.py` in line 454

    if data.config['use_altitude_tag']:
            alt = exif['gps'].get('altitude', 2.0)
        else:
            alt = 2.0  # Arbitrary value used to align the reconstruction

So it seems that it does use an altitude value from the exif data, but when we compute from XYZ to GPS using the reference stored in `reference_lla.json` in which the altitude has been set to `0`,then we're somehow making a mistake. Is this correct?

**Comment by paulinus** [comment]
The reference lla can be at any point as long as it is in the vicinity of the images. The altitude is set to 0, which is ok as long as you are not at very high altitudes. It might be a good idea to actually use the average altitude when available instead of 0.

As for the `use_altitude_tag`, in many cases, the altitude tag is often unreliable. Setting this option to `no` simply ignores the tag and sets the altitude to 2 meters. This is done with street level imagery in mind and make no sense for drone datasets.

The altitude tag in drone images tend to be more reliable than on other devices, so it is best to use `use_altitude_tag: yes` for such datasets.

**Comment by YanNoun** [comment]
No answer in a while, closing.
