### ISSUE TITLE
Missing Documentation (config.yaml)

### ISSUE THREAD

**Issue by jabelone** [mapillary/OpenSfM#315]
I'm trying to use OpenSfM for a project but am having trouble understanding the different configuration parameters that are available. The configuration section ([link](http://opensfm.readthedocs.io/en/latest/using.html#configuration)) appears to be missing. It would be great if someone could write up a quick guide on what options are available and what they do. Also I seem to be having difficulty running "3D" datasets captured from a drone. (mainly cell phone towers) I'm hoping those issues are just a configuration problem though so I'll add a new issue later if it's not.

**Comment by paulinus** [comment]
We are lagging on documentation, sorry. The best source for a short explanation of the parameters is https://github.com/mapillary/OpenSfM/blob/master/opensfm/config.py

The default parameters should work fine for most situations, though. Please, do post an issue with the images if the reconstruction fails. Thanks!

**Comment by jabelone** [comment]
After tweaking the options it hasn't made much difference. Can I pm you a link to the dataset? (I can't share it publicly sorry) OpenSfM seems to have stitched individual vertical sections of the tower pretty well, but there are lots of random images everywhere and each vertical section seems quite "disjointed".

**Comment by paulinus** [comment]
can you send me the link to pau at mapillary.com? thanks

**Comment by jabelone** [comment]
Will do thanks heaps :)
