### ISSUE TITLE
Add logic to handle 0 values in DOP Values

### ISSUE THREAD

**Issue by smathermather** [mapillary/OpenSfM#318]
Some cameras apparently give 0 values for DOP in exif data, causing divide-by-zero errors in OpenSfM (ht @pierotofy for noticing).

See: http://community.opendronemap.org/t/float-divison-by-zero-error/317/4

**Comment by pierotofy** [comment]
I think this was already solved with #298 :cheers:

**Comment by smathermather** [comment]
Ah, I'm behind the times I see. Awesome
