### ISSUE TITLE
spherical camera upright.

### ISSUE THREAD

**Issue by happyfrank** [mapillary/OpenSfM#319]
Dear @paulinus  how do you keep spherical camera orientation and position always upright?

**Comment by paulinus** [comment]
By default, the reconstruction will be aligned with the GPS positions while trying to keep the cameras looking towards the horizon.
So for 360 cameras, this assumes that you are holding the camera upright and that the horizon appears horizontal in the equirectangular pano

**Comment by happyfrank** [comment]
@paulinus  That's all right. Thanks ^v^
