### ISSUE TITLE
what is the unit of 'focal_piror' in 'camera_models.json'?

### ISSUE THREAD

**Issue by Geo-fortune** [mapillary/OpenSfM#321]
below is my `camera_models.json`file:
> {
    "v2 unknown unknown 1280 720 perspective 0": {
        "focal_prior": 0.85, 
        "width": 1280, 
        "k1": 0.0, 
        "k2": 0.0, 
        "k1_prior": 0.0, 
        "k2_prior": 0.0, 
        "projection_type": "perspective", 
        "focal": 0.85, 
        "height": 720
    }
}

in this file , the 'focal_prior' & 'focal':0.85 is 0.85 mm?or 850 pixels? 
after calibration my camera , the focal of this image is 1493 pixels。

**Comment by Geo-fortune** [comment]
can you leave your e-mail  and I  can't e-mail my question through the e-mail add in your main page

**Comment by paulinus** [comment]
Focal and focal_prior are the ratio between the focal length and the width of the sensor.
If you have the focal length in pixels, then you should set `focal` to be `focal_length_in_pixels / image_width_in_pixels`
(that assumes that width is larger than height)

**Comment by YanNoun** [comment]
No answer in a while, closing.
