### ISSUE TITLE
Ideal machine configuration to run OpenSfm

### ISSUE THREAD

**Issue by binshi** [mapillary/OpenSfM#322]
What would be the ideal AWS ec2 machine configuration to run OpenSfm? Currently it takes between 20 to 40 mins t2.xlarge(4vCPU, 16 gb RAM) instance.

**Comment by ManishSahu53** [comment]
@paulinus can you us what process will vary exponentially ?
I know Bundle adjustment will but not sure of any others.

**Comment by paulinus** [comment]
Matching will scale quadratically but can be limited by [matching only gps or time neighbors](https://github.com/mapillary/OpenSfM/blob/50ec813ef65be6d172df611d27d9f5e02f4e41e3/opensfm/config.py#L52-L54)
The reconstruction scales more than quadratically but using local bundle adjustment (which is the default) helps in getting close to linear reconstruction times.
The dense reconstruction step scales linearly with the number of images.

**Comment by YanNoun** [comment]
No answer in a while, closing.
