### ISSUE TITLE
How to force OpenSfM to use a single camera parameters for the whole dataset

### ISSUE THREAD

**Issue by stanathong** [mapillary/OpenSfM#324]
Thank you for your great work. It's awesome!

I have a sequence of images with GPS exif taken by a single camera. The resulting `reconstruction.json` shows two camera parameters. I was wondering if providing `camera_models_overrides.json` containing a single camera would help force it to apply a single intrinsics to all images in the dataset.

Thanks very much for your help.

**Comment by jhacsonmeza** [comment]
In the `config.ymal` file I suggest you add the following line:
`optimize_camera_parameters: no`
With this the camera parameters given in `camera_models_overrides.json` are not optimized and they don't change.

**Comment by stanathong** [comment]
@jhacsonmeza 
Thanks very much for your reply. I will test it and update the result once done. Cheers!

**Comment by stanathong** [comment]
Thank both of you for your suggestions.

I have run it with `optimize_camera_parameters: no` added to `config.yaml`. It still contains two set of `cameras` with their `shots` in `reconstruction.json` although both of them have the same camera names and parameters. 

Could you help clarify what this means and why OpenSfM had to group them into two sets? (providing that the images in the dataset are taken by a single camera). 

Thank you very much for your help.

**Comment by jhacsonmeza** [comment]
@stanathong if the camera name that you provide in the `camera_models_overrides.json` is the same that you get in the EXIF information of images, you only should have only one camera in the `reconstruction.json` file. Is very strange that you have two camera names. Can you show us the "cameras" part of `reconstruction.json` file that you get before "shots"?

**Comment by stanathong** [comment]
@jhacsonmeza 
Thanks very much for getting back to me. Here is the two camaras detail copied from reconstruction.json:

        "cameras": {
            "v2 pointgrey zebra2cropped-carriageway 1920 1080 perspective 0": {
                "focal_prior": 0.9266421215320464, 
                "width": 1920, 
                "k1": -0.2809388622126435, 
                "k2": 0.07902100416358199, 
                "k1_prior": 0.0, 
                "k2_prior": 0.0, 
                "projection_type": "perspective", 
                "focal": 0.9266421215320464, 
                "height": 1080
            }
        }, 
       ....
        "cameras": {
            "v2 pointgrey zebra2cropped-carriageway 1920 1080 perspective 0": {
                "focal_prior": 0.9266421215320464, 
                "width": 1920, 
                "k1": -0.2809388622126435, 
                "k2": 0.07902100416358199, 
                "k1_prior": 0.0, 
                "k2_prior": 0.0, 
                "projection_type": "perspective", 
                "focal": 0.9266421215320464, 
                "height": 1080
            }
        }, 

And this is what I added to camera_models_overrides.json, which is exactly the same as the cameras above.

```
{
    "v2 pointgrey zebra2cropped-carriageway 1920 1080 perspective 0": {
        "focal_prior": 0.9266421215320464, 
        "width": 1920, 
        "k1": -0.2809388622126435, 
        "k2": 0.07902100416358199, 
        "k1_prior": 0.0, 
        "k2_prior": 0.0, 
        "projection_type": "perspective", 
        "focal": 0.92664212153204643, 
        "height": 1080
    }
}

```
In the exif, the camera make is `pointgrey` and the camera model is `zebra2cropped-carriageway`.

Thanks for your help.

**Comment by jhacsonmeza** [comment]
It is rare that you get the same camera twice, but both have exactly the same intrinsic values that are the same ones you provided in the `camera_models_overrides.json`. Having this way, you still have a problem anyway?

**Comment by stanathong** [comment]
@jhacsonmeza 
Thanks for your reply. Though I still don't know the reason of OpenSfM splitting the images into two group, I would close this issue as my problem of having two intrinsics has been solved.
Thanks very much for your help.
