### ISSUE TITLE
Submodels relative symlinks

### ISSUE THREAD

**Issue by Jesse-jApps** [mapillary/OpenSfM#326]
When creating submodels with `bin/opensfm create_submodels data/my_dataset`, an images folder is created in every submodel directory. The contained images are symlinks to the real image file.

Those symlinks are created using relative paths, which results in an error if I try to run `bin/opensfm undistort data/my_dataset/submodels/submodel_0000`.

Creating the symlink with the absolute path would resolve this issue.
That would be in` opensfm/large/metadataset.py` in row `150`.
Instead of
```
os.symlink(src, dst)
```
with this
```
os.symlink(os.path.abspath(src), dst)
```

**Comment by paulinus** [comment]
This is indeed a bug. In most cases, `src` is already an absolute path but not always.

I've fixed it by linking to the path relative to the destination folder, https://github.com/mapillary/OpenSfM/commit/afa546be98e790ce47db7b4e005eaa2e812e8e03. This way we avoid absolute links and keep the folder movable.

Thanks for finding out and, please, let me know if the problem persists.
