### ISSUE TITLE
Need some advice regarding the configuration file

### ISSUE THREAD

**Issue by KhaledGabr** [mapillary/OpenSfM#328]
Hi all, 

My goal is to retrieve the camera positions of my shots. I am shooting the images using dslr and 4 fisheye shots to cover 360*180 degree, I then stitch them to create a 360 HDR panorama. When I feed the 360 images to opensfm, it fails to match some of the images, although there were visually enough overlap between them. 

I need some advice regarding how to setup the configuration file to increase the amount of matched images. Accuracy & processing time is not a priority, but having the maximum amount of localised images is necessary for my purpose. 

Thanks in advance,

**Comment by russkel** [comment]
Hello,
How many images are you using, is it 4 or 360? What does "360*180 degree" mean?

Is there a reason why you are stitching the images prior to feeding into OpenSfM? I can't help but think the stitching process is going to obscure the camera location information by transforming parts of the image.

It might help posting the logs of the extract_exif --> match_features steps so we can see where about it is going astray. Also the camera_models.json file may provide some illumination.
