### ISSUE TITLE
How to use brown camera model?

### ISSUE THREAD

**Issue by stanathong** [mapillary/OpenSfM#332]
I found brown camera model has been implemented in OpenSfM through the past issues. However, I couldn't find a way to use it or set it in config.yaml. Could you suggest me how to do this please? Thank you for your help.

**Comment by ManishSahu53** [comment]
Make a json file with name "camera_models_overrides.json". And enter information as given below.
{
    "v2 dji fc6310 5472 3648 perspective 0.6666": {
        "focal_prior": 0.753896593, 
        "width": 5472, 
        "k1": 0.0, 
        "k2": 0.0, 
        "k3": 0.0,
        "p1": 0.0,
        "p2": 0.0,
        "focal_x": 0.753896593, 
        "focal_y": 0.753896593,
        "projection_type": "brown", 
        "focal": 0.753896593, 
        "height": 3648
    }
}

**Comment by stanathong** [comment]
@ManishSahu53 
Thanks very much for your reply. I'm now re-running opensfm with the brown camera parameters in `camera_models_overrides.json` and will update here after finish running.

**Comment by stanathong** [comment]
The solution works fine. Thanks for your help.

**Comment by coderzbx** [comment]
> The solution works fine. Thanks for your help.
How to set c_x_prior and c_y_prior?
When using Brown perspective camera model, how to set c_x_prior and c_y_prior?
What's the relationship between "" and "_prior"? such as focal_x, focal_y, c_x, c_y, k1, k2, p1, p2, p3?
Now my camera has been calibrated, and the intrinsic parameters and distortion parameters are known.
Thanks
