### ISSUE TITLE
OpenGV build problem mac os

### ISSUE THREAD

**Issue by dchatzin** [mapillary/OpenSfM#335]
Hi all,

Although boost and boost-python are installed via Homebrew, there is a problem with boost and cmake when truing to build opengv as follows:

> cmake_ .. -DBUILD_TESTS=OFF -DBUILD_PYTHON=ON
> -- The CXX compiler identification is AppleClang 9.1.0.9020039
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found Eigen: /usr/local/include/eigen3 (Required is at least version "2.91.0") 
> CMake Error at /usr/local/Cellar/cmake/3.11.3/share/cmake/Modules/FindBoost.cmake:2044 (message):
>   Unable to find the requested Boost libraries.
> 
>   Boost version: 1.67.0
> 
>   Boost include path: /usr/local/include
> 
>   Could not find the following Boost libraries:
> 
>           boost_python
> 
>   No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
>   directory containing Boost libraries or BOOST_ROOT to the location of
>   Boost.
> Call Stack (most recent call first):
>   python/CMakeLists.txt:18 (find_package)
> 
> 
> Using boost/python/numpy.
> CMake Error at /usr/local/Cellar/cmake/3.11.3/share/cmake/Modules/FindBoost.cmake:2044 (message):
>   Unable to find the requested Boost libraries.
> 
>   Boost version: 1.67.0
> 
>   Boost include path: /usr/local/include
> 
>   Could not find the following Boost libraries:
> 
>           boost_python
>           boost_numpy
> 
>   No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
>   directory containing Boost libraries or BOOST_ROOT to the location of
>   Boost.
> Call Stack (most recent call first):
>   python/CMakeLists.txt:28 (find_package)
> 
> 
> -- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.10") 
> -- Found PythonInterp: /usr/local/bin/python2.7 (found version "2.7.15") 
> -- Found NumPy: version "1.14.4" /usr/local/lib/python2.7/site-packages/numpy/core/include
> -- Configuring incomplete, errors occurred!

and here is the cmake output log . 
[CMakeOutput.log](https://github.com/mapillary/OpenSfM/files/2088311/CMakeOutput.log)

Does anyone have an idea why this is happening?
Thanks a lot in advance!

**Comment by paulinus** [comment]
The name of the `boost-python` and `boost-numpy` components seem to have recently changed to `boost-python27` and `boost-numpy27`. These names are set in our CMakeList.txt and need to be updated for the newer names.

I've done a test on the `fix-boost-1.67` branch. You can either checkout that branch or apply the patch locally https://github.com/mapillary/OpenSfM/commit/9af631521995ad4938cfd69abc67989799b5db93

I'll put add some logic to choose the right name according to the version later in master.

**Comment by YanNoun** [comment]
OpenGV was removed here, closing : https://github.com/mapillary/OpenSfM/pull/553
