### ISSUE TITLE
How to obtain mesh and texture?

### ISSUE THREAD

**Issue by equiclouds** [mapillary/OpenSfM#336]
I used opensfm, and have got dense cloud points, and how to obtain mesh plus texture from dense cloud points.

When i use opensfm export to mvs, and generate a mvs file. I try to open it with openmvs viewer, and got an error:

```
error: invalid stream ( incompatible native format -size of long )
```

**Comment by zyioump** [comment]
According to [opensfm doc](https://opensfm.readthedocs.io/en/latest/using.html#quickstart) you can use these opensfm command :
- undistort
- compute_depthmaps
to finally obtain a `depthmaps/merged.ply` file which can be open by [MeshLabs]
(http://www.meshlab.net/)

**Comment by YanNoun** [comment]
No answer in a while, closing.
