### ISSUE TITLE
Are there any configurations and explainations to modify for creations of connection in the reconstruction?

### ISSUE THREAD

**Issue by rampagedog12** [mapillary/OpenSfM#338]
I have some problems on 3D reconstruction.
The result is shown in the following two pictures. The problem is that the cameras at the two ends are not connected... I think I need to modify some configurations, but I don't know what I can do....
![image](https://user-images.githubusercontent.com/25874618/41613385-6c2309c8-73c3-11e8-8de1-eedb421bf2a4.png)
![image](https://user-images.githubusercontent.com/25874618/41613390-737370aa-73c3-11e8-8686-c0d3c25a4175.png)

**Comment by paulinus** [comment]
hi @rampagedog12. In principle, there is no need to modify the configuration for such a sequence. 

When images are not connected, it means that either matching failed to find correspondences between the images or that it found correspondences but they do not align well with the reconstructed point so far.

This second option could easily happen if the scene (the person in this case) is not completely static. Did the subject move during the capture?

**Comment by paulinus** [comment]
Unfortunately, the subject needs to be static for SfM to work. Hard to do on humans with a single camera. Most human scanners use multiple cameras, so they can all take the picture at once.
