### ISSUE TITLE
compute_depthmaps: assert shot.camera.projection_type == 'perspective' failed after undistort

### ISSUE THREAD

**Issue by Jekyll1021** [mapillary/OpenSfM#339]
Hi, 

I'm using the following camera model to process a video.

`{
    "v2 unknown unknown -1 -1 perspective 0": {
        "width": 2704,
        "projection_type": "equirectangular",
        "height": 2028
    }
`

after I look into the `undistorted_reconstruction.json` file which I believe `compute_depthmaps.py` read, it still have 

`[
    {
        "cameras": {
            "v2 unknown unknown -1 -1 perspective 0": {
                "width": 2704,
                "projection_type": "equirectangular",
                "height": 2028
            }
        },
        "shots": {
            "A00101120298.jpg": {
                "orientation": 1,
                "camera": "v2 unknown unknown -1 -1 perspective 0",
                "gps_position": [
                    0.0,
                    0.0,
                    0.0
                ],
                "gps_dop": 999999.0,
                "rotation": [
                    -1.5495469079325543,
                    -2.0714317503167252,
                    0.66616894017192141`

The equirectangular camera instead of a perspective one. I wonder if there is a quick fix over that.

**Comment by paulinus** [comment]
That should not happen, @Jekyll1021. When undistorting the reconstruction, equirectangular shots are converted to 6 perspective shots. This happens [here](https://github.com/mapillary/OpenSfM/blob/0449ad184e08d1a528c61d87fcaeccb0ca32366c/opensfm/commands/undistort.py#L63-L70).

If it is not happening for you, either some files were modified after calling `undistort` or there is a bug. Do you have a small dataset where this happens that you can share?
thanks

**Comment by Jekyll1021** [comment]
Thanks! let me upload a small dataset tonight.

**Comment by paulinus** [comment]
@Jekyll1021, I'll close this one assuming you managed to make it work. Let me know if that is not the case. Thanks.
