### ISSUE TITLE
How to extract reprojection error factor of spatial points in two images from undistorted_reconstruction.json

### ISSUE THREAD

**Issue by abhaykagalkar** [mapillary/OpenSfM#340]
i am trying to implement "3D Reconstruction through Measure Based Image Selection" this paper and in this paper it is given that reprojection error of spatial points in two images is obatined using OpenSFM. i tried  but unable to get reprojection error  https://ieeexplore.ieee.org/document/6746422/

**Comment by paulinus** [comment]
You can compute the reprojection error by projecting each point of the reconstruction onto each image it is seen and then computing the distance between the projection and the observation.

In `reconstruction.json` these values are already computed and stored in the `reprojection_error` field of each point.

**Comment by YanNoun** [comment]
No answer in a while, closing.
