### ISSUE TITLE
Trouble georeferencing reconstruction after sfm step

### ISSUE THREAD

**Issue by ManishSahu53** [mapillary/OpenSfM#350]
I have ran sfm step and got sparse point cloud in local coordinate system. I would like to convert it into wgs 84 or projected utm coordinate system. Since I dont have prj file of it, I can't use directly **export_geocoords.py**. So I change this line https://github.com/mapillary/OpenSfM/blob/0420567acc9945b8fa1b27f2c7598db4bcd8715a/opensfm/commands/export_geocoords.py#L60
to ``` projection = pyproj.Proj(init='epsg:' + str(epsg_code)) ``` so that I just have to enter only epsg code. But results are not as I expected.  It seems translation of points are fine but for cameras it is incorrect. Can you tell me what am I doing wrong?
[Reconstructions](https://drive.google.com/drive/folders/1LuXPLO92Ss-9W4GXUFffpUsebCEFOZkB?usp=sharing)

![image](https://user-images.githubusercontent.com/27155127/43892708-516f1500-9bea-11e8-828b-383bb76e6f73.png)

**Comment by YanNoun** [comment]
Hi @ManishSahu53 , this was fixed here : https://github.com/mapillary/OpenSfM/pull/710, so I'm closing this issue.
