### ISSUE TITLE
Compiling error: num_linear_solver_threads

### ISSUE THREAD

**Issue by dcazzato** [mapillary/OpenSfM#356]
Hi all,

I am having the following problem while trying to compile the project (all preliminaries steps have been successful executed). In particular, I have the error:

> In file included from /home/dario/Development/OpenSfM/opensfm/src/csfm.cc:9:0:
/home/dario/Development/OpenSfM/opensfm/src/bundle.h: In member function ‘void BundleAdjuster::Run()’:
/home/dario/Development/OpenSfM/opensfm/src/bundle.h:1401:13: error: ‘struct ceres::Solver::Options’ has no member named ‘num_linear_solver_threads’
     options.num_linear_solver_threads = num_threads_;
             ^
In file included from /home/dario/Development/OpenSfM/opensfm/src/csfm.cc:12:0:
/home/dario/Development/OpenSfM/opensfm/src/reconstruction_alignment.h: In member function ‘void ReconstructionAlignment::Run()’:
/home/dario/Development/OpenSfM/opensfm/src/reconstruction_alignment.h:603:13: error: ‘struct ceres::Solver::Options’ has no member named ‘num_linear_solver_threads’
     options.num_linear_solver_threads = 8;
             ^
CMakeFiles/csfm.dir/build.make:62: recipe for target 'CMakeFiles/csfm.dir/csfm.cc.o' failed

I googled but I was not able to solve it.

Any advice would be really appreciated.
Regards,

**Comment by dcazzato** [comment]
Please note that the error disappear using ceres-solver 1.14.x version, and occurs with the ceres-solver master version.

**Comment by jamalov** [comment]
> Hi all,
> 
> I am having the following problem while trying to compile the project (all preliminaries steps have been successful executed). In particular, I have the error:
> 
> > In file included from /home/dario/Development/OpenSfM/opensfm/src/csfm.cc:9:0:
> > /home/dario/Development/OpenSfM/opensfm/src/bundle.h: In member function ‘void BundleAdjuster::Run()’:
> > /home/dario/Development/OpenSfM/opensfm/src/bundle.h:1401:13: error: ‘struct ceres::Solver::Options’ has no member named ‘num_linear_solver_threads’
> > options.num_linear_solver_threads = num_threads_;
> > ^
> > In file included from /home/dario/Development/OpenSfM/opensfm/src/csfm.cc:12:0:
> > /home/dario/Development/OpenSfM/opensfm/src/reconstruction_alignment.h: In member function ‘void ReconstructionAlignment::Run()’:
> > /home/dario/Development/OpenSfM/opensfm/src/reconstruction_alignment.h:603:13: error: ‘struct ceres::Solver::Options’ has no member named ‘num_linear_solver_threads’
> > options.num_linear_solver_threads = 8;
> > ^
> > CMakeFiles/csfm.dir/build.make:62: recipe for target 'CMakeFiles/csfm.dir/csfm.cc.o' failed
> 
> I googled but I was not able to solve it.
> 
> Any advice would be really appreciated.
> Regards,

same problem. Did you solved it?

**Comment by jamalov** [comment]
Solved! u should just edit 2 files
1) /home/dario/Development/OpenSfM/opensfm/src/bundle.h
2) /home/dario/Development/OpenSfM/opensfm/src/reconstruction_alignment.h

comment lines 
options.num_linear_solver_threads = num_threads_;   - in 1 file
options.num_linear_solver_threads = 8;  - in 2 file

Solver::Options::num_linear_solver_threads is deprecated, Solver::Options::num_threads controls all parallelism in Ceres Solver now.  http://ceres-solver.org/version_history.html

I hope this helps

**Comment by paulinus** [comment]
lines removed from master. Thanks!
