### ISSUE TITLE
Use of akaze instead of hahog

### ISSUE THREAD

**Issue by sau1994** [mapillary/OpenSfM#357]
Hi, 
I want to see what are the results of using only akaze algorithm in the feature detection and extraction. i guess Hahog is default. what changes do I have to make and where do I have to make them to run using only akaze?

Please help.

**Comment by paulinus** [comment]
You can set the option
```
feature_type: AKAZE
```
in your `config.yaml` file.

You can check the list of options available here https://github.com/mapillary/OpenSfM/blob/master/opensfm/config.py#L10
