### ISSUE TITLE
opensfm vs visualsfm

### ISSUE THREAD

**Issue by michaelgli** [mapillary/OpenSfM#36]
I recently used visualsfm a little. It's pretty good. It's free but not open source.

Is opensfm geared to compete with visualsfm? or opensfm has a different focus?

Thanks,
-michael

**Comment by paulinus** [comment]
Visualsfm is great and it's solving exactly the same problem, but it is not open source. We are building OpenSfM with a liberal license and use it internally to find 3D camera positions in Mapillary.
