### ISSUE TITLE
Solve :: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by AhmedSaym** [mapillary/OpenSfM#362]
> #to solve this problem : `[module compiled against API version 0xa but this version of numpy is 0x9 Traceback (most recent call last):   File "<stdin>", line 1, in <module> ImportError: numpy.core.multiarray failed to import ]
------------------------------ Solve ------------------
1- make sure you doing uninstall for numpy.exe (( windows ))
2- pip install numpy
3- import cv2 >>> Successful `

**Comment by paulinus** [comment]
Closing this since it does not seem to be related to OpenSfM. Please, reopen with a question if help is needed.
