### ISSUE TITLE
ModuleNotFoundError: No module named 'pyopengv'

### ISSUE THREAD

**Issue by lanluk** [mapillary/OpenSfM#366]
Hello there,
after a successfull instaltion of openSfM with all dependencies I have trouble which I am not able to fix by myself.

I tried to execute the first test-examples. 

`bin/opensfm_run_all data/berlin`

Thereby python can not find the module 'pyopengv':

`from opensfm import matching File 
.../Programme/OpenSfM-master/opensfm/matching.py", line 3, in <module>
     import pyopengv
ModuleNotFoundError: No module named 'pyopengv'`

It seems like the Module "pyopengv" is not sourced in Python 3.6. -> Cause if I try to execute the `OpenSfM-master/opengv/python/test.py` with Python 2.7 the module is loaded successfully.
 
I am using Python 3.6.5 and an Ubuntu 18.04 distribution.

I am very thankfull for any help.

Cheers,
Lukas

**Comment by GITNE** [comment]
You will have to find a PPA or build [OpenGV](https://github.com/laurentkneip/opengv "OpenGV") from scratch. I run into the same issue when building OpenSfM on Fedora 😞 But, it was fairly easy to build since it only depends on Eigen3 and OpenCV which are required by OpenSfM anyway. Oh, do not forget to build the `pyopengv` module too which is located in `python/` of OpenGV's source tree.

**Comment by paulinus** [comment]
@lanluk as we were discussing here https://github.com/laurentkneip/opengv/pull/79, it is likely that opengv for python 3 has been installed into the python 2 folder. Please try using opengv's cmake option `-DPYTHON_INSTALL_DIR=/usr/local/lib/python3.6/dist-packages/` to set the right destination.

**Comment by lanluk** [comment]
@paulinus thanks for your help. pyopengv is running in python 3.6 and OpenSFM finally works.
Thanks for your help =)

To make the whole solution public here:

`cmake ../opengv -DBUILD_PYTHON=ON -DPYBIND11_PYTHON_VERSION=3.6 -DPYTHON_INSTALL_DIR=/usr/local/lib/python3.6/dist-packages/`

And i can close this issue now.
