### ISSUE TITLE
Default Mapillary configuration 

### ISSUE THREAD

**Issue by GITNE** [mapillary/OpenSfM#368]
@paulinus Please, post the default Mapillary configuration (`config.yaml`) for testing reference. Thank you!

**Comment by paulinus** [comment]
@GITNE, Mapillary's internal SfM pipeline is calling OpenSfM methods with the default config.

**Comment by GITNE** [comment]
Alright, thank you @paulinus!

Which parameter should one tune to increase the number of feature detections?

**Comment by paulinus** [comment]
You can require a minimum number of features with the option `feature_min_frames` (https://github.com/mapillary/OpenSfM/blob/master/opensfm/config.py#L12)

**Comment by GITNE** [comment]
> `feature_min_frames`

Sorry for asking perhaps a bit dumb questions, but the value denotes features per image, right?
