### ISSUE TITLE
image not centered in the sensor

### ISSUE THREAD

**Issue by horstrand** [mapillary/OpenSfM#374]
Is there a way to introduce the parameters cx and cy from the intrinsec transformation matrix K? I see in types.py the get_K function returns the matrix with cx and cy equal 0.
And in case one would like to enter these values manually should they also be normalized to the image height or width, like the focal parameter?

Thanks for the support,

**Comment by YanNoun** [comment]
Hi @horstrand , you're right `c_x` and `c_y` are in normalized coordinates and should represent the shift from the ideal principal point, i.e. centered at (width/2, height/2). So by default, it is (0, 0).
