### ISSUE TITLE
Problem running on OS: missing OpenMP & No module named pyopengv

### ISSUE THREAD

**Issue by nekojan** [mapillary/OpenSfM#385]
I already `brew install open-mpi`.
But when I run `python3 setup.py build`, everything seems ok except for: 
> 
> -- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
> -- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
> -- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 

Then when I try `bin/opensfm_run_all data/berlin`, I get:

> Running using Python command: python
> Traceback (most recent call last):
>   File ".../OpenSfM/bin/opensfm", line 10, in <module>
>     from opensfm import commands
>   File ".../OpenSfM/opensfm/commands/__init__.py", line 4, in <module>
>     from . import match_features
>   File ".../OpenSfM/opensfm/commands/match_features.py", line 11, in <module>
>     from opensfm import matching
>   File ".../OpenSfM/opensfm/matching.py", line 3, in <module>
>     import pyopengv
> ImportError: No module named pyopengv

I run `make install` again, all looks fine:

> [ 92%] Built target opengv
> [ 97%] Built target random_generators
> [100%] Built target pyopengv
> Install the project...
> -- Install configuration: "Release"
> -- Installing: /usr/local/lib/libopengv.a
> -- Up-to-date: /usr/local/lib/cmake/opengv-1.0/opengvConfig.cmake
> -- Up-to-date: /usr/local/lib/cmake/opengv-1.0/opengvConfigVersion.cmake
> -- Up-to-date: /usr/local/lib/cmake/opengv-1.0/opengvTargets.cmake
> -- Up-to-date: /usr/local/lib/cmake/opengv-1.0/opengvTargets-release.cmake
> -- Up-to-date: /usr/local/include
> -- Up-to-date: /usr/local/include/opengv
> -- Up-to-date: /usr/local/include/opengv/sac_problems
> -- Up-to-date: /usr/local/include/opengv/sac_problems/relative_pose
> -- Up-to-date: /usr/local/include/opengv/sac_problems/relative_pose/RotationOnlySacProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac_problems/relative_pose/NoncentralRelativePoseSacProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac_problems/relative_pose/CentralRelativePoseSacProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac_problems/relative_pose/TranslationOnlySacProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac_problems/relative_pose/EigensolverSacProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac_problems/relative_pose/MultiCentralRelativePoseSacProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac_problems/relative_pose/MultiNoncentralRelativePoseSacProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac_problems/point_cloud
> -- Up-to-date: /usr/local/include/opengv/sac_problems/point_cloud/PointCloudSacProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac_problems/absolute_pose
> -- Up-to-date: /usr/local/include/opengv/sac_problems/absolute_pose/AbsolutePoseSacProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac_problems/absolute_pose/MultiNoncentralAbsolutePoseSacProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose
> -- Up-to-date: /usr/local/include/opengv/relative_pose/NoncentralRelativeAdapter.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/CentralRelativeWeightingAdapter.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/RelativeMultiAdapterBase.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/MACentralRelative.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/CentralRelativeMultiAdapter.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/NoncentralRelativeMultiAdapter.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/MANoncentralRelative.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/CentralRelativeAdapter.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/MANoncentralRelativeMulti.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/methods.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/main.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/sixpt
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/sixpt/modules.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/ge
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/ge/modules.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/fivept_stewenius
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/fivept_stewenius/modules.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/fivept_nister
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/fivept_nister/modules.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/fivept_kneip
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/fivept_kneip/modules.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/eigensolver
> -- Up-to-date: /usr/local/include/opengv/relative_pose/modules/eigensolver/modules.hpp
> -- Up-to-date: /usr/local/include/opengv/relative_pose/RelativeAdapterBase.hpp
> -- Up-to-date: /usr/local/include/opengv/point_cloud
> -- Up-to-date: /usr/local/include/opengv/point_cloud/PointCloudAdapter.hpp
> -- Up-to-date: /usr/local/include/opengv/point_cloud/MAPointCloud.hpp
> -- Up-to-date: /usr/local/include/opengv/point_cloud/methods.hpp
> -- Up-to-date: /usr/local/include/opengv/point_cloud/PointCloudAdapterBase.hpp
> -- Up-to-date: /usr/local/include/opengv/sac
> -- Up-to-date: /usr/local/include/opengv/sac/SampleConsensus.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/MultiSampleConsensusProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/Ransac.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/MultiRansac.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/SampleConsensusProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/implementation
> -- Up-to-date: /usr/local/include/opengv/sac/implementation/SampleConsensus.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/implementation/MultiSampleConsensusProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/implementation/Ransac.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/implementation/MultiRansac.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/implementation/SampleConsensusProblem.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/implementation/Lmeds.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/implementation/MultiSampleConsensus.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/Lmeds.hpp
> -- Up-to-date: /usr/local/include/opengv/sac/MultiSampleConsensus.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/CentralAbsoluteAdapter.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/AbsoluteMultiAdapterBase.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/MACentralAbsolute.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/AbsoluteAdapterBase.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/NoncentralAbsoluteAdapter.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/NoncentralAbsoluteMultiAdapter.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/methods.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/main.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/Epnp.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/upnp4.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/gpnp1
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/gpnp1/modules.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/upnp2.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/gp3p
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/gp3p/modules.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/gpnp4
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/gpnp4/modules.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/gpnp3
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/gpnp3/modules.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/gpnp2
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/gpnp2/modules.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/gpnp5
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/modules/gpnp5/modules.hpp
> -- Up-to-date: /usr/local/include/opengv/absolute_pose/MANoncentralAbsolute.hpp
> -- Up-to-date: /usr/local/include/opengv/math
> -- Up-to-date: /usr/local/include/opengv/math/cayley.hpp
> -- Up-to-date: /usr/local/include/opengv/math/arun.hpp
> -- Up-to-date: /usr/local/include/opengv/math/quaternion.hpp
> -- Up-to-date: /usr/local/include/opengv/math/gauss_jordan.hpp
> -- Up-to-date: /usr/local/include/opengv/math/Sturm.hpp
> -- Up-to-date: /usr/local/include/opengv/math/roots.hpp
> -- Up-to-date: /usr/local/include/opengv/OptimizationFunctor.hpp
> -- Up-to-date: /usr/local/include/opengv/triangulation
> -- Up-to-date: /usr/local/include/opengv/triangulation/methods.hpp
> -- Up-to-date: /usr/local/include/opengv/Indices.hpp
> -- Up-to-date: /usr/local/include/opengv/types.hpp
> -- Up-to-date: /usr/local/lib/python3.6/dist-packages/pyopengv.cpython-37m-darwin.so

I'm on MacOS High Sierra.

Note: I tried [issues 366](https://github.com/mapillary/OpenSfM/issues/366) and [179](https://github.com/mapillary/OpenSfM/issues/179) solutions, but these don't seem to help me.

**Comment by paulinus** [comment]
The missing OpenMP messages can be safely ignored.

About python3 not finding `pyopengv`. The logs say that `pyopengv` is installed at `/usr/local/lib/python3.6/dist-packages/pyopengv.cpython-37m-darwin.so`.  There seem to be a missmatch between the versions in the folder and the file name `/python3.6/` vs `.cpython-37m`. That might prevent python from loading it.

**Comment by nekojan** [comment]
Thank you.
