### ISSUE TITLE
How to reproject the 3D point cloud

### ISSUE THREAD

**Issue by freddifederica** [mapillary/OpenSfM#393]
Hello everyone, 

I am trying to retroject the 3D Point cloud from the  "merged.ply'" file using the information on camera rotation (R) and translation (T) given in the "reconstruction.json" file. 
Important note: I am converting to spherical coordinate system because I am using an equirectangular camera. 
In case you want to download my "merged.ply" and "reconstruction.json" to use the same data here is a link:

https://drive.google.com/open?id=1ZLktc5LJeY3GD8-gawZG2LqveUfxMvhK https://drive.google.com/file/d/1bVFkEHOWpgmzvLAHcaRecQshJ0HGpvRG
Basically I am doing this to reproject the point cloud to a 2D image:

```
import numpy
from PIL import Image
import plyfile 
import time
import math
import matplotlib.pyplot as plt
import sys
import os
import json
import cv2

import numpy as np

print('Importing')
now = time.time()
plydata = plyfile.PlyData.read('../depthmaps/merged.ply')
print('Imported in',time.time()-now,"seconds")
vertex_list=plydata.elements[0]

x =vertex_list["x"]
# swapped z and y as they seem to be using a different convention...
y =vertex_list["y"]
z =vertex_list["z"]
red = vertex_list['diffuse_red']
green = vertex_list['diffuse_green']
blue = vertex_list['diffuse_blue']
xyz1 = np.c_[x,y,z,np.ones(len(x))]
rgb = np.c_[red,green,blue]
R=[rx,ry,rz]=[+0.4246409810336499,+1.9613655024298424,-2.00126830597893] 
T=[tx,ty,tz]=[-703.6442031122513,-2.1610079391805024,-409.73094670642655]

M=cv2.Rodrigues(numpy.array(R))[0]
M=numpy.concatenate([M,numpy.matrix(T).T],axis=1)
M=numpy.concatenate([M,numpy.matrix([0,0,0,1])],axis=0)

xyz_c=(M*(xyz1.T)).T
x=numpy.array(xyz_c[:,0]).reshape(len(xyz_c))
y=numpy.array(xyz_c[:,1]).reshape(len(xyz_c))
z=numpy.array(xyz_c[:,2]).reshape(len(xyz_c))

# convert to polar coords
start = time.time()
rho = np.sqrt(x**2+y**2) #cylindrical radius
phi = np.arctan2(y,x) #azimuthal angle
phi_mod = np.mod(phi,2*np.pi)
r = np.sqrt(x**2+y**2+z**2) #spherical angle (x,y)
theta = np.arccos(z/r) #polar angle (z)
end = time.time()
print('Converted in {:.3} seconds'.format(end-start))

# projection
width=3840
height=1920
image_cloud=numpy.zeros((height,width,3),dtype=numpy.uint8)

# generate x and y coordinates for image (round with cast to int)
im_y = (theta/np.pi*(height-1)).astype(np.int32)
im_x = (np.mod(phi,2*np.pi)/(2*np.pi)*(width-1)).astype(np.int32)
image_cloud[im_y,im_x] = rgb

output_folder="./output/"
os.makedirs(output_folder,exist_ok=True)
Image.fromarray(image_cloud).save(os.path.join(output_folder,"reprojected-cloud.png"))
```

The actual image that I am expecting to find should be something similar to this (as this is the original shot, number "01212.png" in the "reconstruction.json"):
![01212_original](https://user-images.githubusercontent.com/37051452/51973148-e519f280-2474-11e9-909b-2c72e053a3c5.png)

However the image I obtain from reprojecting is:
![111](https://user-images.githubusercontent.com/37051452/51973044-b6038100-2474-11e9-92e0-e39aa9bedff0.png)

I tried to use this as reference:
https://docs.opensfm.org/cam_coord_system.html
I also tried multiple combinations of assignment of x,y,z to understand if the problem might have been with a wrong convention that I am using. I obtained some slightly better results however they are still not the correct solution, for example I obtained:
![xzy-1-11](https://user-images.githubusercontent.com/37051452/51973279-27433400-2475-11e9-8cb5-32362c4e34a6.png)

Does anyone know what is going wrong and what the right approach is? 
Thanks everyone for your help

**Comment by freddifederica** [comment]
Solved - issue closed, the conversion to polar coordinates it done using a different convention for latitude and longitude (involving arcsin instead of arccos), moreover the x-y-z convention is different too.

**Comment by yuancaimaiyi** [comment]
@freddifederica  Hi ,Can you specifically share the correct conversion formula about spherical camera,thanks

**Comment by mfkenson** [comment]
@freddifederica would be nice if you could give some hints on the critical steps you made
