### ISSUE TITLE
failed at build, ubuntu 16.04, 32bits 

### ISSUE THREAD

**Issue by marceloarguello700** [mapillary/OpenSfM#398]
Hi, 
when run this command: sudo python3 setup.py build

I failed, with next:

Waht can be wrong ??

Configuring for python 3.5...
-- pybind11 v2.2.4
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- A library with BLAS API found.
-- Found AMD library: /usr/lib/i386-linux-gnu/libamd.so
-- Found AMD header in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/i386-linux-gnu/libcamd.so
-- Found CAMD header in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/i386-linux-gnu/libcolamd.so
-- Found COLAMD header in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/i386-linux-gnu/libccolamd.so
-- Found CCOLAMD header in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/i386-linux-gnu/libcholmod.so
-- Found CHOLMOD header in: /usr/include/suitesparse
-- Found CXSPARSE library: /usr/lib/i386-linux-gnu/libcxsparse.so
-- Found SuiteSparseQR library: /usr/lib/i386-linux-gnu/libspqr.so
-- Found SuiteSparseQR header in: /usr/include/suitesparse
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Found SuiteSparse_config library: /usr/lib/i386-linux-gnu/libsuitesparseconfig.so
-- Found SuiteSparse_config header in: /usr/include/suitesparse
-- Adding librt: /usr/lib/i386-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Did not find METIS library (optional SuiteSparse dependency)
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/userone/repos/OpenSfM/cmake_build
Compiling extension...
[  5%] Built target gtest
[ 15%] Built target akaze
[ 19%] Built target testing_main
[ 86%] Built target vl
[ 92%] Built target depthmap_test
[ 94%] Building CXX object CMakeFiles/csfm.dir/csfm.cc.o
In file included from /home/userone/repos/OpenSfM/opensfm/src/openmvs_exporter.h:3:0,
                 from /home/userone/repos/OpenSfM/opensfm/src/csfm.cc:10:
/home/userone/repos/OpenSfM/opensfm/src/third_party/openmvs/Interface.h:207:6: error: redefinition of ‘bool MVS::ARCHIVE::Save(MVS::ARCHIVE::ArchiveSave&, const _Tp&) [with _Tp = unsigned int]’
 bool Save<TYPE>(ArchiveSave& a, const TYPE& v) { \
      ^
/home/userone/repos/OpenSfM/opensfm/src/third_party/openmvs/Interface.h:219:1: note: in expansion of macro ‘ARCHIVE_DEFINE_TYPE’
 ARCHIVE_DEFINE_TYPE(size_t)
 ^
/home/userone/repos/OpenSfM/opensfm/src/third_party/openmvs/Interface.h:207:6: note: ‘bool MVS::ARCHIVE::Save(MVS::ARCHIVE::ArchiveSave&, const _Tp&) [with _Tp = unsigned int]’ previously declared here
 bool Save<TYPE>(ArchiveSave& a, const TYPE& v) { \
      ^
/home/userone/repos/OpenSfM/opensfm/src/third_party/openmvs/Interface.h:218:1: note: in expansion of macro ‘ARCHIVE_DEFINE_TYPE’
 ARCHIVE_DEFINE_TYPE(uint32_t)
 ^
/home/userone/repos/OpenSfM/opensfm/src/third_party/openmvs/Interface.h:212:6: error: redefinition of ‘bool MVS::ARCHIVE::Load(MVS::ARCHIVE::ArchiveLoad&, _Tp&) [with _Tp = unsigned int]’
 bool Load<TYPE>(ArchiveLoad& a, TYPE& v) { \
      ^
/home/userone/repos/OpenSfM/opensfm/src/third_party/openmvs/Interface.h:219:1: note: in expansion of macro ‘ARCHIVE_DEFINE_TYPE’
 ARCHIVE_DEFINE_TYPE(size_t)
 ^
/home/userone/repos/OpenSfM/opensfm/src/third_party/openmvs/Interface.h:212:6: note: ‘bool MVS::ARCHIVE::Load(MVS::ARCHIVE::ArchiveLoad&, _Tp&) [with _Tp = unsigned int]’ previously declared here
 bool Load<TYPE>(ArchiveLoad& a, TYPE& v) { \
      ^
/home/userone/repos/OpenSfM/opensfm/src/third_party/openmvs/Interface.h:218:1: note: in expansion of macro ‘ARCHIVE_DEFINE_TYPE’
 ARCHIVE_DEFINE_TYPE(uint32_t)
 ^
CMakeFiles/csfm.dir/build.make:62: recipe for target 'CMakeFiles/csfm.dir/csfm.cc.o' failed
make[2]: *** [CMakeFiles/csfm.dir/csfm.cc.o] Error 1
CMakeFiles/Makefile2:180: recipe for target 'CMakeFiles/csfm.dir/all' failed
make[1]: *** [CMakeFiles/csfm.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    build_c_extension()
  File "setup.py", line 45, in build_c_extension
    subprocess.check_call(['make', '-j2'], cwd='cmake_build')
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j2']' returned non-zero exit status 2

**Comment by GinaSt** [comment]
I have the same issue:
```

> 
>   File "setup.py", line 45, in build_c_extension
>     subprocess.check_call(['make', '-j4'], cwd='cmake_build')
>   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2
> 

```
Any solutions?

**Comment by hurricanedjp** [comment]
use tag v0.5.1

**Comment by adholmgren** [comment]
I had the same issue as well:
`#9 123.4   File "setup.py", line 37, in <module>
#9 123.4     build_c_extension()
#9 123.4   File "setup.py", line 33, in build_c_extension
#9 123.4     subprocess.check_call(['make', '-j4'], cwd='cmake_build')
#9 123.4   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
#9 123.4     raise CalledProcessError(retcode, cmd)
#9 123.4 subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.`

Going to tag v0.5.1 worked

**Comment by YanNoun** [comment]
Since v0.5.1 seems to solve the issue, I'm closing.
