### ISSUE TITLE
Ceres parameter block added with same double pointer

### ISSUE THREAD

**Issue by maak** [mapillary/OpenSfM#40]
I pulled the head recently and am seeing the following error:

F0930 15:49:03.158898 2057392896 problem_impl.cc:103] Check failed: size == existing_size Tried adding a parameter block with the same double pointer, 0x102980ac8, twice, but with different block sizes. Original size was 5 but new size is 3
**\* Check failure stack trace: ***
    @        0x1052c5146  google::LogMessage::Fail()
    @        0x1052c4933  google::LogMessage::SendToLog()
    @        0x1052c4e79  google::LogMessage::Flush()
    @        0x1052c76d5  google::LogMessageFatal::~LogMessageFatal()
    @        0x1052c544d  google::LogMessageFatal::~LogMessageFatal()
    @        0x10538e741  ceres::internal::ProblemImpl::InternalAddParameterBlock()
    @        0x105390525  ceres::internal::ProblemImpl::AddResidualBlock()
    @        0x1053911f9  ceres::internal::ProblemImpl::AddResidualBlock()
    @        0x105189242  BundleAdjuster::Run()
    @        0x1051953fd  boost::python::objects::caller_py_function_impl<>::operator()()
    @        0x1055e831a  boost::python::objects::function::call()
    @        0x1055ea48a  boost::detail::function::void_function_ref_invoker0<>::invoke()
    @        0x1055f1391  boost::python::handle_exception_impl()
    @        0x1055e9ef3  boost::python::objects::function_call()
    @        0x10000c7b2  PyObject_Call
    @        0x1000c071d  PyEval_EvalFrameEx
    @        0x1000c505b  PyEval_EvalFrameEx
    @        0x1000c505b  PyEval_EvalFrameEx
    @        0x1000c505b  PyEval_EvalFrameEx
    @        0x1000c505b  PyEval_EvalFrameEx
    @        0x1000c5ca3  PyEval_EvalCodeEx
    @        0x1000c5dc6  PyEval_EvalCode
    @        0x1000eb17e  PyRun_FileExFlags
    @        0x1000eb41a  PyRun_SimpleFileExFlags
    @        0x10010248d  Py_Main
    @        0x100000f54  start

Has anyone experienced this problem?

**Comment by paulinus** [comment]
Haven't seen it before. If it happens on a clean install, it is a bug. Is this running the `berlin` dataset?
