### ISSUE TITLE
Test on my own camera, need I modify the camera intrinsic?

### ISSUE THREAD

**Issue by myhooo** [mapillary/OpenSfM#405]
Hello everyone,
I am trying to test OpenSfM on my own data which taken by my own camera, I wonder to know if I should change the camera intrinsic and where should I edit.
Looking forward to your replay!

**Comment by YanNoun** [comment]
Hi,

You can modify by first copying `camera_models.json`as a new file `camera_models_overrides.json`, and then modifying `camera_models_overrides.json`.

Please see camera model documentation then : https://www.opensfm.org/docs/geometry.html#coordinate-systems

Yann
