### ISSUE TITLE
[Question] how to get dense textured mesh

### ISSUE THREAD

**Issue by chris-aeviator** [mapillary/OpenSfM#407]
Hi! I'm comparing OpenSfM results to OpenMVS. Since I'd prefer using OpenSfM due to it's webplayer and compability with machines that are used here, I'm trying to get the same result I'm getting from OpenMVS.

With the standard config of OpenSfM whoever I get a much faster calculation (aprox. 5 min compared to about 30 mins with Visual FSM for sparse point cloud and OpenMVS for dense, resconstruction, refinement and texturing accoring to https://groups.google.com/forum/#!topic/vsfm/VcXGvP1HuMo on an i7 4,2ghz 6 core, GForce 1070) but it will get me a way less accurate result when running `bin/opensfm_run_all`. Since I'm using default settings for both of these configurations I wonder if anybody could help me getting the correct settings to construct a similar result with OpenFsm

EDIT: just realized, is OpenSfM doing a textured mesh calculation at all?

**Comment by pierotofy** [comment]
Hey @chris-aeviator :hand:, no OpenSfM does not have textured mesh capabilities. But you can export the dense reconstruction in a variety of formats and use other tools to achieve that.

**Comment by chris-aeviator** [comment]
@pierotofy thx for your reply! Is there any way I can import a dense(+textured) model into the web viewer/ openSfm?

**Comment by pierotofy** [comment]
With some coding, probably yes. The viewer is built on top of three.js, so check out the documentation for threejs on loading OBJ files (+ MTL). https://threejs.org/docs/#examples/loaders/OBJLoader

**Comment by FreddieRa** [comment]
@chris-aeviator Are you only looking at the online reconstruction? This is a sparse mesh just for demonstration purposes as far as I can see. You actually want to look at "merged.ply" in the depthmaps folder within your project folder.

**Comment by YanNoun** [comment]
No answer in a while, closing.
