### ISSUE TITLE
csfm.so: undefined symbol: cs_di_chol

### ISSUE THREAD

**Issue by smilecolon** [mapillary/OpenSfM#41]
when I run:
bin/run_all data/berlin

I get the following output:

![output_error](https://cloud.githubusercontent.com/assets/14998765/10312375/2be4e2a8-6c75-11e5-8a7f-4f862bd0020a.jpg)

Any ideas?
Thanks.

**Comment by paulinus** [comment]
This seems to be ceres missing libcxsparse which it should not need. Did you install the `libsuitesparse-dev` ubuntu package before building ceres?

**Comment by smilecolon** [comment]
The libsuitesparse-dev ubuntu package has been installed before building ceres.
I have installed step by step following on the https://github.com/mapillary/OpenSfM/blob/master/Dockerfile.
However, there is the suitesparse version 4.2.1 installed on my machine before installing libsuitesparse-dev. Is there any conflict?

Thanks,

**Comment by paulinus** [comment]
i could not reproduce the problem. @smilecolon please reopen if this is still an issue for you.

**Comment by sabado** [comment]
exactly same as @smilecolon  

> i could not reproduce the problem. @smilecolon please reopen if this is still an issue for you.

**Comment by zoey-shan** [comment]
I've got the same problem of "undefined symbol: cs_di_chol"
