### ISSUE TITLE
Can I get a densor point cloud based on undistorted_reconstruction.json?

### ISSUE THREAD

**Issue by perelmangao** [mapillary/OpenSfM#410]
It is a problem that I need to separate a pano-photo into six parts as a skybox model. I can't get smooth animation with undistorted_reconstruction.json. Is there any way to get a densor point cloud data for skybox model?

**Comment by YanNoun** [comment]
Hi,

Can elaborate a bit more. Is the dense point cloud generated (`merged.ply`) not dense enough ? Or is the `undistorted_reconstruction.json`. For the first one, you can control it using `depthmap_resolution`. For the latter, the SfM point cloud is not meant to be dense, however, you can control the number of points by putting a higher value to `feature_min_frames`.
