### ISSUE TITLE
[Question] GCP alignment

### ISSUE THREAD

**Issue by pierotofy** [mapillary/OpenSfM#413]
Hello :hand:

I have a small dataset captured from a drone. Each image has GPS lat/lon/alt information included.

For additional accuracy I've tried to include a GCP file. The resulting point cloud however, exported with `opensfm export_geocoords --dense` does not align well with the GCPs (it's offset by ~1 meter in the X and ~3 meters in the Y axix).

Point cloud coordinates (Xg and Yg) of GCP point (WGS84 UTM 16N):

![image](https://user-images.githubusercontent.com/1951843/55747733-eafaf980-5a0a-11e9-9f18-0706f4461f30.png)

Entry from GCP file:

```
609865.7259757777 4950688.244601672 170.675678 2704 2559 DJI_0027.JPG
```

GCP point (top left) vs actual position.

![image](https://user-images.githubusercontent.com/1951843/55747829-2a294a80-5a0b-11e9-94eb-d0433159f886.png)

OpenSfM config file:

```
use_exif_size: no
optimize_camera_parameters: yes
use_altitude_tag: True
align_method: naive
bundle_use_gcp: yes
bundle_use_gps: no
```

I'm wondering if this is expected, if I need to toggle a setting, or if there's something I should check (or did I find a bug)?

I should mention there are 5 GCPs in total and none of them align correctly.

**Comment by YanNoun** [comment]
Hi,

I'm not sure what went wrong, but the way we do align is by realigning the reconstruction on GPS+GCP after any whole bundle adjustment. It might not be the optimal way of doing it, and we're currently working on it.

So at the very end of the process, after last bundle, the reconstruction is aligned on GPS+GCP. It's already misleading since you might want not to use GPS (as GPS can be off by several meters compared to GCPs).

I made a tentative-untested branch `feat-gcp-align` that does not align on GPS AT ALL is `bundle_use_gps` is no, to see if it solves your case. let me know how it goes.

Yann

**Comment by pierotofy** [comment]
Hey @YanNoun, thanks for the reply! :hand:

Like you say, it looks like both GPS+GCP observations are used even though `budle_use_gcp` is set to `no`.

I will try the changes in your branch and report back my findings.

**Comment by pierotofy** [comment]
Looking good!!

![image](https://user-images.githubusercontent.com/1951843/59802982-2c840c80-92b8-11e9-9acd-b3de48131df1.png)

![image](https://user-images.githubusercontent.com/1951843/59802991-3443b100-92b8-11e9-8f53-40212963ac16.png)

![image](https://user-images.githubusercontent.com/1951843/59802997-39086500-92b8-11e9-9873-99124b7c52a1.png)

![image](https://user-images.githubusercontent.com/1951843/59803014-4291cd00-92b8-11e9-8673-51950096ccb4.png)

This is with:

```
bundle_use_gps: no
bundle_use_gcp: yes
```

And the changes from the `feat-gcp-align` branch.

**Comment by pierotofy** [comment]
Running with defaults (`bundle_use_gps: yes`, `bundle_use_gcp: no`) however yields:

During `./opensfm reconstruct`:

```
File "/code/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/code/SuperBuild/src/opensfm/opensfm/commands/reconstruct.py", line 23, in run
    incremental_reconstruction(data, graph)
  File "/code/SuperBuild/src/opensfm/opensfm/reconstruction.py", line 1323, in incremental_reconstruction
    data, graph, graph_inliers, reconstruction, remaining_images, gcp)
  File "/code/SuperBuild/src/opensfm/opensfm/reconstruction.py", line 1184, in grow_reconstruction
    align_reconstruction(reconstruction, gcp, config)
  File "/code/SuperBuild/src/opensfm/opensfm/align.py", line 16, in align_reconstruction
    res = align_reconstruction_similarity(reconstruction, gcp, config)
  File "/code/SuperBuild/src/opensfm/opensfm/align.py", line 58, in align_reconstruction_similarity
    return align_reconstruction_naive_similarity(config, reconstruction, gcp)
  File "/code/SuperBuild/src/opensfm/opensfm/align.py", line 87, in align_reconstruction_naive_similarity
    s = np.linalg.norm(Xp[0] - Xp[1])/np.linalg.norm(X[0] - X[1])
TypeError: unsupported operand type(s) for -: 'list' and 'list'
```

**Comment by YanNoun** [comment]
Hi,

I just updated the branch. Let me know how it goes. 

However, it seems that in your tests, you have only two images, right ? In that very specific case of two images (or any sets of images aligned on a line), as since we can't align a line in 3D, the result won't be good.

For such case (which is not ideal capture practice), it is better to use 'align_method` with `orientation_prior` along with `align_orientation_prior` set to `vertical`.

Maybe an additional `smart` setting would be useful by mixing `naive` and `orientation_prior` would be better : use `naive` when sufficiently constrained (non-aligned point), otherwise, switch to `orientation_prior`.

Yann

**Comment by pierotofy** [comment]
Hey @YanNoun,

I've further modified line 87 to wrap the other list into a numpy array (the same error had appeared without this change):

`s = np.linalg.norm(np.array(Xp[0]) - np.array(Xp[1]))/np.linalg.norm(np.array(X[0]) - np.array(X[1]))`

The dataset has `18` images in total (https://github.com/pierotofy/drone_dataset_brighton_beach) and I'm executing it with the following:

```
use_exif_size: no
feature_process_size: 2048
feature_min_frames: 8000
processes: 4
matching_gps_neighbors: 8
matching_gps_distance: 0
depthmap_method: PATCH_MATCH
depthmap_resolution: 640
depthmap_min_patch_sd: 1
depthmap_min_consistent_views: 3
optimize_camera_parameters: yes
undistorted_image_format: png
use_altitude_tag: yes
```

So that defaults to `align_method: naive`. I could certainly switch it to `align_method: prior` and `align_orientation_prior: vertical`. A bit of background, this is related to some work we're doing with OpenDroneMap (https://github.com/OpenDroneMap/ODM). The reason I've left it at `naive` is because while most datasets are of aerial images, we occasionally have users that use the program to reconstruct non-aerial datasets (perhaps of architectural buildings) in which the orientation is not vertical, but horizontal. Would that create problems if we imposed the orientation prior to `vertical` (would the program adjust for non-vertical inputs)? Sometimes there's also mixes of vertical images and horizontal images (mapping an area with vertical shots, followed by a "point of interest" set of horizontal images).

**Comment by pierotofy** [comment]
Result looks pretty good! Will run some further tests. 

![image](https://user-images.githubusercontent.com/1951843/59850242-c4750b00-9337-11e9-92d3-12720ea05187.png)

**Comment by pierotofy** [comment]
Branch with fix in https://github.com/mapillary/OpenSfM/compare/master...pierotofy:feat-gcp-align-fix

**Comment by YanNoun** [comment]
Ok, then you're right, in your case, it is better to let it to `naive`. The orientation prior is nice for strips of images, but the drawback is someone needs to decide for the scene orientation wrt. images. At Mapillary, our street-view datasets often consist in long strips of images, here's why we have this kind of option. 

Regarding your dataset, does it result in a single reconstruction or several partial ones ? You must have some chunk of two cameras somewhere since it entered the buggy code somehow.

BTW, we did a bit of improvment on the SfM these past weeks : 
 - Robustified the way we do incremental SfM : https://github.com/mapillary/OpenSfM/pull/427 . Improves a lot of some tricky scenes. Some options can greatly improve accuracy as well (see `bundle_outlier_filtering_type` in the PR)
 - Added image-based (BoW) matching. Maybe not of major interested for drone mapping, but allows matching of scene without GPS.

**Comment by pierotofy** [comment]
It results into a single reconstruction (which seems odd, given your explanation).

I've seen BoW matching and tried to use it a few days ago, albeit unsuccessfully for a few datasets (like the one I've linked above), when I switch the matcher_type to WORDS I always get:

```
opensfm reconstruct /datasets/brighton2/opensfm
2019-06-20 13:19:06,488 INFO: Starting incremental reconstruction
2019-06-20 13:19:06,491 INFO: 0 partial reconstructions in total.
```

Works fine with FLANN though.

I hadn't seen #427, I will for sure check it out!! Great to see all of these improvements in OpenSfM!

**Comment by YanNoun** [comment]
https://github.com/mapillary/OpenSfM/pull/429 add `matching_bow_neighbors` for using images themselves to decide which pairs to match (might not be relevant since you'll use GPS anyway). 

It is different from `bow_matcher_type` which is the matching method for matching the pair. Anyway, we ran benchmarks recently and FLANN is still the best option.

**Comment by pierotofy** [comment]
Mm, still no luck (full output is available here: https://pastebin.com/hrTQsyTk)

Perhaps the datasets that I'm trying are not ideal for bow?

**Comment by YanNoun** [comment]
With the following config.yaml :

```
processes: 12
use_exif_size: no
feature_process_size: 2048
feature_min_frames: 8000
depthmap_method: PATCH_MATCH
depthmap_resolution: 640
depthmap_min_patch_sd: 1
depthmap_min_consistent_views: 3
optimize_camera_parameters: yes
undistorted_image_format: png
use_altitude_tag: yes
matching_bow_neighbors: 8
matching_gps_neighbors: 0
matching_gps_distance: 0
```

Using `bow_matcher_type: BOW` I have after `create_tracks` : `Good tracks: 10077`
Using `bow_matcher_type: FLANN` instead (`FLANN being default) I have : `Good tracks: 10081`

My `camera_models_overrides.json` is (I tried with a Brown model to see if it removes the slight bowl effect, but didn't)

```
    "v2 dji fc300s 4000 2250 perspective 0.5555": {
        "focal_x_prior": 0.5555555555555556,
        "focal_y_prior": 0.5555555555555556, 
        "width": 4000, 
        "k1": 0.0, 
        "k2": 0.0, 
        "k1_prior": 0.0, 
        "k2_prior": 0.0, 
        "projection_type": "brown", 
        "focal_x": 0.5555555555555556, 
        "focal_y": 0.5555555555555556, 
        "height": 2250
    }
```

**Comment by pierotofy** [comment]
Oh, I think I understand now. I just need to set `matching_bow_neighbors` to a value > 0 to enable BoW. I kept setting `matcher_type` to `WORDS`, but that needs to remain `FLANN`? (Can you confirm I'm doing this right?)

p.s. you can use this camera model which has been computed using a better dataset.

```
{
    "v2 dji fc300s 4000 2250 perspective 0.5555": {
        "focal_prior": 0.5555555555555556, 
        "width": 4000, 
        "k1": -0.009399196808062386, 
        "k2": 0.015120083762071154, 
        "k1_prior": 0.0, 
        "k2_prior": 0.0,
        "projection_type": "perspective", 
        "focal": 0.5852784573769383, 
        "height": 2250
    }
}```

**Comment by YanNoun** [comment]
The two are independant :
 - `matching_bow_neighbors` > 0 will use BoW for selecting which pairs of images to match.
 - `matcher_type` can be set either `BOW` or `FLANN` and used when matching pairs, `FLANN` being better than `WORDS`.

**Comment by pierotofy** [comment]
Thanks for the explanation! I think there might be some bug (you mentioned you were able to process it OK, but still having issues, I swear I'm not crazy :) )

With:
```
processes: 4
use_exif_size: no
feature_process_size: 2048
feature_min_frames: 8000
depthmap_method: PATCH_MATCH
depthmap_resolution: 640
depthmap_min_patch_sd: 1
depthmap_min_consistent_views: 3
optimize_camera_parameters: yes
undistorted_image_format: png
use_altitude_tag: yes
matching_bow_neighbors: 8
matching_gps_neighbors: 0
matching_gps_distance: 0
bow_matcher_type: BOW
matcher_type: WORDS
```

```
root@07628e9f82a2:/source/OpenSfM# bin/opensfm create_tracks /datasets/brighton
2019-06-21 15:13:12,033 INFO: reading features
2019-06-21 15:13:12,215 DEBUG: Merging features onto tracks
2019-06-21 15:13:12,215 DEBUG: Good tracks: 0
```

Changing `matcher_type` to `FLANN` works.

This is the master branch of OpenSfM, built with docker this morning from a fresh clone.

**Comment by YanNoun** [comment]
OK, my bad, I was misleading and I forgot about the `bow_matcher_type` and `matcher_type`.

So correct BoW setting are :
 - `bow_matcher_type: FLANN` (default). Using `BOW` makes the command `detect_features` actually crash on my machine, as it is not a valid option. Then BoW assignment are not generated, and then further BoW use doesn't work (actually the command `match_features` should crash.
 - `matcher_type: FLANN` (default, best trade-off) or `matcher_type: WORDS` (faster, worse)

Additionally, the new `matching_bow_neighbors` > 0 setting allow matching dataset without GPS and/or bad GPS (indoor).

Overall the process is the following :

 - Extract features
 - Assign each feature to some words (hence Bag-of-Words, BoW). It's where `bow_matcher_type` is used.
 - Construct a list of pairs to match. This where `matching_{gps, bow, order, time}_neighbors` comes into action.
 - For each of these pairs, match their features using the matcher of `matcher_type`.

Hope that helps !

**Comment by pierotofy** [comment]
It does, thanks for taking the time to explain in more details!

I'm still unable to get this dataset to process, but I'll keep trying. I must be doing something wrong.

I will close this issue for now since the original discussion was about GCP alignment. I'll re-open a new issue to follow up with the BOW feature.

Thanks again! :+1:
