### ISSUE TITLE
No module named networkx even after installing it using pip3.

### ISSUE THREAD

**Issue by ujwalaparupalli** [mapillary/OpenSfM#414]
Hello everyone,
I have installed opensfm and trying to run 
`    bin/opensfm_run_all data/berlin` 
from command line. But I am getting an Import Error: No module name networkx. I have installed networkx using pip3 install networkx. It got installed successfully. I tried import networkx and it worked. But when I am again running `    bin/opensfm_run_all data/berlin` , I am getting the same Import Error. 
`     File "/..../OpenSfM/opensfm/dataset.py", line 10, in <module>
    import networkx as nx
ImportError: No module named networkx
`
It will be really helpful if someone can help me to solve this issue.
Thank you very much.

**Comment by YanNoun** [comment]
Hi,

Which python version are you using when running `bin/opensfm_run_all data`. Make sure it's the relevant one (eg. python2 or python3).

Yann
