### ISSUE TITLE
How to use prior data (gps, dop, compass etc.)?

### ISSUE THREAD

**Issue by WeirdKeksButtonK** [mapillary/OpenSfM#415]
Hi! I am trying to use some prior data:
a) gps
b) compass
c) accelerometer
d) dop

1. Which steps of the whole pipeline (opensfm_run_all) do benefit from this data? Are any of these fields (a, b, c, d) actually useless / ignored?

2. How to tell OpenSfm about this prior data? My current approach is inferred from the source code. Namely, I use "exif_overrides.json" like this:
```
exif_overrides[image] = {
    "gps" : {
        "latitude" :  my_lat,
        "longitude" : my_lon,
        "altitude" : my_altitude,
        "dop" : my_dop
    },
    "capture_time" : my_time,
    "compass" : my_compass,
    "accelerometer": my_accelerometer
}
```
However, I am not sure that I do everything correctly. Do I have to tweak `config.yaml` anyhow?

3. (a bit off-topic) How do I extract the updated compass value from the reconstruction file after the pipeline is completed?

**Comment by kzykmyzw** [comment]
I have similar question. Does OpenSfM benefit from EXIF GPS data when it estimates extrinsic camera parameters? I compared reconstructed results between w/ and w/o EXIF GPS, but the results looked almost the same.

**Comment by YanNoun** [comment]
Hello,

@kzykmyzw  Yes, GPS is used during bundle_adjustment (provided that `bundle_use_gps` is `True`). Its impact will depend on the value of `gps.dop` in EXIFs : a default value of 15 meters will have negligible impact, wehereas a RTK-like value of 0.01 meter can affect results.

@StrausMG 
1. Bundle adjustment will only use the GPS (gps and dop) data, (provided that `bundle_use_gps` is `True`). The rest (compass, accelerometer) is not used for now.

 2. To use your custom GPS data : 
 - Write them into `exif_overrides`
 - Delete any previous EXIF data/folder (to make sure `extract_metadata` won't re-use it !)
 - Run whole pipeline.

3. You can get the 3x3 rotation matrix of a `shot` by calling `shot.pose.get_rotation_matrix()`. Apply its tranpose to the Z-vector of the camera `[0, 0, 1]` by doing `np.transpose(shot.pose.get_rotation_matrix()).dot([0, 0, 1])`. you'll get the Z-vector in world coordinates. Taking the arc-tangent of it using `atan2(x, y)`, you'll get the compass angle.

**Comment by YanNoun** [comment]
@StrausMG 
Simpler answer for question 3. : you can use the script `bin/export_gps` instead which will export a reconstruction in GPS+Compass coordinates and in a `.csv` format.
