### ISSUE TITLE
error when building opensfm

### ISSUE THREAD

**Issue by Jiazheng-Yuan** [mapillary/OpenSfM#416]
This is what i had, which is the final step for build. After that nothing happens. opensfm still cannot be found
Configuring for python 3.7...
-- pybind11 v2.2.4
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- A library with LAPACK API found.
-- Found AMD library: /usr/local/lib/libamd.dylib
-- Found AMD header in: /usr/local/include
-- Found CAMD library: /usr/local/lib/libcamd.dylib
-- Found CAMD header in: /usr/local/include
-- Found COLAMD library: /usr/local/lib/libcolamd.dylib
-- Found COLAMD header in: /usr/local/include
-- Found CCOLAMD library: /usr/local/lib/libccolamd.dylib
-- Found CCOLAMD header in: /usr/local/include
-- Found CHOLMOD library: /usr/local/lib/libcholmod.dylib
-- Found CHOLMOD header in: /usr/local/include
-- Found CXSPARSE library: /usr/local/lib/libcxsparse.dylib
-- Found SuiteSparseQR library: /usr/local/lib/libspqr.dylib
-- Found SuiteSparseQR header in: /usr/local/include
-- Found Intel Thread Building Blocks (TBB) library: /usr/local/lib/libtbb.dylib, assuming SuiteSparseQR was compiled with TBB.
-- Found Intel Thread Building Blocks (TBB) Malloc library: /usr/local/lib/libtbbmalloc.dylib
-- Found SuiteSparse_config library: /usr/local/lib/libsuitesparseconfig.dylib
-- Found SuiteSparse_config header in: /usr/local/include
-- Found METIS library: /usr/local/lib/libmetis.dylib.
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /usr/local/lib/cmake/gflags
-- Detected gflags version: 2.2.2
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jiazheng/Desktop/OpenSfM/cmake_build
Compiling extension...
[  5%] Built target gtest
[ 40%] Built target akaze
[ 82%] Built target vl
[ 86%] Built target testing_main
[ 94%] Built target csfm
[100%] Built target depthmap_test
running build
running build_py
running build_scripts

Is this finished ? Nothing says like "finish building", I am new to this so i wanna make sure im not missing anything

**Comment by paulinus** [comment]
The log looks good. If you are not able to run it, please send the error you get when running
