### ISSUE TITLE
Different result get from reconstruction.json

### ISSUE THREAD

**Issue by iamwangyabin** [mapillary/OpenSfM#423]
HI,I test OpenSfM on TUM benchmark,the results of camera pose looks acceptable in the web viewer ,but when I extract "translation" and "rotation" from Json file and show these camera pose ,it  looks very strange......I look the doc you provided which says `The pose of a camera is determined by the rotation and translation that converts world coordinates to camera coordinates.` and I compute the camera pose by
```
def optical_center(shot):
    R = cv2.Rodrigues(np.array(shot['rotation'], dtype=float))[0]
    t = shot['translation']
    return -R.T.dot(t)
```

the result is :(the main problem I guess is the scale of Z coordinate is not right)

![2019-05-31 11-53-11屏幕截图](https://user-images.githubusercontent.com/38123329/58701839-abcba200-83d6-11e9-9ff8-5cdb0d2dfd1d.png)
![Figure_1](https://user-images.githubusercontent.com/38123329/58701853-ba19be00-83d6-11e9-9a63-5f3f3628664a.png)
Thanks a lot

**Comment by iamwangyabin** [comment]
By the way ,how to change parameters to have a Global Reconstruct?--just as openmvg do as GlobalSfM?
because its result looks great for a large linear dataset which also have loop closure, I read your doc and try to set 
```
matching_gps_distance: 0            
matching_gps_neighbors: 0             
matching_time_neighbors: 0            
matching_order_neighbors: 0  

retriangulation_ratio: 99999          # I think it is better dont retriangulate.... 
bundle_interval: 1361             # because dataset totally has 1361 images
bundle_new_points_ratio: 999999
local_bundle_radius: 1              # just as video mod
```
and the result is very bad......

but the GlobalSfM (by openMVG pipline) shows very good result:
![2019-06-03 11-13-30屏幕截图](https://user-images.githubusercontent.com/38123329/58875156-5b698280-86fd-11e9-997b-de8fc5ebf619.png)

**Comment by YanNoun** [comment]
Hi,

Regarding your first issue, you're doing everything right. On your `matplotlib` plot, it's just the display along the Z-axis that is stretched. I you're not happy with the results, I suggest you pull the latest master and recompute SfM as we did quite some changes recently that seems to improves robustness.

Regarding your second question, so far, we don't support (yet !) global-sfm like method, only incremental ones.

For your last issue, you can let `retriangulation_ratio`  and `bundle_new_points_ratio` to dummy value (`99999`), but I suggest you set `bundle_interval` to some reasonable value like `10` or `20` images. 

Let me know if that improves.

Yann
