### ISSUE TITLE
Orthomosiac Generation

### ISSUE THREAD

**Issue by nickponline** [mapillary/OpenSfM#43]
Hi there, 

I'm considering adding functionality to OpenSfm to create an orthophoto as it doesn't look like this exists. I was wondering if that would be useful? If there is a partial work I'm happy to build of that or take direction on a suggested approach?

Regards, 

Nick

**Comment by waps101** [comment]
Hi Nick,

This is something I would be very interested in and pleased to see added to OpenSfM.

Cheers,

Will

**Comment by nickponline** [comment]
Hi Will, 

Is there anything I can build off to get started or a preferred approach?

Nick

**Comment by paulinus** [comment]
Hi Nick and Will,

OpenSfM does not compute orthophotos on its own, but can be used as a part of the process.

The typical approach to create orthophotos is
 1. Compute the camera positons (OpenSfM does this part)
 2. Compute depth maps or dense point clouds
 3. Compute a mesh and texture it using the images
 4. Take a picture (the orthophoto) of that mesh

https://github.com/OpenDroneMap/OpenDroneMap is a project that installs and runs the required software for all of the process. The `python-port` branch has the option to use OpenSfM for computing the camera positions.

**Comment by nickponline** [comment]
Does this branch generate the orthophoto using Python? If it does it might
be a good starting point.

**Comment by paulinus** [comment]
It generates the orthophoto using a C++ code (https://github.com/OpenDroneMap/OpenDroneMap/tree/python-port/odm_orthophoto).  Python there refers only to the `run.py` script with is the one in charge of running the required tools for each of the processes

**Comment by nickponline** [comment]
Then Would it make sense to just port the cpp implementation to Python and
integrate into osfm?

**Comment by paulinus** [comment]
super late answer here: that would be more complex than just using ODM directly. I don't think is a good plan. I would rather help improving ODM on that side.
