### ISSUE TITLE
[Possible Regression Bug] optimize_camera_parameters is not being respected?

### ISSUE THREAD

**Issue by pierotofy** [mapillary/OpenSfM#431]
If a person sets `optimize_camera_parameters: no` in `config.yml`, it seems as the camera internals are still being optimized during BA.

Comparing previous versions of OpenSfM, it looks as if the `constant` variable is no longer taken into consideration when adding cameras?

https://github.com/mapillary/OpenSfM/blob/master/opensfm/src/bundle/src/bundle_adjuster.cc#L540

vs.

https://github.com/mapillary/OpenSfM/blob/b67c337f490a86ba1bb008dd740a66284a17aadc/opensfm/src/bundle.h#L1180

**Comment by YanNoun** [comment]
Hi,

You right, we broke it in a series of two PRs over last month. I'm fixing it now, sorry for the regression.

Yann

**Comment by YanNoun** [comment]
@pierotofy fixed here : https://github.com/mapillary/OpenSfM/commit/06940c3bf5bb7154bcb969f3580aba6cebb920af
