### ISSUE TITLE
Scale of reconstruction is off when no GPS information is available (but GCP is)

### ISSUE THREAD

**Issue by pierotofy** [mapillary/OpenSfM#435]
Hello :hand:

While trying to process a set of images flown from a kite with no GPS information but with a corresponding GCP file I've noticed that the output reconstruction is in miniature size.

I think this is normal in absence of georeferencing information (no GPS, no GCP), but the GCP has some information about distances, so it might be possible to use it to set a proper scale?

To reproduce:

 - Use the images in https://github.com/OpenDroneMap/odm_data_copr
 - Use the following `gcp_list.txt` file:

```
WGS84 UTM 11N
235277.61	3811190.36	0	3483.00	729.00	IMG_0031.jpg
235281.01	3811195.14	0	731.00	1017.00	IMG_0031.jpg
235269.88	3811198.11	0	3608.00	2292.00	IMG_0037.jpg
235269.88	3811198.11	0	586.00	1028.00	IMG_0121.jpg
235269.89	3811203.16	0	2040.00	1017.00	IMG_0046.jpg
235262.54	3811203.50	0	3472.00	1002.00	IMG_0052.jpg
235264.49	3811213.70	0	1472.00	1110.00	IMG_0067.jpg
235258.91	3811213.60	0	3910.00	916.00	IMG_0073.jpg
235257.74	3811222.65	0	2020.00	2148.00	IMG_0073.jpg
235246.25	3811220.60	0	3570.00	2593.00	IMG_0082.jpg
235246.25	3811220.60	0	3564.00	1929.00	IMG_0085.jpg
235246.25	3811220.60	0	3407.00	995.00	IMG_0088.jpg
235248.03	3811227.25	0	1082.00	764.00	IMG_0091.jpg
```

And this `config.yaml`:

```
align_method: naive
bundle_use_gcp: true
bundle_use_gps: false
feature_min_frames: 8000
feature_process_size: 2048
matching_gps_distance: 0
matching_gps_neighbors: 8
optimize_camera_parameters: true
processes: 4
```

After the `reconstruction` and `export_ply` command the resulting PLY looks like:

![image](https://user-images.githubusercontent.com/1951843/59969476-88020480-951b-11e9-99ae-364a38be5dc5.png)

The reconstruction actually looks great, it's just the scale that is off.

![image](https://user-images.githubusercontent.com/1951843/59969482-e9c26e80-951b-11e9-9aaf-e23198044376.png)

(Distance reads about ~5 meters)

I thought it might have been a local vs. world coordinates fault on my end, so I ran `export_geocoords odm_data_copr/opensfm --proj "+proj=utm +zone=11 +ellps=WGS84 +datum=WGS84 +units=m +no_defs" --reconstruction` and received:

```
Traceback (most recent call last):
  File "/code/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/code/SuperBuild/src/opensfm/opensfm/commands/export_geocoords.py", line 77, in run
    self._transform_reconstruction(r, transformation)
  File "/code/SuperBuild/src/opensfm/opensfm/commands/export_geocoords.py", line 138, in _transform_reconstruction
    shot.pose.set_rotation_matrix(np.dot(R, A1))
  File "/code/SuperBuild/src/opensfm/opensfm/types.py", line 85, in set_rotation_matrix
    raise ValueError("Determinant not 1")
ValueError: Determinant not 1
``` 

(which might a different problem)

So I exported the transform with `export_geocoords odm_data_copr/opensfm --proj "+proj=utm +zone=11 +ellps=WGS84 +datum=WGS84 +units=m +no_defs" --transformation` and the scale values seem like they wouldn't be affected by it:

```
1.0000598981278017 0.028431922721210867 0.0 235262.68351039622
-0.02843192033469677 1.0000599017366767 0.0 3811208.6790932035
7.82310962677002e-08 7.82310962677002e-08 0.9999999990686774 9.313225746154785e-10
0.0 0.0 0.0 1.0
```

I think this has been a problem in earlier version of OpenSfM (~1 year ago) as well.

![image](https://user-images.githubusercontent.com/1951843/59969480-b2ec5880-951b-11e9-9c3b-4a5ccf642b47.png)

(Distance reads about ~143 meters)

Whereas the actual distance should be roughly 60-65 meters. 

![image](https://user-images.githubusercontent.com/1951843/59969509-897ffc80-951c-11e9-958c-9a87ce9cff4c.png)

I've tried to change `align_method` to `orientation_prior` and `align_orientation_prior` to `vertical` (but I'm pretty sure that skips the GCP alignment code), without success. 

Looking for some pointers in the areas of the code that I should be focusing my attention to, or if this is a known limitation and/or possible ideas on how to fix it?

Thank you in advance.

**Comment by YanNoun** [comment]
Hi,

Running with current `master`, I end up with the same `ValueError: Determinant not 1` as you had. This is because there is no EXIF in shots so a [0, 0, 0] value is used for all shots.

I rebased the branch `feat-gcp-align` on master we made last time for propagating use of GPS. Using it as is, I had slightly better results. After a couple of commits for generating proper topocentric frame, results are OK.

Made a PR here for `feat-gcp-align`, so we can push this when @paulinus is back . There is might be some discussion about `use_gcp`/`use_gps` and `align` behaviour, your input might be welcome. 

For the `align` step, I'm curious of any registration any behaviour it would change (two last commits `42cd57c` and `f28f97a`)

Yann

**Comment by pierotofy** [comment]
Thanks @YanNoun !! :clinking_glasses: 

This is great. I will check the new branch changes in the next few days and re-run our test suite to compare results. 

I think a person needs to be part of the organization (mapillary) to be added as a reviewer in PRs. It's a limitation of GitHub (I don't know why they don't let external contributors be reviewers).

**Comment by pierotofy** [comment]
This is now fixed! :clinking_glasses:
