### ISSUE TITLE
How to calculate the camera position from rotation and translation fields

### ISSUE THREAD

**Issue by morioka7** [mapillary/OpenSfM#445]
I have trouble to calculate the camera position (x,y,z) from rotation and translation fields of each shots in reconstruction.json.
Are there any function in python files?

**Comment by YanNoun** [comment]
Hello,

You can load a reconstruction using `rec = opensfm.io.reconstruction_from_json`. Then running over the `shots` of `rec`, calling `shot.pose.get_origin()` will give you the shot position. You can get its 3x3 rotation matrix by calling `shot.pose.get_rotation_matrix()`.

Let me know if that helps.

Yann

**Comment by Matesanz** [comment]
It would be great to add this kind of info to the docs.
May I can help? (I've never done something like this before)

**Comment by Matesanz** [comment]
My proposition still stands.
A related question : What's the difference between taking the **camera position** from `pose.get_origin()` and `pose.translation` ?

Nice regards.

**Comment by marc-micatka** [comment]
As someone who just spent a while looking at the source to understand how to actually do this (as the documentation seems non-existent still?) here's a bit of a step-by-step, apologize for the hand-holding if this is more obvious to others!

```
from opensfm import io
import json

rec_file = "path/to/reconstruction.json"

with open(rec_file, 'r') as f:
    data = json.load(f)[0]
rec = io.reconstruction_from_json(data)

for shot in rec.shots.values():
   # shots.values() seems to get you what you need...
    r = shots.pose.rotation
    t - shots.pose.translation
    r_matrix = shots.pose.get_rotation_matrix()
    t_matrix = shots.pose.get_translation_matrix()
```
