### ISSUE TITLE
'BrownPerspectiveCamera' object has no attribute 'focal'

### ISSUE THREAD

**Issue by gohai** [mapillary/OpenSfM#447]
I am using OpenSfM as part of OpenDroneMap - there, running the reconstruction fails for me when I try to use a Brown-Conrady camera model, with the following output:

```
  File "/code/SuperBuild/src/opensfm/bin/export_bundler", line 48, in <module>
    io.export_bundler(images, reconstructions, track_graph, bundle_file_path, list_file_path)
  File "/code/SuperBuild/src/opensfm/opensfm/io.py", line 703, in export_bundler
    focal = camera.focal * scale
AttributeError: 'BrownPerspectiveCamera' object has no attribute 'focal'
```

I have seen this error message mentioned before in a bug that was solved: https://github.com/mapillary/OpenSfM/issues/259

For reference, this is the `cameras.json` file that I am feeding to ODM. (Note: there are probably a few superfluous properties set, and ODM might also do some type of massaging before passing it on to OpenSfM.)

```
{
    "dji fc2204 4000 3000 perspective 0.6666": {
        "projection_type": "brown", 
        "width": 4000, 
        "height": 3000, 
        "c_x": 0.492639, 
        "c_x_prior": 0.492639, 
        "c_y": 0.503773, 
        "c_y_prior": 0.503773, 
        "k1": -0.040661, 
        "k1_prior": -0.040661, 
        "k2": 0.104878, 
        "k2_prior": 0.104878, 
        "k3": -0.095506, 
        "k3_prior": -0.095506, 
        "p1": 0.000122, 
        "p1_prior": 0.000122, 
        "p2": 0.000276, 
        "p2_prior": 0.000276, 
        "focal": 0.721327, 
        "focal_prior": 0.721327, 
        "focal_x": 0.721327, 
        "focal_x_prior": 0.721327, 
        "focal_y": 0.721327, 
        "focal_y_prior": 0.721327
    }
}
```

**Comment by YanNoun** [comment]
Hello,

Bundler export doesn't support full Brown-Conrady model (skew ratio + 3 radial + 2 tangential). 

I pushed a fix though but beware that any further process that will use the Bundler export (I'm summonning @pierotofy here) will not be optimal reprojection-wise, as we can't export the full model.

Yann

**Comment by pierotofy** [comment]
Thanks @YanNoun ! Correct, that's a limitation of the bundler format (although some output is better than no output?). Thanks for the fix!
