### ISSUE TITLE
Shots origins collapse into one point

### ISSUE THREAD

**Issue by arbel0s** [mapillary/OpenSfM#448]
Hello!

Sometimes during the reconstruction process origins of some random shots collapse into one point. Keypoints of these shots are also reconstructed at the same point – their common origin.

On the reconstruction it looks like this:
![image](https://user-images.githubusercontent.com/25365183/61793105-fb52ab00-ae26-11e9-89dd-9f942a185ecf.png)

I've tried to patch [remove_outliers](https://github.com/mapillary/OpenSfM/blob/645fc2e7e297ed71558916112832a2c6f306fc9b/opensfm/reconstruction.py#L1067) function to filter out those points that were reconstructed near its shot origin, but it didn't work out.

Have you faced such a problem before? Do you have any ideas on how to overcome this issue?

**Comment by YanNoun** [comment]
Hello,

Can you consistently reproduce the issue ? Could you share a dataset where it happens ?

Thank you,

Yann
