### ISSUE TITLE
Crash on call to "sorted" in python3

### ISSUE THREAD

**Issue by nbubis** [mapillary/OpenSfM#450]
Line 210 `pairs_selection.py` fails under python 3. It should read:
`pairs = set([tuple(sorted([i, j])) for i in images_ref for j in images_cand])`
(note the added square braces in the `sorted` command.

**Comment by YanNoun** [comment]
Hello,

Tanks for reporting. The issue has been fixed 4 days ago, please pull latest master.

Yann
