### ISSUE TITLE
How to reduce number of points in merged.ply?

### ISSUE THREAD

**Issue by morioka7** [mapillary/OpenSfM#451]
I have problem too much points in merged.ply. Opensfm by using 200 jpegs created marged.ply of 1GB size. I would like to reduce number of points in marged.ply.
Let me know how to modify parameters of config.py.
Thank you.

**Comment by YanNoun** [comment]
Hi,

You can generate less point by settings a lower number for `depthmap_resolution` in `config.py`. 640 is the default.

Hope that helps,

Yann
