### ISSUE TITLE
Can unknown focal length  work ? 

### ISSUE THREAD

**Issue by shuluoshu** [mapillary/OpenSfM#457]
Hello,  @peterneubauer @kolen @kant 
 Nice work !
   here I have some pictures and don't have the EXIF information(not captured by phones), how can I use your OpenSFM to get  relative 3d points and R, T ?  Thanks so much! 

I don't need the actual  distance, but need the reconstructed result.

**Comment by paulinus** [comment]
You can put your images in a folder named `/some/path/images` and run `bin/opensfm_run_all /some/path`. It will run the reconstruction algorithm even if the images don't have EXIF information. See https://www.opensfm.org/docs/using.html
