### ISSUE TITLE
Pixel bearing function is slow

### ISSUE THREAD

**Issue by paulinus** [mapillary/OpenSfM#46]
Since the use of OpenGV for geometric solvers, we are converting very often from pixel position to pixel bearings. The current implementation of that conversion (https://github.com/mapillary/OpenSfM/blob/master/opensfm/multiview.py#L422) is pretty slow.

The main reason is that it is extracting the camera parameters from the dictionary for each pixel.

This could be speed up by creating a camera class that stores this parameters and has a `pixel_bearing` method. The class could implemented in C++ if needed.

**Comment by YanNoun** [comment]
Since, we now have C++ camera classes (https://github.com/mapillary/OpenSfM/pull/594), I'm closing.
