### ISSUE TITLE
Can I give a rough focal length and let the openSfM  refine the pose as well as the camera intrinsics? 

### ISSUE THREAD

**Issue by shuluoshu** [mapillary/OpenSfM#468]
Hi, @peterneubauer  @kolen @kant @angelday @ktuite 
  If I don't have the focal length and principle points, can I just give a roughly estimated focal length, for example, 1000, in the SfM pipeline and then, can the pipeline refine the intrinsics as well as the poses at the same time?  

Thanks so much!

**Comment by paulinus** [comment]
yes, you can provide your own estimate of the focal length. It will be used as initialization and later refined during bundle adjustment.

You can follow the steps here to provide your estimate https://www.opensfm.org/docs/using.html#providing-your-own-camera-parameters

Note that the focal length is normalized. That is you need to divide your estimate by the width of the image (or the height, whichever is larger)
