### ISSUE TITLE
where i can find sweden project 3d navigation?

### ISSUE THREAD

**Issue by Arshiamidos** [mapillary/OpenSfM#470]

**Comment by YanNoun** [comment]
Hi,

Can you elaborate and explain a bit more ?

Yann

**Comment by Arshiamidos** [comment]
https://blog.mapillary.com/update/2014/12/15/sfm-preview.html
   the thrid 3dmap item in page

**Comment by paulinus** [comment]
That reconstruction was build from Mapillary images in [this area](https://www.mapillary.com/app/?lat=55.61087217&lng=12.99471815&z=17&pKey=NY3gHAi7rLlBlt9oZtbnGg)
You can use OpenSfM to build such reconstruction using those images or any others.
OpenSfM itself does not include those images.
