### ISSUE TITLE
fix pose of shot

### ISSUE THREAD

**Issue by coderzbx** [mapillary/OpenSfM#471]
Is there anyone know how to set the pose of shot as a constant?
I thought i resolve this problem by doing these below:
First, I add ervery shot at opensfm/reconstruction.py: Line685, Function:bootstrap_reconstruction.
I save matrix R and matrix T at metadata of shot.

    shot1 = types.Shot()
    shot1.id = im1
    shot1.camera = camera1
    shot1.metadata = get_image_metadata(data, im1)
    r_matrix = shot1.metadata.r_matrix
    shot1.pose = types.Pose()
    shot1.pose.set_rotation_matrix(r_matrix, permissive=True)
    shot1.pose.set_origin(shot1.metadata.gps_position)
    reconstruction.add_shot(shot1)

    shot2 = types.Shot()
    shot2.id = im2
    shot2.camera = camera2
    shot2.metadata = get_image_metadata(data, im2)
    r_matrix = shot2.metadata.r_matrix
    shot2.pose = types.Pose()
    shot2.pose.set_rotation_matrix(r_matrix, permissive=True)
    shot2.pose.set_origin(shot2.metadata.gps_position)
    reconstruction.add_shot(shot2)

and at opensfm/reconstruction.py:Line 320, Function: resect

    if ninliers >= min_inliers:
        # R = T[:, :3].T
        # t = -R.dot(T[:, 3])
        shot = types.Shot()
        shot.id = shot_id
        shot.camera = camera
        r_matrix = metadata.r_matrix
        shot.pose = types.Pose()
        shot.pose.set_rotation_matrix(r_matrix, permissive=True)
        shot.pose.set_origin(metadata.gps_position)
        shot.metadata = metadata
        reconstruction.add_shot(shot)

at opensfm/reconstruction.py:Line 320, Function:bundle_local

    for shot_id in interior | boundary:
        shot = reconstruction.shots[shot_id]
        r = shot.pose.rotation
        t = shot.pose.translation
        ba.add_shot(shot.id, shot.camera.id, r, t, True)

and at opensfm/reconstruction.py: Line 166, Function: bundle

    for shot in reconstruction.shots.values():
        r = shot.pose.rotation
        t = shot.pose.translation
        ba.add_shot(shot.id, shot.camera.id, r, t, True)

and at opensfm/reconstruction.py: Line251, Function:bundle_single_view

    ba = csfm.BundleAdjuster()
    shot = reconstruction.shots[shot_id]
    camera = shot.camera
    _add_camera_to_bundle(ba, camera, constant=True)

    r = shot.pose.rotation
    t = shot.pose.translation
    ba.add_shot(shot.id, camera.id, r, t, True)

But, it didn't work! The pose of every shot has been changed by BA.

**Comment by YanNoun** [comment]
Hi,

What you're doing seems correct. Are you sure that the `r_matrix` field that you added contains the correct data ?

Yann

**Comment by coderzbx** [comment]
> Hi,
> 
> What you're doing seems correct. Are you sure that the `r_matrix` field that you added contains the correct data ?
> 
> Yann

Thank  you for your answer.
My Matrix R is from my IMU device, it's very expensive and accurate. It is an unit matrix.
So, I want to set this matrix as a constant, then I change the GPS coordinates to TopoCentric Coordinate using dataset.reference() as Matrix C.
Then, we get Matrix T=(-R).dot(C)
and shot.set_origin(C), shot.set_rotation_matrix(R).
But, eventually, my pose has been changed or optimized by BA modules.
PS: using code from master branch

**Comment by coderzbx** [comment]
> Hi,
> 
> What you're doing seems correct. Are you sure that the `r_matrix` field that you added contains the correct data ?
> 
> Yann

Here is my testing data:
before OpenSfM:
Matrix R:
[[
0.9998643549294332,
0.017450688901414352,
0.0003507644906930118
],[
0.006065618905126866,
-0.32855433077492197,
-0.9444675029738022
],[
-0.0163663633793922,
0.944341518216439,
-0.3286046451143123
]]
Matrix C:
[
116.48473501353,
39.97273942547,
27.5099
]
Matrix T:
[
-117.17613576974283,
38.408871200377874,
-26.801605008304584
]

After OpenSfM:
Matrix R:
[[
0.9998471444778623,
0.017460228631862848,
0.0009099975758626337
],[
0.006737239078087074,
-0.3367296235045499,
-0.9415772779034596
],[
-0.016133731405651188,
0.9414394834882417,
-0.33679578625678075
]]
Matrix C:
[
116.4847350125867,
39.97273942884111,
27.321191657334566
]
Matrix T:
[
-117.18972506524258,
38.40023325938352,
-26.550919508242526
]

Obviously, they are changed.

**Comment by coderzbx** [comment]
pose are changed in align_reconstruction during reconstruction
