### ISSUE TITLE
is there any method to get points/faces/vertices by click in webgl html?

### ISSUE THREAD

**Issue by Arshiamidos** [mapillary/OpenSfM#474]

**Comment by paulinus** [comment]
The viewer uses three.js' raycaster to let you click on the cameras. Maybe that can help you get started with what you want?
https://github.com/mapillary/OpenSfM/blob/master/viewer/reconstruction.html#L1350-L1351

**Comment by Arshiamidos** [comment]
@paulinus ,do you accept PR for clicking on points_clouds and calculating distance on active camera? (with button on dat.gui.js)

**Comment by paulinus** [comment]
While selecting points would be a useful functionality, we should be careful in adding functionality to the current viewer. It is meant to be a simple viewer, and the current structure of the code is not ready to grow much without becoming unmaintainable.
If you can add this functionality without making the code grow much we can merge it.

**Comment by Arshiamidos** [comment]
got it
