### ISSUE TITLE
How to mapping object in 2D image to point cloud group in marged.ply

### ISSUE THREAD

**Issue by morioka7** [mapillary/OpenSfM#486]
I would like to mapping object in 2D image to point cloud group in marged.ply.
For example, in case of a small box is appeared in 2D image, which is source file of openSFM.
I would like to extract dense point group corresponding to that small box from all point cloud of marged.ply

Is it possible in openSFM?
Thank you for your cooperation.

Ps) Other tools such as Metashape has these mapping function.

**Comment by YanNoun** [comment]
Hi,

You will need to write to write some custom to do this. From your bounding-box, you can get the corresponding bearings, and thus the camera frustrum (you also need to define some depth boundaries). Then you will need to intersect the frustrum with the point cloud.

Hope that helps,

Yann

**Comment by YanNoun** [comment]
No answer in a while, closing.
