### ISSUE TITLE
How to review & assess openSfM results

### ISSUE THREAD

**Issue by SwiftGust** [mapillary/OpenSfM#492]
Hello,

I'd like to know how to review & assess openSfM result to see how it is accurate but got no clue so far.
Especially when processed with GCPs, how can I assess it is well aligned or assess accuracy of the results?

And also the viewer(viewer/reconstruction.html) cannot get relative path of image shot files, 
no thumbnails are visible with having directory '/images' under reconstruction.json (or am I using wrong?)

Plus when generating GCP lists file, pixel locations should be retrieved from raw, distorted image or is there way to get undistorted image prior?

Thank you in advance.

**Comment by YanNoun** [comment]
Hi @SwiftGust , you can now use the quality report command of OpenSfM (`opensfm compute_statistics DATASET && opensfm export_report DATASET`), to assess the quality of the reconstruction.

**Comment by SwiftGust** [comment]
@YanNoun Hi, sorry for late reply.
I also can see the documentation https://www.opensfm.org/docs/reporting.html
Thank you for adding the feature!
