### ISSUE TITLE
No 'reprojection_error' field in reconstruction.json

### ISSUE THREAD

**Issue by thuliu-yt16** [mapillary/OpenSfM#493]
I am running opensfm on my own images. I want to reconstruct the scene and get the reprojection error. 
So I run 
```bash
bin/opensfm_run_all data/MY_DATASET/images
```
However, there is no reprojection_error field under points in reconstruction.json when I check the output format.
It seems like this
```json
// I omit where seems correct
[
    {
        "cameras" : ...  ,
         "shots":  ... ,
          
         "points": {
                 "9019": {
                           "color":  ... ,
                           "coordinates": ... ,
                  },
                  "9512": ...
           } 
    }
]

```

**Comment by paulinus** [comment]
That looks correct, @thuliu-yt16. We do not store the reprojection error of points in `reconstruction.json`.

**Comment by thuliu-yt16** [comment]
But according to the section 'Reconstruction file format' of the opensfm document (https://opensfm.readthedocs.io/en/latest/dataset.html#reconstruction-file-format),
points in `reconstruction.json` should contain the reprojection error. 
Or is the document outdated? 
Anyway, i want to know the error and could you tell me where i can find it?

**Comment by nchamo** [comment]
Hey @paulinus !

Same question from me :)

Is the reprojection error reported somewhere?

Thanks!

**Comment by thuliu-yt16** [comment]
In fact, i succeed to report the reprojection error by changing opensfm code. @nchamo 

You can find `class Point` in `opensfm.types` which contains the field `reprojection_errors` but module `opensfm.io`, which is imported by `opensfm.dataset` to output `reconstruction.json`, ignores this field. Actually, type of `reprojection_errors` is dict{str: numpy.ndarray}. So i guess the reason why it is ignored is that a numpy.ndarray cannot be dump by json. So i change the code in `opensfm/io.py`. 

```python
# start from line 298
def point_to_json(point):
    """
    Write a point to a json object
    """
    # new add 
    reprojection_errors_list_format = {}
    for k, v in point.reprojection_errors.items():
        reprojection_errors_list_format[k] = list(v)

    return {
        'color': list(point.color),
        'coordinates': list(point.coordinates),
        'reprojection_errors': reprojection_errors_list_format, # new add
    }
```
Another possible solution is to write a custom json encoder to support numpy.ndarray. I haven't tried it but i guess it will work. You can find solution here: https://stackoverflow.com/questions/26646362/numpy-array-is-not-json-serializable

**Comment by nchamo** [comment]
Hey @thuliu-yt16 !

Thanks for the idea, I'll try it and see what happens. 

Did you consider adding merging your changes to OpenSfM?

**Comment by YanNoun** [comment]
Hi,

We thought about this a lot. The reason for not implementing it is that it would make the reconstruction JSON much much bigger, and this information is super cheap to compute.

Yann

**Comment by santelelle** [comment]
What about a single valued "mean reprojection error"? It would be really nice in order to compare results obtained with different parameters
