### ISSUE TITLE
problen running -ti mapillary/opensfm /bin/sh -c "bin/run_all data/berlin"

### ISSUE THREAD

**Issue by mlm74** [mapillary/OpenSfM#496]
Hi,
I am getting started in opensfm and I have encountered this problem: After building the docker image using

cd path/to/OpenSfM
docker build -t mapillary/opensfm .

I tryed to create the reconstruction using

docker run -ti mapillary/opensfm /bin/sh -c "bin/opensfm_run_all data/berlin"

but I got:
 bin/opensfm_run_all: line 10: python: command not found

Thanks in advance.

**Comment by paulinus** [comment]
I switched the default docker image to python3 but the run_all script is trying to run python 2. Will move default to python3. In the meantime, you can run it with python3 as the last argument
```docker run -ti mapillary/opensfm /bin/sh -c "bin/opensfm_run_all data/berlin python3```

**Comment by mlm74** [comment]
Solved. Thanks...
