### ISSUE TITLE
Error building OpenSfM 

### ISSUE THREAD

**Issue by mlm74** [mapillary/OpenSfM#498]
Hi,
After installing all dependencies on Ubuntu with docker using

docker build –t mapillary/opensfm .  

I'm trying to build OpenSfm using 

sudo apt-get install python3-setuptools
sudo apt-get install python3-wheel
python3 setup.py build

but i got this error:

Configuring for python 3.6...
Traceback (most recent call last):
  File "setup.py", line 48, in <module>
    configure_c_extension()
  File "setup.py", line 39, in configure_c_extension
    subprocess.check_call(cmake_command, cwd='cmake_build')
  File "/usr/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'

Thanks in advance,

Manuel

**Comment by yurenpang** [comment]
I have the same exact problem. Did you manage to solve it?

**Comment by mlm74** [comment]
No. Sorry




Obtener Outlook para Android







On Wed, Apr 22, 2020 at 5:54 AM +0200, "yurenpang" <notifications@github.com> wrote:















I have the same exact problem. Did you manage to solve it?

**Comment by BrianG13** [comment]
Encounter exactly the same problem.
Popping

**Comment by YanNoun** [comment]
@BrianG13 @mlm74 make sure you have CMake installed.

**Comment by xuzhuang1996** [comment]
hello！I has installed cmake,and I occurred this :
CMake Error at CMakeLists.txt:3 (project):
  Running

   'nmake' '-?'

  failed with:

   绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?

-- Configuring incomplete, errors occurred!
See also "C:/Users/x00574457/Desktop/md/OpenSfM/cmake_build/CMakeFiles/CMakeOutput.log".
Configuring for python 3.8...
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    configure_c_extension()
  File "setup.py", line 43, in configure_c_extension
    subprocess.check_call(cmake_command, cwd="cmake_build")
  File "C:\Users\x00574457\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '../opensfm/src', '-DPYTHON_EXECUTABLE=C:\\Users\\x00574457\\AppData\\Local\\Programs\\Python\\Python38\\python.exe', '-DVCPKG_TARGET_TRIPLET=x64-windows', '-DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake']' returned non-zero exit status 1.
==========================================
 Did you occurred this?
