### ISSUE TITLE
Locating features coordinate on the point cloud result

### ISSUE THREAD

**Issue by ChayaninSuatap** [mapillary/OpenSfM#501]
Is there any way to locate the position of features (for example, extracted using HAHOG) of the input images on the position of the point cloud result?

Now I am able to get the feature position ( x and y ) of an image in files of folder "features".

I studied the source code a bit. In the reconstruction part, I was looking for something like "this point x,y,z on the point cloud is from the feature id xxxx of the input image xxxx". But can't seem to find something like that. 

I look at reconstruction.json but don't find what I look for.

I know the distance and position of the real-world scene. My problem is I want to reference some of the real-world points to the point cloud point so that I can use them the scale and rotate point cloud properly. Is there any suggestion? # #

**Comment by paulinus** [comment]
The correspondence information between images, features and 3d points (or tracks) is stored in the tracks graph.
You can load them like this
```
from opensfm import dataset
data = dataset.DataSet('data/berlin')
graph = data.load_tracks_graph()
track_id = '0'
image_id = '01.jpg'
graph[track_id]   # all images that see track_id
graph[image_id]   # all points seen by image_id
graph[track_id][image_id]   # edge connecting point and image contains the 2d feature data
```

**Comment by ChayaninSuatap** [comment]
Thank you very much!

**Comment by abmmusa** [comment]
I see load_track_graph() is gone in the latest git repo. Can you please let me know how to access this now?
