### ISSUE TITLE
How to use segmentation function of OpenSfM

### ISSUE THREAD

**Issue by morioka7** [mapillary/OpenSfM#509]
Hello

I would like to use segmentation function of OpenSfM, which is described in “Denser 3D Point Clouds in OpenSfM”
https://blog.mapillary.com/update/2016/10/31/denser-3d-point-clouds-in-opensfm.html

I know the input segmentation image is grayscale image. But I don't know how to define segmentation labels for each segmented pixel.

Does anyone show me a sample of segmentation image and labels

Thank you.

-Morioka

**Comment by baihaozi12** [comment]
and how to map the segmentation result to the point cloud?

**Comment by YanNoun** [comment]
See https://github.com/mapillary/OpenSfM/issues/506#issuecomment-799298879
