### ISSUE TITLE
make opengv fail

### ISSUE THREAD

**Issue by geosky** [mapillary/OpenSfM#51]
Scanning dependencies of target opengv
[  0%] Building CXX object CMakeFiles/opengv.dir/src/absolute_pose/modules/main.o
/source/opengv/src/absolute_pose/modules/main.cpp: In function ‘void opengv::absolute_pose::modules::upnp_main_sym(const Eigen::Matrix<double, 10, 10>&, const Eigen::Matrix<double, 1, 10>&, double, std::vector<std::pair<double, Eigen::Matrix<double, 4, 1> >, Eigen::aligned_allocator<std::pair<double, Eigen::Matrix<double, 4, 1> > > >&)’:
/source/opengv/src/absolute_pose/modules/main.cpp:800:10: warning: unused variable ‘imagThreshold’ [-Wunused-variable]
   double imagThreshold = 0.01;
          ^
/source/opengv/src/absolute_pose/modules/main.cpp:803:43: warning: variable ‘D’ set but not used [-Wunused-but-set-variable]
   Eigen::Matrix<std::complex<double>,8,1> D = Eig.eigenvalues();
                                           ^
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/opengv.dir/src/absolute_pose/modules/main.o] Error 4
make[1]: *** [CMakeFiles/opengv.dir/all] Error 2
make: *** [all] Error 2

**Comment by paulinus** [comment]
The error looks like a gcc bug. What OS is that on?

**Comment by geosky** [comment]
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

**Comment by paulinus** [comment]
Did you solve the problem @geosky?  i'm sorry i could not reproduce.

**Comment by geosky** [comment]
Nope. Just disappear when I tried on another computer. perhaps you're right, some internal bugs of gcc or the dev-environment caused the error. not much related with the opengv lib, i think.
