### ISSUE TITLE
Getting image parse error - EXIF metadata extraction process Open SFM

### ISSUE THREAD

**Issue by amak19** [mapillary/OpenSfM#510]
I am getting this below error when I try to extract the metadata from the images:

Can anyone please help to get the solution to this problem?

Traceback (most recent call last):
OpenSfM/opensfm/commands/extract_metadata.py", line 35, in run
    d = self._extract_exif(image, data)
OpenSfM/opensfm/commands/extract_metadata.py", line 64, in _extract_exif
    d = exif.extract_exif_from_file(data.open_image_file(image))
OpenSfM/opensfm/exif.py", line 93, in extract_exif_from_file
    exif_data = EXIF(fileobj)
OpenSfM/opensfm/exif.py", line 133, in __init__
    self.xmp = get_xmp(fileobj)
OpenSfM/opensfm/exif.py", line 108, in get_xmp
    xdict = x2d.parse(xmp_str)
  File "/usr/local/lib/python3.7/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 150

Thank you!

**Comment by GITNE** [comment]
> xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 150

Your image's XMP meta data is malformed. Try rectifying it or remove it from the images before processing.

**Comment by amak19** [comment]
> > xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 150
> 
> Your image's XMP meta data is malformed. Try rectifying it or remove it from the images before processing.

Hello,
Thank you so much for your reply.
The images I am using are standard DJI drone camera images. How can I remove the metadata as I am using extract metadata command first.

I am new to using OpenSFM so please bear with my understanding! Thank you.

Regards,
Amar

**Comment by GITNE** [comment]
> How can I remove the metadata as I am using extract metadata command first.

Since this goes beyond the scope of OpenSfM, I am not going to comment much on this. Basically, you can use any application which enables you to modify Exif meta data. My tool of choice is [`exiv2`](https://www.exiv2.org) which could be considered as the Swiss army knife of Exif data manipulation, but many other applications can get this job done too.

**Comment by amak19** [comment]
Since the xml metadata  - <x:xmpmeta is malformed, I removed the nextline tag '\n' from the metadata by modifying the get_xmp(fileobj) method in the exif.py file. 

@paulinus So it is something that you plan to include in the exif.py code, to first check the validity of the xmp_str before parsing it using xmltodict library.

Thank you!

**Comment by GITNE** [comment]
@amak19 Just out of curiosity, could you please post a dump of the XMP meta data or a raw image for examination?

**Comment by oradzhabov** [comment]
I've faced with this issue after OpenSFM has been built for Windows.
Adding one line in exif.py fixed this problem for me:

```
        xmp_str = img_str[xmp_start:xmp_end + 12]
        xmp_str = xmp_str.replace(r'\n', ' ')
```

**Comment by paulinus** [comment]
We often see images with escaped strings XMP which breaks the parser. I've added an exception catch which tries unescaping the string if parsing fails https://github.com/mapillary/OpenSfM/commit/63239a63b485de078eab6c0f5c89439483e15083 . This fixes the most common cause for this issue.
