### ISSUE TITLE
How to set cx_prior and cy_prior

### ISSUE THREAD

**Issue by gaosanyuan** [mapillary/OpenSfM#514]
When using Brown perspective camera model, how to set c_x_prior and c_y_prior?
What's the relationship between "*" and "*_prior"? such as focal_x, focal_y, c_x, c_y, k1, k2, p1, p2, p3?
Now my camera has been calibrated, and the intrinsic parameters and distortion parameters are known.
Thanks

**Comment by pierotofy** [comment]
On setting the _prior values, see https://www.opensfm.org/docs/using.html#providing-your-own-camera-parameters

the _prior values are the "starting" estimates of the camera upon which OpenSfM starts optimizing.
