### ISSUE TITLE
If opensfm supports Local Cartesian coordinate system

### ISSUE THREAD

**Issue by gaosanyuan** [mapillary/OpenSfM#515]
I want to set the pos of a shot to be const, how to select the coordinate system; if the position of a shot is set as latitude, longitude, altitude, how to set its pose information.

**Comment by YanNoun** [comment]
Hi,

We currently support `WGS84` and thus lat/lon/alt as input information in the `.exif` file.

Let me know if that helps.

Yann

**Comment by YanNoun** [comment]
No answer in a while, closing.
