### ISSUE TITLE
Bug in export_openmvs.py

### ISSUE THREAD

**Issue by Luke192** [mapillary/OpenSfM#519]
The export function references "udata" before it is defined. Did you mean to pass udata in as an argument?

**Comment by Bilal-Arshad** [comment]
@Luke192 did you manage to solve this issue.

**Comment by Luke192** [comment]
I just worked around it by making a temporary edit to pass udata in as an argument, which seemed to work.

**Comment by YanNoun** [comment]
Hi,

It has been fixed here : https://github.com/mapillary/OpenSfM/commit/ff1cad80b287a6153e4c0a6972dc7f745cbcfee0

Let me know if that helps.

Yann

**Comment by YanNoun** [comment]
No answer in a while, closing.
