### ISSUE TITLE
How to get the camara center position?

### ISSUE THREAD

**Issue by Futen** [mapillary/OpenSfM#52]
Thanks for developing this tool，it's awesome. I recently have trouble to get the camera center position
(x, y, z), When I open reconstruction.meshed.json, I couldn't find where it is. Is the position information stored in the json file or something else??

**Comment by paulinus** [comment]
We store the camera position as a transformation from the world reference frame to the camera reference frame. In the the json file, every shot has `rotation` and `translation` fields. To get the camera center you need to compute it from those numbers.

In `reconstruction.py` there is the function to do so
```
def optical_center(shot):
    R = cv2.Rodrigues(np.array(shot['rotation'], dtype=float))[0]
    t = shot['translation']
    return -R.T.dot(t)
```

If what you want are the (lan, lon, alt) of the camera, you can get them onto the `reconstruction.json` file by running the `bin/align` command.

**Comment by Futen** [comment]
It works!!! Thank you so much!!!!!

**Comment by paulinus** [comment]
cool! thanks for trying
