### ISSUE TITLE
Power cables not visible

### ISSUE THREAD

**Issue by dicobrazz** [mapillary/OpenSfM#523]
Hi,

Can someone suggest what settings could be changed in the config to make power cables reconstruct? Attaching 2 screenshots, one of the scene processed in Pix4d (bottom screenshot), which seems to pick up power cables and the other OpenSfM.
<img width="1670" alt="Screenshot 2020-01-09 at 23 38 16" src="https://user-images.githubusercontent.com/22419700/72111159-40698b80-333a-11ea-9e41-e230398f1056.png">
<img width="1574" alt="Screenshot 2020-01-09 at 23 39 29" src="https://user-images.githubusercontent.com/22419700/72111168-4495a900-333a-11ea-93da-78a768150f51.png">

**Comment by YanNoun** [comment]
Hi,

Maybe you could it a try by increasing the resolution of the dense processing by increasing the `depthmap_resolution` parameter.

Let me know if that helps.

Yann

**Comment by YanNoun** [comment]
No answer in a while, closing.
