### ISSUE TITLE
Problem in GCP alignment

### ISSUE THREAD

**Issue by mac516** [mapillary/OpenSfM#524]
Hello,

I have problem in GCP alignment.

I generated dense cloud for the 1km length object with few GCP and following config.py.
  - bundle_use_gps: yes
  - bundle_use_gcp: yes     

In this case, each images has GPS location. GPS accuracy is not good, GCP accuracy is good.
Results are followings:
 - Features around GCP were aligned by GCP location
 - Features not around GCP were aligned by GPS location.
As a result, the shape of 1km length object is different from the original shape.
Is it possible to align dense cloud to GCP location with keeping the original shape.

I already tried following config.py.
 - bundle_use_gps: no,  bundle_use_gcp: yes
     Does not keep original shape because of lack of GPS information
 - bundle_use_gps: yes,  bundle_use_gcp: no
	Keep the original shape, but location accuracy is not good.

Thank you for your help.

**Comment by YanNoun** [comment]
Hi,

Could you share some data (DropBox, GDrive, Onedrive) with me, so I could give it a try ?

Yann

**Comment by YanNoun** [comment]
No answer in a while, closing.
