### ISSUE TITLE
WARNING: Not all images have GPS info. Disabling matching_gps_neighbors.

### ISSUE THREAD

**Issue by YangJae96** [mapillary/OpenSfM#528]
![exif](https://user-images.githubusercontent.com/57695621/72717804-188aeb00-3bb8-11ea-8f38-de7fc147acc9.png)
![camera_model](https://user-images.githubusercontent.com/57695621/72717807-188aeb00-3bb8-11ea-84b1-8303ef4eabfd.png)

Hi, I am trying to use the   "  bin/opensfm match_features path/to/dataset "  command in splitting a large dataset into smaller submodels. The problem is GPS info is missing when I tried the images
that I downloaded from the google or  from my phone. 
 But weird thing is when I run the command  "bin/opensfm_run_all data/(my images)" ,  
there is no error and no missing GPS info. So, I can get clear output of reconstruction.

Above is the Camera_model.json and exif.jpg.

1. I can't figure out why " bin/opensfm_run_all " even when the gps info is missing.
2. I want to know how to fill? or make the gps info in exif from image that I downloaded from google or from my camera.

Can anyone help me with this?? Thanks in advance.
![opensfm](https://user-images.githubusercontent.com/57695621/72714927-e62abf00-3bb2-11ea-8d6c-a6bc22d9d8dd.png)

**Comment by moopene36607** [comment]
You may find the answer here. https://github.com/mapillary/OpenSfM/issues/301

**Comment by YanNoun** [comment]
No answer in a while, closing.
