### ISSUE TITLE
Differences from code and result file

### ISSUE THREAD

**Issue by kjkim-kr** [mapillary/OpenSfM#538]
Hello, I have a question during reading result file of opensfm, 'tracks.csv'

with source code at

OpenSfM/opensfm/dataset.py
Line 513,

fileobj.write('%s\t%s\t%d\t%g\t%g\t%g\t%g\t%g\n' % (str(image), str(track), fid, x, y, r, g, b)) 

Each line in tracks.csv gives information "image name, track id, fid, x, y, r, g, b" to me.

but when I open 'tracks.csv' in data/berlin,
one more column is inserted.
like this
"03.jpg 1640 2123 -0.462243 -0.305387 0.00245209 170 158 144".

First I read this, I interpret this line as

Track 1640 data is found at fid = 2123 in 03.jpg, where
x coord = 123.238848
y coord = 476.412624
with r = 170, g = 158, and b = 144.

what is the value '0.00245209'? Is this a depth information? or something else?

**Comment by YanNoun** [comment]
Hi,

Please update to the latest master, as we modified the storage scheme a while ago. The value of `0.002` is the scale information of the feature, which we use for weighting purposes in the bundle adjustment.

Let me know if that helps,

Yann

**Comment by kjkim-kr** [comment]
Thanks. my question is now solved.

Ah, @YanNoun , Can I ask one more thing?

Are there any linear map T:(R,G,B) -> (depth, distance)?
more detail, How can I translate color values (170, 158, 144) to any distance (or depth) information?
It seems to be a value in depth map, but I don't know exactly how can I use these values.
T(170, 158, 144) -> 8.32 (m) or something else....

**Comment by paulinus** [comment]
The `tracks.csv` file contains only information about the 2D correspondences between images. There is no 3D information in it, so the depth can not be extracted from it.
3D data is stored in the `reconstruction.json` file. In there, each point has 3D coordinates. The ID of a point is the same as the id of the corresponding track.

**Comment by kireoxdz** [comment]
@kjkim-kr how to convert “-0.462243 -0.305387” to “x coord = 123.238848；y coord = 476.412624”？ I want to get 2d coordinates of matches.  thank you
