### ISSUE TITLE
Localize specified points(or ranges)

### ISSUE THREAD

**Issue by kjkim-kr** [mapillary/OpenSfM#539]
Hello.

Can I find some points at image A.jpg, from depth map(merged.ply or something else)?

For example,

I have 4 images, named {A.jpg, B.jpg, C.jpg, D.jpg}, respectively, which are moving forward images 1920 * 1080 captured from black-box at car.

I found a real-object from A.jpg, B.jpg, C.jpg, D.jpg using object-detection algorithm, 
object locates in (u1, v1), (u2, v2) at A.jpg , ... (bounding box)
(like (1044, 576) - left top, (1070, 602) - right bottom at A.jpg)

and run OpenSfM with 4 images, undistorted data are generated.

Q) If so, can I find a real-point (X,Y,Z) correspond to (1044, 576) at A.jpg?
more detail, can I figure out any points (u, v) at image (A.jpg), where that point (u, v) locates in depth-map(or real world), (x, y, z)?

Thanks.

**Comment by YanNoun** [comment]
Hi,

You can use `load_clean_depthmap` for loading the `depthmap` of any image, then, from this, you can get depth (relative to the image position) of all the pixels in your bounding-box.

Let me know if that helps.

Yann

**Comment by kjkim-kr** [comment]
load_clean_map function in [OpenSfM/dataset.py:741](https://github.com/mapillary/OpenSfM/blob/9cfc4d3cb21e657e5125ca759039b6deb2987f0e/opensfm/dataset.py#L741), right?

I found this function in [OpenSfM/dense.py:324](https://github.com/mapillary/OpenSfM/blob/9cfc4d3cb21e657e5125ca759039b6deb2987f0e/opensfm/dense.py#L320).

I will try with this function. 
@YanNoun Thanks for your reply.

**Comment by Sentient07** [comment]
Hi @kjkim-kr @YanNoun I am in a very similar position, trying to estimate SfM given 3 images taken from different locations. I intend to estimate 3D coordinates of pixels in an image, similar to the author's initial comment. When I extract the clean depth map, the depth of all pixels is empty. However, raw depth maps seem to contain sparse depth information. In the sense that only a few structures of the scene have depth and not all. (attaching the image). My questions are

1) Can depth be inferred only at those parts of the scene which have been observed by 2 or more cameras, for which parallax is available?
2) For the locations in the depth map, where no depth information is available( depth is 0 where it's not supposed to be), is a hallucination (Nearest neighbor approaches) valid approach?
3) Similar to @kjkim-kr , my input frames are `(1080x1920)`. However, depth maps are of shape `(360, 640)`. Could you please elaborate more on this? (My apologies if my understandings of the library/sfm are not concrete enough).


Thank you again for taking the time to read my question. 
Depth Map 
![Uploading image.png…]()

Regards,
