### ISSUE TITLE
When building OpenGV, python cannot be enabled

### ISSUE THREAD

**Issue by nabergh** [mapillary/OpenSfM#54]
When building OpenGV, I use the command below:

cmake .. -DBUILD_TESTS=OFF -DBUILD_PYTHON=ON

and it says that the option BUILD_PYTHON is ignored.

I know this is not specifically an OpenSfM problem, but the person in charge of OpenGV won't respond.  Has anyone else had trouble getting OpenGV python bindings working?  It seems like it's impossible to use OpenSfM without them.

**Comment by paulinus** [comment]
Never seen that. What OS are you using? Could you paste the complete output of the cmake command? Thanks!
