### ISSUE TITLE
Thread Thrashing in some processing steps

### ISSUE THREAD

**Issue by linusmartensson** [mapillary/OpenSfM#541]
Heya,

Setting up an OpenSfM container on a 96 core aws container, and noticed a staggering 10k (≃ 96²)  threads and resultant threading issues during detect_features after setting "processes: 96" in config.yaml, whilst setting "processes: 1" in the same way yields full multi-core usage. 
However, in the later reconstruction stage, "processes: 1" utilizes only one core, whilst "processes: 96" yields full multi-core usage.

Are some of the stages incorrectly multi-threading twice?

**Comment by YanNoun** [comment]
Hi,

We just figure out that `opencv` might spawn more threads in our back and we made a fix : https://github.com/mapillary/OpenSfM/commit/41f144035fdf61aa38538efdd906318b02ef6acb

Can you fetch latest master and let us know if that fixes your contention issue ?

Thanks,

Yann

**Comment by YanNoun** [comment]
Since OpenSfM switched to multithreading instead of multiprocessing, it should have fixed this issue.
