### ISSUE TITLE
hahog_peak_threshold and hahog_edge_threshold

### ISSUE THREAD

**Issue by dicobrazz** [mapillary/OpenSfM#542]
Hi all,

Tried to search for documentation or any issues, but couldn't find any information. How do those parameters effect the final outcome?

```
# Params for HAHOG
hahog_peak_threshold: 0.00001
hahog_edge_threshold: 10
hahog_normalize_to_uchar: yes
```

Thanks

**Comment by YanNoun** [comment]
Hi,

You can information in the `VLFeat` documentation here : https://www.vlfeat.org/api/covdet_8c.html#a16e0f9b96b16727a1bcec2df7bff0017

`hahog_peak_threshold` is the threshold above which a pixel is detected as a keypoint. The lower, the more keypoints. `hahog_edge_threshold` controls how much a keypoint can lie on an edge. The higher, the more tolerant, the more keypoints detected.

Let me know if that helps.

Yann

**Comment by dicobrazz** [comment]
> Hi,
> 
> You can information in the `VLFeat` documentation here : https://www.vlfeat.org/api/covdet_8c.html#a16e0f9b96b16727a1bcec2df7bff0017
> 
> `hahog_peak_threshold` is the threshold above which a pixel is detected as a keypoint. The lower, the more keypoints. `hahog_edge_threshold` controls how much a keypoint can lie on an edge. The higher, the more tolerant, the more keypoints detected.
> 
> Let me know if that helps.
> 
> Yann

That's great! Thank you for the information!
