### ISSUE TITLE
Generate 3D model with gps data

### ISSUE THREAD

**Issue by tub-sgg** [mapillary/OpenSfM#544]
I have a couple of images and I know exactly the location(X,Y,Z coordinates) of each camera.How can I insert these data to generate the real  size model

**Comment by YanNoun** [comment]
Hi,

You could turn these coordinates into some fake GPS coordinates in the `.exif` file by adding something like this :
`    "gps": {
        "latitude": FAKE_LAT 
        "longitude": FAKE_LON, 
        "altitude": FAKE_ALT
    }`

You can generate such FAKE_XXX by using the function `geo.lla_from_ecef` that will turn your XYZ into latitude/longitude/altitude. 

Additionally, in the `.exif` file, add `"gps_dop": 0.00001` or whatever small value (except zero) to indicate `OpenSfM` the accuracy of your XYZ.

Let me know if that helps.

Yann

**Comment by YanNoun** [comment]
No answer in a while, closing.
