### ISSUE TITLE
ImportError: cannot import name 'pyfeatures' from 'opensfm'

### ISSUE THREAD

**Issue by lineker10** [mapillary/OpenSfM#545]
Hello, Sir...
I try to run demo but, I saw error message as follows.

ImportError: cannot import name 'pyfeatures' from 'opensfm'

in Mac OS and in Linux Mint, both of them show this message.

Please help me..

Good bye.

**Comment by paulinus** [comment]
It looks like python could not find the extension modules which are build during the `setup.py build` step. Did you follow the [building instructions](https://www.opensfm.org/docs/building.html)

**Comment by YanNoun** [comment]
No answer in a while, closing.

**Comment by waltermorawa** [comment]
I got this same error on MacOS Catalina 10.15.5 after following the build instructions. First, I cloned the repository. Then, I ran these three commands:

```
brew install opencv
brew install ceres-solver
sudo pip install -r requirements.txt
```

I also ran pip3 in case it was needed for python 3.8

I exported the path:

```
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH
export PYTHONPATH=/usr/local/lib/python3.8/site-packages:$PYTHONPATH
```

Finally, I ran:

```
python setup.py build
python3 setup.py build
```

When I ran 
```
cd doc
make livehtml
```
I got the following error:

```
make: *** No rule to make target `livehtml'.  Stop.
```

When I tried running the sample:
```
bin/opensfm_run_all data/berlin
```

I got the following error:
```
Traceback (most recent call last):
  File "/Users/waltermorawa/Documents/OpenSfM/bin/opensfm_main.py", line 6, in <module>
    from opensfm import commands
  File "/Users/waltermorawa/Documents/OpenSfM/opensfm/commands/__init__.py", line 1, in <module>
    from . import (
  File "/Users/waltermorawa/Documents/OpenSfM/opensfm/commands/align_submodels.py", line 1, in <module>
    from opensfm.actions import align_submodels
  File "/Users/waltermorawa/Documents/OpenSfM/opensfm/actions/align_submodels.py", line 1, in <module>
    from opensfm.large import metadataset
  File "/Users/waltermorawa/Documents/OpenSfM/opensfm/large/metadataset.py", line 7, in <module>
    from opensfm import io
  File "/Users/waltermorawa/Documents/OpenSfM/opensfm/io.py", line 10, in <module>
    from opensfm import context, features, geo, pygeometry, pymap, types
  File "/Users/waltermorawa/Documents/OpenSfM/opensfm/features.py", line 10, in <module>
    from opensfm import context, pyfeatures
ImportError: cannot import name 'pyfeatures' from 'opensfm' (/Users/waltermorawa/Documents/OpenSfM/opensfm/__init__.py)
```

I will update if I find a solution. I'm also going to try running on Ubuntu/Docker. Best Regards

**Comment by fabianschenk** [comment]
Hi @waltermorawa ,

The `make livehtml` command has been replaced and you have to build the doc via: `python3 setup build_doc` (see this [issue](https://github.com/mapillary/OpenSfM/issues/748 )).

Regarding the second problem, it seems that the OpenMP library is missing on your system.
Try to run 
```
brew install libomp
```

Good luck ;)
Fabian

**Comment by ThakurSarveshGit** [comment]
> Thanks! Installing OpenMP seemed to fix the build issue.

Hi, installing libomp-dev via apt-get did not help in my case. I build OpenSfm successfully but while running the example reconstruction, I am getting the following error:
```
File ".../OpenSfM/opensfm/__init__.py", line 3, in <module>
    from opensfm import pyfeatures
ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0
```
Any thoughts what's wrong? #978
