### ISSUE TITLE
Invalid NVM from undistort and export_visualsfm

### ISSUE THREAD

**Issue by linusmartensson** [mapillary/OpenSfM#554]
The filename produced as output to an nvm file in https://github.com/mapillary/OpenSfM/blob/5825725706b3e86a488265e0d214924de21f0be3/opensfm/commands/export_visualsfm.py#L71 may currently contain spaces. 
This produces invalid NVM files that cannot be parsed by other editors, as the NVM file spec lacks escape characters for spaces, and separates its parameters by spaces.
This could be resolved by transforming the filenames in  https://github.com/mapillary/OpenSfM/blob/15d66bc284642b54ba7e2096923656efe12d823e/opensfm/dataset.py#L606
for example by hashing, filtering or b64-encoding the generated undistorted filename. 
Alternatively, this transformation could be done explicitly as part of the export step by copying the original files with issues to safe filenames, and referencing the copies in the export, preserving existing datasets without breaks. On systems that support symlinks, this could be done with efficient disk space usage.

**Comment by YanNoun** [comment]
No answer in a while, and two PR merged, closing.
