### ISSUE TITLE
Install opensfm on windows 10

### ISSUE THREAD

**Issue by kjkim-kr** [mapillary/OpenSfM#555]
Hello,
I'm trying to install OpenSfM on windows 10.

Are there any guides for installing this one on windows?
(without dockers, virual-machine environments)

I did various settings, (like mingw, cygwin, ... and so on) but
finally I failed to generate csfm.pyd (ALL_BUILD fails at visual studio)

(now I couldn't build VL project various errors, like M_PI undefined, VL_PI undefined...
SSE2 errors... )

Are there anyone install successfully?
I found #80 , OpenSfM seems to be able to run on windows...

Thanks.

**Comment by flyhamsw** [comment]
Did you try using WSL of Windows 10? I didn't tried installing OpenSfM on WSL, but it looked nice

**Comment by kjkim-kr** [comment]
@flyhamsw I didn't try yet, but thanks to your advice. I will try and leave results in here

**Comment by oradzhabov** [comment]
I've built OpenSFM by MSVC 2015.x64.
To fix SSE2 error:
1. In iroj properties - Code Generation/Enable Enhanced Instruction Set to "Streaming SIMD Extension 2(/arch:SSE2)"
2. Add __SSE2__ key to preprocessing definition.

**Comment by kjkim-kr** [comment]
Hello, @oradzhabov 
Here's my setting [here](https://imgur.com/Ou00QDD) as you adviced,

but I got errors again, here
오류	C1189	#error:  "Compiling with SSE2 enabled, but no __SSE2__ defined"	vl	C:\test\OpenSfM\opensfm\src\third_party\vlfeat\vl\imopv_sse2.c	15	
오류	C1189	#error:  Compiling SSE2 functions but SSE2 does not to be supported by the compiler.	vl	c:\test\opensfm\opensfm\src\third_party\vlfeat\vl\mathop_sse2.c	35	
오류	C2491	'vl_aib_process': dllimport 함수을(를) 정의할 수 없습니다.	vl	C:\test\OpenSfM\opensfm\src\third_party\vlfeat\vl\aib.c	589	
...

Did I miss something else?

**Comment by kjkim-kr** [comment]
Hello, @oradzhabov
Thanks for your advice, Finally, I could build OpenSfM and run data/berlin successfully

Thanks again. :)

**Comment by Sandeep10021** [comment]
@kjkim-kr Can you please guide with steps you followed? I am unable to install it on windows machine.

Thanks :)
