### ISSUE TITLE
Installation worked at commit id 0cdaf56, but it doesn't work now

### ISSUE THREAD

**Issue by flyhamsw** [mapillary/OpenSfM#558]
Hello. First of all, thank you very much for this wonderful project.

I have 2 PCs which are 1) a MacBook Pro 13-inch laptop and 2) a desktop with Ubuntu 18.04 LTS respectively.

Few weeks ago, I managed to install OpenSfM on my MacBook Pro successfully. After that, I also got to install OpenSfM on the Ubuntu PC today. However, even if I already installed all the dependencies that OpenSfM needs, the installation script failed to install the software.

I found that the problem didn't happen when I was dealing with my MacBook few weeks ago, and it just happened now in Ubuntu PC. It looked like something was happened during few weeks. So, I decided to find which commit was checked out in MacBook and Ubuntu PC. The result was...

1) MacBook - 0cdaf565acaae899a668ad88b57ecdbb9eb285bb
2) Ubuntu PC - 04e24a0a7bd79843e9b2993e7cfe9938d96b5fb9

So, in Ubuntu PC, I checked out commit id 0cdaf56 (same with MacBook), and I could build OpenSfM successfully.

Here is the error message when I was building OpenSfM with 04e24a0 commit was checked out.

Thank you.

![opensfm_build_error](https://user-images.githubusercontent.com/17755280/76168849-90d45c80-61b6-11ea-8881-ff31b1bc1c77.png)

Scanning dependencies of target geometry
[ 58%] Building CXX object geometry/CMakeFiles/geometry.dir/src/essential.cc.o
[ 59%] Building C object third_party/vlfeat/CMakeFiles/vl.dir/vl/stringop.c.o
[ 61%] Building C object third_party/vlfeat/CMakeFiles/vl.dir/vl/svm.c.o
[ 62%] Building C object third_party/vlfeat/CMakeFiles/vl.dir/vl/svmdataset.c.o
[ 63%] Building C object third_party/vlfeat/CMakeFiles/vl.dir/vl/vlad.c.o
[ 64%] Linking C static library libvl.a
[ 64%] Built target vl
[ 66%] Building CXX object geometry/CMakeFiles/geometry.dir/src/triangulation.cc.o
[ 67%] Linking CXX static library libdense.a
[ 67%] Built target dense
[ 68%] Building CXX object geometry/CMakeFiles/geometry.dir/src/absolute_pose.cc.o
Scanning dependencies of target testing_main
[ 70%] Building CXX object CMakeFiles/testing_main.dir/testing_main.cc.o
[ 71%] Linking CXX static library libtesting_main.a
[ 71%] Built target testing_main
[ 72%] Building CXX object geometry/CMakeFiles/geometry.dir/src/relative_pose.cc.o
In file included from /root/OpenSfM/opensfm/src/geometry/relative_pose.h:7:0,
                 from /root/OpenSfM/opensfm/src/geometry/src/relative_pose.cc:1:
/usr/local/include/ceres/tiny_solver_autodiff_function.h: In instantiation of 'class ceres::TinySolverAutoDiffFunction<RelativePoseCost<__gnu_cxx::__normal_iterator<std::pair<Eigen::Matrix<double, 3, 1>, Eigen::Matrix<double, 3, 1> >*, std::vector<std::pair<Eigen::Matrix<double, 3, 1>, Eigen::Matrix<double, 3, 1> > > > >, -1, 6, double>':
/root/OpenSfM/opensfm/src/geometry/relative_pose.h:139:24:   required from 'Eigen::Matrix<double, 3, 4> RelativePoseRefinement(const Eigen::Matrix<double, 3, 4>&, IT, IT, int) [with IT = __gnu_cxx::__normal_iterator<std::pair<Eigen::Matrix<double, 3, 1>, Eigen::Matrix<double, 3, 1> >*, std::vector<std::pair<Eigen::Matrix<double, 3, 1>, Eigen::Matrix<double, 3, 1> > > >]'
/root/OpenSfM/opensfm/src/geometry/src/relative_pose.cc:47:92:   required from here
/usr/local/include/ceres/tiny_solver_autodiff_function.h:138:62: error: size of array is negative
   mutable Jet<T, kNumParameters> jet_residuals_[kNumResiduals];
                                                              ^
geometry/CMakeFiles/geometry.dir/build.make:134: recipe for target 'geometry/CMakeFiles/geometry.dir/src/relative_pose.cc.o' failed
make[2]: *** [geometry/CMakeFiles/geometry.dir/src/relative_pose.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target pydense
[ 74%] Building CXX object dense/CMakeFiles/pydense.dir/python/pybind.cc.o
Scanning dependencies of target features
[ 75%] Building CXX object features/CMakeFiles/features.dir/src/akaze_bind.cc.o
[ 76%] Linking CXX static library libbundle.a
[ 76%] Built target bundle
[ 77%] Building CXX object features/CMakeFiles/features.dir/src/hahog.cc.o
CMakeFiles/Makefile2:671: recipe for target 'geometry/CMakeFiles/geometry.dir/all' failed
make[1]: *** [geometry/CMakeFiles/geometry.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 79%] Building CXX object features/CMakeFiles/features.dir/src/matching.cc.o
[ 80%] Linking CXX shared module /root/OpenSfM/opensfm/pydense.cpython-36m-x86_64-linux-gnu.so
[ 81%] Linking CXX static library libfeatures.a
[ 81%] Built target features
[ 81%] Built target pydense
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    build_c_extension()
  File "setup.py", line 45, in build_c_extension
    subprocess.check_call(['make', '-j4'], cwd='cmake_build')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.

**Comment by flyhamsw** [comment]
sorry for wrong screenshot place 🙏

**Comment by YanNoun** [comment]
Hi,

Sorry for the inconvenience, there was effectively a glitch two days ago with the supported Ceres version leading to build errors.

It has been fixed on Monday at the following commit ID : https://github.com/mapillary/OpenSfM/commit/aac0e0dbb0f29ca8ddc099eb9d74b780923909fd

Please update to latest master.

Let me know if that solves your issue,

Yann

**Comment by flyhamsw** [comment]
Thank you for your effort. I'll try soon.

**Comment by flyhamsw** [comment]
Checked out the most recent commit, and the installation works perfectly. It was tested on macOS.
