### ISSUE TITLE
Can this project be accelerated by GPU further? 

### ISSUE THREAD

**Issue by EchoTHChen** [mapillary/OpenSfM#560]
I recenly have to run hundreds of samples on this project. I have used multiprocesses and parallel calculating methods of joblib. But it is still a little slow for me. I hope there is a way for me to accelerate OpenSfM further.  Do you have a gpu version of this project? Or do you have any suggestion for me ? Thanks!

**Comment by pierotofy** [comment]
Hey @EchoTHChen :hand: see my answer on #563

**Comment by EchoTHChen** [comment]
Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Piero Toffanin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月17日(星期二) 上午10:05
收件人:&nbsp;"mapillary/OpenSfM"<OpenSfM@noreply.github.com&gt;;
抄送:&nbsp;"3296271079"<3296271079@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [mapillary/OpenSfM] Can this project be accelerated by GPU further?  (#560)





 
Hey @EchoTHChen  see my answer on #563
