### ISSUE TITLE
the format of the reconstruction file

### ISSUE THREAD

**Issue by RemoteSensingFrank** [mapillary/OpenSfM#562]
could you plz explain the meaning of the tracks.csv file and the reconstruction.json file？I‘m confused by the translation and gps_position and the reference_lla.json. What should I do if I want to calculate the camera position in real world coordinate.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by pierotofy** [comment]
This might help: https://www.opensfm.org/docs/dataset.html#reconstruction-file-format

**Comment by RemoteSensingFrank** [comment]
thanks and after I read the source and my problem have been solved
