### ISSUE TITLE
Is it possible to fix the GPS of certain frames during bundle adjustment?

### ISSUE THREAD

**Issue by moopene36607** [mapillary/OpenSfM#567]
I filmed a short video using insta360 and add GPS information of 4 key frames, which is search from google map.
Following the suggestions in https://www.opensfm.org/docs/using.html and  https://github.com/mapillary/OpenSfM/issues/544, I set set the dop=0.0001 in the exif_overrides.json. (Also tried dop=0.0000000000001, but it did get better...)
After running bin/opensfm export_geocoords, I found that the location of these 4 key frames drifted and the coordinates of all frames in video just clustered together.
Does it possible to fix GPS info during bundle adjustment?

**Comment by paulinus** [comment]
Bundle adjustment will use the GPS position in the exif. If you set them in the `exif_overrides.json`, then they will get used.

Can you check what is the value of `shots -> image_name -> gps_position` in `reconstruction.json` for the images that you set the GPS position?

If it is 0, please, be sure to run `extract_metadata` after creating or modifying `exif_overrides.json` file. You need to remove the `exif` to be sure that it gets recreated with the new data.

**Comment by moopene36607** [comment]
No...it's not 0. 
Is it possible that the GPS information is not strong enough to spread out all the points? Is the whole process guarantee the GPS in `reconstruction.json` the same as the GPS in `exif`?
BTW, I tried adding GCP and it works better.

**Comment by paulinus** [comment]
Hard to know what is going on. Could you share a small dataset that reproduces the problem?

**Comment by moopene36607** [comment]
Sure! I will email you a link. Thanks lot.
