### ISSUE TITLE
camera_model_overrides

### ISSUE THREAD

**Issue by lukebaumann** [mapillary/OpenSfM#57]
focal_from_exif line 55
from
for key, value in camera_models_overrides:

to
for key, value in camera_models_overrides.items():

**Comment by paulinus** [comment]
Thanks @lukebaumann! fixed.

Are you trying to use your own camera calibration?

**Comment by lukebaumann** [comment]
My images are from a GoPro video and do not have exif data embedded in them.

**Comment by lukebaumann** [comment]
opensfm/reconstructions.py lines 28 and 74 fail when overrides are present it seems like

I am not entirely sure what is the code is trying to do but maybe this is a sufficient fix:

defaultProjection = reconstruction['cameras'].get('projection_type', 'perspective')
for k, v in reconstruction['cameras'].items():
    if not isinstance(v, dict):
        continue
    pt = v.get('projection_type', defaultProjection)

**Comment by paulinus** [comment]
In that code, `v` should always be a dict.  What are the contents of the `camera_models_overrides.json` that you are using?
It should be of the same form as `camera_models.json`. The simplest way to generate it is to do first run without it. Then, rename `camera_models.json` to `camera_models_overrides.json` and modify the values in there.

**Comment by paulinus** [comment]
i'm closing this issue. @lukebaumann let me know if you need any help
