### ISSUE TITLE
Error on testing data/berlin

### ISSUE THREAD

**Issue by kjkim-kr** [mapillary/OpenSfM#570]
Hello, now I'm upgrading my opencv 3 to 4, and re-install OpenSfM.

When I test with bin/opensfm_run_all data/berlin, I found I have an error

> KJ:~/OpenSfM$ bin/opensfm_run_all data/berlin
> Running using Python command: python3
> 
> 2020-04-01 17:36:58,275 INFO: Extracting EXIF for 03.jpg
> 2020-04-01 17:36:58,309 ERROR: Image file "data/berlin/images/03.jpg" has no valid time stamp
> 2020-04-01 17:36:58,309 INFO: Extracting EXIF for 02.jpg
> 2020-04-01 17:36:58,344 ERROR: Image file "data/berlin/images/02.jpg" has no valid time stamp
> 2020-04-01 17:36:58,345 INFO: Extracting EXIF for 01.jpg
> 2020-04-01 17:36:58,383 ERROR: Image file "data/berlin/images/01.jpg" has no valid time stamp
> 2020-04-01 17:36:59,467 INFO: Extracting ROOT_HAHOG features for image 03.jpg
> 2020-04-01 17:36:59,534 INFO: Extracting ROOT_HAHOG features for image 01.jpg
> 2020-04-01 17:36:59,536 INFO: Extracting ROOT_HAHOG features for image 02.jpg
> 2020-04-01 17:37:00,294 DEBUG: Found 4749 points in 0.7160384654998779s
> 2020-04-01 17:37:00,347 DEBUG: Masking 0 / 4749 (0.00) features for 03.jpg
> 2020-04-01 17:37:00,369 DEBUG: Found 4791 points in 0.7144503593444824s
> 2020-04-01 17:37:00,376 DEBUG: Found 4810 points in 0.7099905014038086s
> 2020-04-01 17:37:00,422 DEBUG: Masking 121 / 4791 (0.03) features for 01.jpg
> 2020-04-01 17:37:00,429 DEBUG: Masking 371 / 4810 (0.08) features for 02.jpg
> 2020-04-01 17:37:01,150 INFO: Matching 3 image pairs
> 2020-04-01 17:37:01,155 INFO: Computing pair matching with 8 processes
> 2020-04-01 17:37:01,702 DEBUG: Image 02.jpg matches: 0 out of 0
> 2020-04-01 17:37:01,721 DEBUG: Masking 0 / 4670 (0.00) features for 01.jpg
> 2020-04-01 17:37:01,758 DEBUG: Masking 0 / 4749 (0.00) features for 03.jpg
> 2020-04-01 17:37:01,777 DEBUG: Masking 0 / 4749 (0.00) features for 03.jpg
> 2020-04-01 17:37:01,825 DEBUG: Masking 0 / 4439 (0.00) features for 02.jpg
> 2020-04-01 17:37:02,033 DEBUG: Matching 01.jpg and 03.jpg.  Matcher: FLANN (symmetric) T-desc: 0.368 T-robust: 0.001 T-total: 0.369 Matches: 348 Robust: 298 Success: True
> 2020-04-01 17:37:02,071 DEBUG: Matching 03.jpg and 02.jpg.  Matcher: FLANN (symmetric) T-desc: 0.366 T-robust: 0.001 T-total: 0.367 Matches: 847 Robust: 791 Success: True
> 2020-04-01 17:37:02,071 DEBUG: Image 03.jpg matches: 1 out of 1
> 2020-04-01 17:37:02,095 DEBUG: Masking 0 / 4439 (0.00) features for 02.jpg
> 2020-04-01 17:37:02,247 DEBUG: Matching 01.jpg and 02.jpg.  Matcher: FLANN (symmetric) T-desc: 0.206 T-robust: 0.002 T-total: 0.208 Matches: 1249 Robust: 1209 Success: True
> 2020-04-01 17:37:02,247 DEBUG: Image 01.jpg matches: 2 out of 2
> 2020-04-01 17:37:02,248 INFO: Matched 3 pairs for 3 ref_images (perspective-perspective: 3) in 1.0978643290000036 seconds (0.3659548706685503 seconds/pair).
> 2020-04-01 17:37:02,939 INFO: reading features
> 2020-04-01 17:37:02,958 DEBUG: Merging features onto tracks
> 2020-04-01 17:37:02,970 DEBUG: Good tracks: 1719
> 2020-04-01 17:37:03,602 INFO: Starting incremental reconstruction
> 2020-04-01 17:37:04,162 INFO: Starting reconstruction with 01.jpg and 02.jpg
> 2020-04-01 17:37:04,197 INFO: Two-view reconstruction inliers: 1221 / 1221
> 2020-04-01 17:37:04,299 INFO: Triangulated: 1205
> 2020-04-01 17:37:04,310 DEBUG: Ceres Solver Report: Iterations: 3, Initial cost: 1.254733e+01, Final cost: 1.181251e+01, Termination: CONVERGENCE
> 2020-04-01 17:37:04,391 DEBUG: Ceres Solver Report: Iterations: 3, Initial cost: 1.208705e+01, Final cost: 1.183332e+01, Termination: CONVERGENCE
> 2020-04-01 17:37:04,466 DEBUG: Ceres Solver Report: Iterations: 15, Initial cost: 3.072789e+01, Final cost: 2.399422e+01, Termination: CONVERGENCE
> 2020-04-01 17:37:04,477 INFO: Removed outliers: 0
> 2020-04-01 17:37:04,477 INFO: -------------------------------------------------------
> 2020-04-01 17:37:04,486 INFO: 03.jpg resection inliers: 217 / 368
> 2020-04-01 17:37:04,489 DEBUG: Ceres Solver Report: Iterations: 4, Initial cost: 3.037148e+01, Final cost: 2.824587e+01, Termination: CONVERGENCE
> 2020-04-01 17:37:04,490 INFO: Adding 03.jpg to the reconstruction
> 2020-04-01 17:37:04,514 INFO: Re-triangulating
> 2020-04-01 17:37:04,774 DEBUG: Ceres Solver Report: Iterations: 63, Initial cost: 1.287844e+02, Final cost: 5.156605e+01, Termination: CONVERGENCE
> 2020-04-01 17:37:04,935 DEBUG: Ceres Solver Report: Iterations: 9, Initial cost: 1.499002e+02, Final cost: 1.188863e+02, Termination: CONVERGENCE
> 2020-04-01 17:37:04,951 INFO: Removed outliers: 6
> 2020-04-01 17:37:04,951 INFO: -------------------------------------------------------
> 2020-04-01 17:37:05,088 DEBUG: Ceres Solver Report: Iterations: 20, Initial cost: 1.427306e+02, Final cost: 1.252050e+02, Termination: CONVERGENCE
> 2020-04-01 17:37:05,105 INFO: Removed outliers: 3
> 2020-04-01 17:37:05,113 INFO: {'observations_count': 3756, 'points_count': 1700, 'cameras_count': 3, 'average_track_length_notwo': 3.0, 'average_track_length': 2.2094117647058824}
> 2020-04-01 17:37:05,113 INFO: Reconstruction 0: 3 images, 1700 points
> 2020-04-01 17:37:05,113 INFO: 1 partial reconstructions in total.
> 2020-04-01 17:37:06,694 DEBUG: Undistorting the reconstruction
> 2020-04-01 17:37:07,265 DEBUG: Undistorting image 03.jpg
> 2020-04-01 17:37:07,307 DEBUG: Undistorting image 01.jpg
> 2020-04-01 17:37:07,313 DEBUG: Undistorting image 02.jpg
> 2020-04-01 17:37:08,396 INFO: Computing neighbors
> 2020-04-01 17:37:08,914 INFO: Computing depthmap for image 02.jpg with PATCH_MATCH_SAMPLE
> 2020-04-01 17:37:08,972 INFO: Computing depthmap for image 03.jpg with PATCH_MATCH_SAMPLE
> 2020-04-01 17:37:08,975 INFO: Computing depthmap for image 01.jpg with PATCH_MATCH_SAMPLE
> 2020-04-01 17:37:36,673 INFO: Cleaning depthmap for image 02.jpg
> 2020-04-01 17:37:36,675 INFO: Cleaning depthmap for image 03.jpg
> 2020-04-01 17:37:36,682 INFO: Cleaning depthmap for image 01.jpg
> 2020-04-01 17:37:38,303 INFO: Pruning depthmap for image 02.jpg
> 2020-04-01 17:37:38,304 INFO: Pruning depthmap for image 03.jpg
> 2020-04-01 17:37:38,306 INFO: Pruning depthmap for image 01.jpg
> 2020-04-01 17:37:39,431 INFO: Merging depthmaps
> KJ:~/OpenSfM$

What's this error, "2020-04-01 17:36:58,309 ERROR: Image file "data/berlin/images/03.jpg" has no valid time stamp" ?

When this error occurs and how can I modify that?
Does OpenCV4 affect  this error?

Thanks.

**Comment by paulinus** [comment]
This should be a warning. I will change it. There is nothing wrong there; just that those images actually do not have a valid timestamp.
