### ISSUE TITLE
Images matched with themselves in pairselection.py

### ISSUE THREAD

**Issue by santelelle** [mapillary/OpenSfM#578]
During the matching phase each image is also matched agains itself.

The problem shows when using `bin/opensfm match_features <folder>`

In file **pairselection.py**
line 298 `pairs = set([tuple(sorted([i, j])) for i in images_ref for j in images_cand])`

A quick fix should be 
line 298 `pairs = set([tuple(sorted([i, j])) for i in images_ref for j in images_cand if i!=j])`

**Comment by paulinus** [comment]
fixed. Thanks, @santelelle
