### ISSUE TITLE
Add Ground Control Points support

### ISSUE THREAD

**Issue by paulinus** [mapillary/OpenSfM#58]
There should be an option to use GCP while reconstructing. This should be used when aligning the reconstruction and during bundle adjustment.

**Comment by btchouston** [comment]
Please @paulinus can you tell me when is gcp used inside the reconstruction ? 
Is it absolutely necessary for images to have exif data ?

**Comment by YanNoun** [comment]
Ground control points supports can be found here : https://www.opensfm.org/docs/using.html#ground-control-points.

@btchouston regarding your questions :
 - GCP are used through the SfM reconstruction process during bundle adjustment.
 - No necessarily, but it will definitely helps and makes the difference between a bad or average reconstruction and a very good one.
