### ISSUE TITLE
How is accelerometer data used in OpenSfM?

### ISSUE THREAD

**Issue by CameronFraser** [mapillary/OpenSfM#596]
In the README it says:

> It also integrates external sensor (e.g. GPS, accelerometer) measurements for geographical alignment and robustness. 

I see where the GPS data is being used, but all i see is the accelerometer data being read into a metadata object and I'm not sure if it is being used anywhere. Can anyone shine some light on how exactly the accelerometer data is being leveraged during reconstruction?

**Comment by pierotofy** [comment]
I'm pretty sure accelerometer data is not being used (?)

**Comment by pierotofy** [comment]
Actually, it looks like there's support for using accelerometer information in the latest version! https://github.com/mapillary/OpenSfM/blob/master/opensfm/reconstruction.py#L285

**Comment by YanNoun** [comment]
Hi @CameronFraser @pierotofy , accelerometer support has some bits here and there plugged, but isn't used yet in OpenSfM.
