### ISSUE TITLE
Document Mask creation process

### ISSUE THREAD

**Issue by Germanunkol** [mapillary/OpenSfM#598]
How to mask images was a bit difficult to figure out. It took me a while to find out that the mask needs an extra extension (.png). I think a description in the documentation would really help.

In the meantime, the process can be figured out by reading all the comments in the original pull request: https://github.com/mapillary/OpenSfM/pull/132

See also #551

**Comment by YanNoun** [comment]
Closing as it is a duplicate of https://github.com/mapillary/OpenSfM/issues/551
