### ISSUE TITLE
Issue a release for odm-2 branch

### ISSUE THREAD

**Issue by dakotabenjamin** [mapillary/OpenSfM#60]
Would you mind creating a release for the `odm-2` branch? I'm trying to have better control over the download step [here](https://github.com/edgarriba/OpenDroneMap/issues/14), so having a release for that branch will prevent the need to update the MD5 hash after an update.

**Comment by paulinus** [comment]
Just created one here https://github.com/mapillary/OpenSfM/releases/tag/odm-2. Let me know if that's what is needed

**Comment by dakotabenjamin** [comment]
Perfect, thank you!
