### ISSUE TITLE
How to run or add OpenSfM in other Program (question)

### ISSUE THREAD

**Issue by luisEMEBA** [mapillary/OpenSfM#615]
Hi Everyone, first than all I want to thank you very much for this awesome tool, I've been exploring it since a few months ago and now I wish to develop a program where I want to call OpenSfM functions as compute_depthmaps.py or create_tracks.py. So my question is if can I add OpenSfM as a library in my program or if I can run those python scripts from my program? Which programing language should I use? 

Hope that it has been clear, I'm new on developing so I'll be very thankful with you for your help.

**Comment by pierotofy** [comment]
Hey @luisEMEBA :hand: the easiest way is to simply invoke the launch a process that invokes Python and calls `bin/opensfm`.

Each language has its own way to accomplish this. In Python, this can be done via the `subprocess` module (look it up in the Python reference documentation).

**Comment by luisEMEBA** [comment]
Thank you very much! :D
