### ISSUE TITLE
match_features: has_gps_info not reading gps info

### ISSUE THREAD

**Issue by dakotabenjamin** [mapillary/OpenSfM#62]
I have a [photoset](https://github.com/opendronemap/odm_data_caliterra) that is georeferenced but am getting this warning when trying to run match_features:
`WARNING:__main__:Not all images have GPS info. Disabling matching_gps_neighbors.`
It comes from this part of the code:
https://github.com/mapillary/OpenSfM/blob/master/bin/match_features#L48

The call all(map(has_gps_info, exifs)) is returning false, even though all the photos have gps exif tags. I can't figure out exactly what is going on, but I think map() is not properly passing the exifs dictionary to has_gps_info

**Comment by paulinus** [comment]
There was a bug on that line indeed. The map is iterating over the keys of the dict instead of the values. Just fixed it. Thanks!

**Comment by YangJae96** [comment]
Hi, I am getting the same problem using the openSfM. I get the error message when I put my images into the dataset and then try to divide into submodel. 
Did you solve the problem??
