### ISSUE TITLE
build error relating to ceres solver

### ISSUE THREAD

**Issue by yuni-g** [mapillary/OpenSfM#630]
On my Ubuntu 20.04, running on VMware windows host, 
when running setup.py, I get this kinds of error everywhere:

/usr/local/include/ceres/internal/variadic_evaluate.h:74:52: error: ‘ParameterBlockIndices’ was not declared in this scope

/usr/local/include/ceres/internal/parameter_dims.h:74:40: error: ‘ceres::internal::IsValidParameterDimensionSequence’ cannot be used as a function

Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    build_c_extension()
  File "setup.py", line 45, in build_c_extension
    subprocess.check_call(['make', '-j4'], cwd='cmake_build')
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.

which I can't figure out why. Tried reinstalling ceres & opencv multiple times with different methods, apt-get, build from source, fPIC flag and other CMAKE parameter flags but no luck.

Anybody has an insight to solve this problem?

**Comment by exploringNewThings** [comment]
Hey @yuni-g ,

I am facing the same issue. Were you able to resolve it?\
If yes, could you please share the details on the same?

Thank you.
