### ISSUE TITLE
How to get the current camera pose from a built reconstruction?

### ISSUE THREAD

**Issue by Harry-675** [mapillary/OpenSfM#631]
Hi, like the title question, if I got a new frame, and there is already a reconstruction about this scene, is there any method to get the current pose of the frame? Thanks for help!

**Comment by rudyryk** [comment]
Same here. When just adding the new picture to the `images`, it does new reconstruction with new 0-point, so all other positions are not the same as for original reconstruction.

**Comment by YanNoun** [comment]
Hi @Harry-675 and @rudyryk , I'm closing since it is a features many others user have been asking here : https://github.com/mapillary/OpenSfM/issues/129 and here : https://github.com/mapillary/OpenSfM/issues/115
