### ISSUE TITLE
geometry/camera_functions.h:7:38: fatal error: unsupported/Eigen/AutoDiff: No such file or directory

### ISSUE THREAD

**Issue by Techhooli** [mapillary/OpenSfM#637]
I have tried lots of methods. But i can't solve this problem, even though I try to modify the CMakelist.txt in the src. I also copy the unsupported (Eigen) to the file folder in the geometry. However, it doesn't work. Who can help me? I have wasted three days on it. I don't know which path the program is looking for. My god, the AutoDiff is here. But the program don't know. Of course, i also try to modify the environment variables. It's upsetting...

The problems are shown as follows:
/OpenSfM/opensfm/src/geometry/camera_functions.h:7:38: fatal error: unsupported/Eigen/AutoDiff: No such file or directory
compilation terminated.
geometry/CMakeFiles/geometry.dir/build.make:79: recipe for target 'geometry/CMakeFiles/geometry.dir/src/camera.cc.o' failed
make[2]: *** [geometry/CMakeFiles/geometry.dir/src/camera.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:870: recipe for target 'geometry/CMakeFiles/geometry.dir/all' failed
make[1]: *** [geometry/CMakeFiles/geometry.dir/all] Error 2
Makefile:157: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    build_c_extension()
  File "setup.py", line 45, in build_c_extension
    subprocess.check_call(['make', '-j4'], cwd='cmake_build')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2

**Comment by Techhooli** [comment]
I have solved it. but what is undefined symbol: _Py_ZeroStruct

**Comment by YanNoun** [comment]
Hi @Techhooli ,

Try running `rm -rf cmake_build` and then `python setup.py build``.

Yann

**Comment by YanNoun** [comment]
No answer in a while, closing.
