### ISSUE TITLE
Meaning of the 'depth.npy' file

### ISSUE THREAD

**Issue by Leviosaaaa** [mapillary/OpenSfM#643]
I have been trying to evaluate the reconstruction by comparing the output depthmaps with groundtruth. However, I failed to figure out the meaning of the 'depth.npy' file in the undistorted.depthmaps folder.
My input images are 1280*1024 .png files. Confusingly, the corresponding 'depth.npy' file is a float32 (512, 640) matrix, which is not of the same size as the resolution of input images. So, what does the matrix in 'depth.npy' means; or is there a better way to access the reconstructed depthmaps information?
Thanks in advance!

**Comment by originlake** [comment]
The size of the depth map is based on the configuration, check the config.py for the default value, `depthmap_resolution: 640`. That's why your depth matrix has size (512, 640)

**Comment by YanNoun** [comment]
Question answered and no answer in a while, closing.

**Comment by Leviosaaaa** [comment]
Thank you very much for replying! I am sorry for not answering and closing this issue earlier.
