### ISSUE TITLE
bin/opensfm.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by matheusfillipe** [mapillary/OpenSfM#649]
Just finally built it but this file is missing I guess?

**Comment by spicfrankly** [comment]
Same here. The file is not existing in the repository. Should it be generated?

**Comment by spicfrankly** [comment]
OK got it!
The file bin/opensfm [no extension] used to be a python script back in time.
The last version when it used to be a python script is https://raw.githubusercontent.com/mapillary/OpenSfM/6328adc9f78ffbf6f90974cd18068646d146a30a/bin/opensfm.

To fix this problem temporarily, I created the file bin/opensfm.py with the content of the version above.

**Comment by matheusfillipe** [comment]
Yeah I think the forgot the file on these latest commits :P .

**Comment by YanNoun** [comment]
Hi all,

It has been fixed here https://github.com/mapillary/OpenSfM/commit/e84efb4adc179a3f94e5f1a2a4d1e9d8de71d391#diff-ca1ae7ea9d6a7843795feb6ec087ea68, sorry for the inconvenience.

Yann

**Comment by spicfrankly** [comment]
Thank you guys!
