### ISSUE TITLE
No such file or directory: 'data/lund/tracks.csv'

### ISSUE THREAD

**Issue by iloveedward** [mapillary/OpenSfM#65]
Hello,

I tried to run the command of "bin/mesh data/lund" after building OpenSfm successfully. But I met the following issue. 

Traceback (most recent call last):
  File "bin/mesh", line 22, in <module>
    graph = data.load_tracks_graph()
  File "/Users/fangru/Downloads/OpenSfm-master/opensfm/dataset.py", line 279, in load_tracks_graph
    with open(self.__tracks_graph_file()) as fin:
IOError: [Errno 2] No such file or directory: 'data/lund/tracks.csv'

Could you help me to solve it? Thanks a lot.

Jie

**Comment by ybkuang** [comment]
Hi Jie, have you run the reconstruction part for the data yet? e.g. have you tried `bin/run_all data/lund`?

**Comment by iloveedward** [comment]
I tried bin/run_all data/lund. It showed the following error messages:

Traceback (most recent call last):
  File "/Users/fangru/Downloads/OpenSfm-master/bin/focal_from_exif", line 10, in <module>
    from opensfm import exif
  File "/Users/fangru/Downloads/OpenSfm-master/opensfm/exif.py", line 6, in <module>
    import exifread
ImportError: No module named exifread

**Comment by ybkuang** [comment]
Look like exifread is not properly installed.  Can you try `sudo pip install -r requirements.txt`?

**Comment by iloveedward** [comment]
After executing  "sudo pip install -r requirements.txt", it has the following error. 
Traceback (most recent call last):
  File "/Users/fangru/Downloads/OpenSfm-master/bin/match_features", line 13, in <module>
    from opensfm import matching
  File "/Users/fangru/Downloads/OpenSfm-master/opensfm/matching.py", line 3, in <module>
    import pyopengv
ImportError: No module named pyopengv

But I have installed opengv before.

**Comment by ybkuang** [comment]
Maybe you can follow https://github.com/mapillary/OpenSfM#installing-dependencies-on-macosx to install all the dependencies?

**Comment by iloveedward** [comment]
Follow the instructions in https://github.com/mapillary/OpenSfM#installing-dependencies-on-macosx , I met with this issue after executing "make install" for installing opengv. 

[  1%] Building CXX object CMakeFiles/opengv.dir/src/relative_pose/CentralRelativeMultiAdapter.o
In file included from /Users/fangru/opengv/src/relative_pose/CentralRelativeMultiAdapter.cpp:32:
/Users/fangru/opengv/include/opengv/relative_pose/CentralRelativeMultiAdapter.hpp:44:10: fatal error: 'boost/shared_ptr.hpp' file not found
#include <boost/shared_ptr.hpp>
         ^
1 error generated.
make[2]: *** [CMakeFiles/opengv.dir/src/relative_pose/CentralRelativeMultiAdapter.o] Error 1
make[1]: *** [CMakeFiles/opengv.dir/all] Error 2
make: *** [all] Error 2

**Comment by paulinus** [comment]
it looks like boost is missing. You should run 
```brew install boost```
To get that dependency. You should also run
```brew install boost-python```
which you will also need.

**Comment by iloveedward** [comment]
After executing "brew install boost", I had the message below
Warning: boost-1.60.0 already installed

It seems that the boost is already installed. Is the version of boost fine for your project?

**Comment by paulinus** [comment]
Yes that version works fine. The problem seems to be that the compiler is not finding it.

It looks like OpenGV's cmake files don't search for boost explicitly. That would solve the problem. I will update that cmake.

Until then, you can set the include path to include `/usr/local/include` using
```
export C_INCLUDE_PATH=/usr/local/include
export CPLUS_INCLUDE_PATH=/usr/local/include
export LD_LIBRARY_PATH=/usr/local/lib
```

**Comment by iloveedward** [comment]
During building opengv, I also met with the following issue:

[ 92%] Built target opengv
[ 97%] Built target random_generators
make[2]: *** No rule to make target `/libboost_python.a', needed by `lib/pyopengv.so'.  Stop.
make[1]: *** [python/CMakeFiles/pyopengv.dir/all] Error 2
make: *** [all] Error 2

After adding set(Boost_LIBRARY_DIR /usr/local/lib) in CMakeLists.txt file under opengv/python, opengv is successfully installed.

Then I run 
bin/run_all data/lund
python -m SimpleHTTPServer

and browsed http://localhost:8000/viewer/reconstruction.html#file=/data/lund/reconstruction.meshed.json, the web page showed up. "bin/mesh data/lund" also works. 

Thanks for your guys’ supporting.

**Comment by paulinus** [comment]
Happy to hear!
thanks for reporting

**Comment by Adnino** [comment]
Hi, I am unable to generate pyopengv.so. When I run : cmake -D BUILD_TESTS=OFF -D BUILD_PYTHON=ON ..

I get the following message at the end: 
 Manually-specified variables were not used by the project:

    BUILD_PYTHON
    BUILD_TESTS

**Comment by edgarriba** [comment]
try to remove the spacing between -D options, type the following:
    
     cmake -DBUILD_TESTS=OFF -DBUILD_PYTHON=ON ..

**Comment by Adnino** [comment]
I've already tried this, it gives exactly the same warning and no python lib is generated at the end of compilation
