### ISSUE TITLE
Build error: No matching function for call to relative_pose_result

### ISSUE THREAD

**Issue by Ahmedest61** [mapillary/OpenSfM#654]
I am trying to build openSFM on Ubuntu 14.04 using anaconda and stuck on this issue. Any suggestion would be really helpful.
![openSFMError](https://user-images.githubusercontent.com/8188175/95718157-7bad3800-0c87-11eb-837b-f642b2582a0a.png)

**Comment by smathermather** [comment]
This link might contain the bread crumbs you need:
https://github.com/OpenDroneMap/ODM/issues/613

or just install on 16.04 or later... .

**Comment by YanNoun** [comment]
Has been answered and no reply in a while, closing.
