### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by ghost** [mapillary/OpenSfM#66]
Deleted

**Comment by paulinus** [comment]
It looks like the file /data/lund/reconstruction.meshed.json is missing. Did you run `bin/run_all data/lund` ?

**Comment by profdunny** [comment]
Yes.
Out put is "ls data/lund" as follows.
 
![screenshot from 2016-02-03 19 00 40](https://cloud.githubusercontent.com/assets/17042931/12778891/9ba5710c-caa8-11e5-9b64-e654775d51db.png)

**Comment by paulinus** [comment]
that looks ok. I can't see why the server wouldn't serve that file

**Comment by profdunny** [comment]
I'm sorry that I made a careless mistakes.
I gave the full path of the data directory.
I modified it and it works.

Thank you so much for your kind reply.

**Comment by profdunny** [comment]
OpenSfM is very cool and useful.
I hope that it is extended to spherical and online sequences.
(The branches of spherical and video seems not to be completed.)
