### ISSUE TITLE
building OpenSFM on Windows

### ISSUE THREAD

**Issue by xialang2012** [mapillary/OpenSfM#67]
Hi, I tried to build the full Open Drone Map (ODM) on Windows [https://github.com/OpenDroneMap/OpenDroneMap/issues/247], and the Meshing, Texture, UTM and ortho modules have been built successful.  Besides, pmvs(cmvs) are available on official website. So, the last problem is to build OpenSFM on Windows. I have tried to make OpenSFM works on Windows, but failed.
I wonder is it possible to make the OpenSFM runs on windows without big changes?

**Comment by ProfFan** [comment]
Please leave specific error messages and problems while you compile the software.

**Comment by xialang2012** [comment]
@ProfFan Have you already completed it?

**Comment by ProfFan** [comment]
No, but it allows others to try to reproduce your problem and help you resolve it.

**Comment by xialang2012** [comment]
@ProfFan Now, the problem is how to build a static library on Windows...

**Comment by kjkim-kr** [comment]
@xialang2012 hello, can you help me? I'm getting trouble in installing opensfm at win10..
