### ISSUE TITLE
Corrected metadata for cameras

### ISSUE THREAD

**Issue by syyh4** [mapillary/OpenSfM#70]
Hi there,

Opensfm is a great software and I am able to build a 3D point cloud using it. Here I just have a short question: did you guys generate corrected metadata for cameras (like what they did in bundle)? And if yes, is there a way to save those metadata?

Thanks,
S.Yao

**Comment by paulinus** [comment]
Hi @syyh4,
which metadata are you interested in? Is it the camera positions?

**Comment by syyh4** [comment]
Hi Pau,


Thanks for reply. That was really quick.

The metadata I'm interested in is R, t: the rotation, and translation of cameras.


Thanks,

Best Regards
--
Shizeng Yao
Graduate Student
Dept. of Computer Science
Univ. of Missouri-Columbia
Columbia, MO 65211-2060
(573) 818-5405


________________________________

**Comment by paulinus** [comment]
Rotation and translation for each shot are stored in the `reconstruction.json` file. Rotation is stored as an angle axis vector.

**Comment by syyh4** [comment]
Thank you so much!

I'll go check those!


Thanks,

Best Regards
--
Shizeng Yao
Graduate Student
Dept. of Computer Science
Univ. of Missouri-Columbia
Columbia, MO 65211-2060
(573) 818-5405


________________________________
