### ISSUE TITLE
returned with code 256.

### ISSUE THREAD

**Issue by ahmadusman** [mapillary/OpenSfM#71]
I am trying to run Open Drone Map on ubuntu 15.10 and getting the following error

ImportError: cannot import name csfm
b

quitting cause: 
    PYTHONPATH=/home/ahmadusman/opendronemap/lib/python2.7/dist-packages "/home/ahmadusman/opendronemap/src/OpenSfM/bin/import_bundler" opensfm --list list.txt
returned with code 256.

can anyone help me to resolve this issue

**Comment by edgarriba** [comment]
a couple of things, make sure that:
1. list.txt exists
2. libcsfm.so exists (did you succed compiling OpenSfM?)
3. check that your PYTHONPATH looks like [this](https://github.com/OpenDroneMap/OpenDroneMap/blob/edgarriba-cmake/configure.sh#L117)

**Comment by atomoclast** [comment]
I'm having similar issues as well. I do not see the .so file nor do I see list.txt

Lastly, it seems the file you linked to for one to check their PYTHONPATH doesn't exist....

**Comment by kcheung8** [comment]
I am having the same issue
