### ISSUE TITLE
Write image coordinate of KeyPoints in txt file 

### ISSUE THREAD

**Issue by farhadinima75** [mapillary/OpenSfM#717]
Hi there.
First of all, thanks for the great repo and application.

I have a question about how to save the image name and Keypoint id with the image coordinate of every matched keypoints. I know it's not a bug but I don't know where can I ask this.

Desired output txt file is like this:
image_name1, point_id1, img_coor_x, img_coor_y
image_name1, point_id2, img_coor_x, img_coor_y
and so on...

Any help would really appreciate.
Best regards, Nima.

**Comment by fabianschenk** [comment]
Hi @farhadinima75 ,

This information is stored in the `tracks.csv` file created when you run `create_tracks`. To figure out what is what, take a look at: https://github.com/mapillary/OpenSfM/blob/4948182bb3b1f3a71d19b64312a39449cc586911/opensfm/src/sfm/src/tracks_manager.cc#L28
Be aware that the coordinates there are normalized, so you have to denormalize them. There are already some methods for this in the Camera class.
Good luck
