### ISSUE TITLE
How to use OpenSfm+OpenMVS

### ISSUE THREAD

**Issue by Li-kewei** [mapillary/OpenSfM#718]
I did not find the export_mvs file under bin/, how can I import OpenSfm results into OpenMVS

**Comment by fabianschenk** [comment]
Hi,

I have never used this function but you should be able to run it with `bin/opensfm export_mvs DATASET`.
It should work the same way as `extract_metadata` and the other scripts. You can also take a look [`opensfm_run_all`](https://github.com/mapillary/OpenSfM/blob/master/bin/opensfm_run_all).

I hope it works now for you,
Fabian

**Comment by Li-kewei** [comment]
> Hi,
> 
> I have never used this function but you should be able to run it with `bin/opensfm export_mvs DATASET`.
> It should work the same way as `extract_metadata` and the other scripts. You can also take a look [`opensfm_run_all`](https://github.com/mapillary/OpenSfM/blob/master/bin/opensfm_run_all).
> 
> I hope it works now for you,
> Fabian

Thank you very much for your reply

**Comment by Li-kewei** [comment]
done
