### ISSUE TITLE
Work Flow through these functions in OpenSFM?

### ISSUE THREAD

**Issue by realhire** [mapillary/OpenSfM#73]
Hi, 
you did a mazing job. I do want to learn your project, not only about how to use it, but how to build it.
I have learned the basic algorithms in SFM, but more detail I want to understand. Your project give me a  good example. Do you have a work flow to show how these functions are connected?

I can see some of them, but not all of them.

Thanks,
realhire

**Comment by paulinus** [comment]
Hi,
you can see how to run the tool at the end of the readme. There is no doc describing the pipeline at the moment. We follow the standard incremental SfM pipeline so, reading [phototourism paper](http://phototour.cs.washington.edu/ModelingTheWorld_ijcv07.pdf) should help. I'm adding an issue for adding docs.
thanks,
pau
