### ISSUE TITLE
Export to OpenMVS does not work

### ISSUE THREAD

**Issue by c0ffymachyne** [mapillary/OpenSfM#739]
Hi, 
Export to OpenMVS does not seem to work. I have created a point cloud with OpenSfM and then used a command: 
`python3 bin/opensfm_main.py export_openmvs` . openmvs subfolder with a scene.mvs was created in undistorted folder but running `./ReconstructMesh -i scene.mvs` returns "Invalid Project" message.

**Comment by pierotofy** [comment]
Make sure you are running the latest OpenMVS (from the `develop` branch). There's been some project format changes in OpenMVS lately.
