### ISSUE TITLE
make: *** No rule to make target 'livehtml'. Stop. In Window

### ISSUE THREAD

**Issue by Gurumi432** [mapillary/OpenSfM#748]
I have tried last step failed in ubuntu, sudo su, anaconda, powershell, cmd at https://www.opensfm.org/docs/building.html

If I try "cd doc"
"the specified path could not be found"(or"system cannot find the path specified ") is displayed.
 
If I try "make livehtml" after make doc file
"make: *** No rule to make target 'livehtml'. Stop." is displayed.

What should I do?? 
I have been fighting this problem for 8 hours :(
please help me..

**Comment by fabianschenk** [comment]
Hi @Gurumi432 ,

There has been a recent but undocumented change and the documentation is now built by running `python3.8 setup.py build_doc`. See this [commit](https://github.com/mapillary/OpenSfM/commit/ae0058c04c7a5ac7a141a4d9f6acac27cdd85f8d#diff-814f155990403e624cae00fe50997cb10876aa790ea2f56a60c97821bb538efc).
Then just open `$OPENSFM_FOLDER/build/doc/html/` in your browser.

You can also have a look at our [online doc](https://www.opensfm.org/docs/dataset.html)

**Comment by Gurumi432** [comment]
> Hi @Gurumi432 ,
> 
> There has been a recent but undocumented change and the documentation is now built by running `python3.8 setup.py build_doc`. See this [commit](https://github.com/mapillary/OpenSfM/commit/ae0058c04c7a5ac7a141a4d9f6acac27cdd85f8d#diff-814f155990403e624cae00fe50997cb10876aa790ea2f56a60c97821bb538efc).
> Then just open `$OPENSFM_FOLDER/build/doc/html/` in your browser.
> 
> You can also have a look at our [online doc](https://www.opensfm.org/docs/dataset.html)

I am so sorry, I don't know where the python3.8 setup.py build_doc is

**Comment by Gurumi432** [comment]
If run python3.8 setup.py build_doc in ubuntu This error message occur "python3.8: can't open file 'setup.py': [Errno 2] No such file or directory"

**Comment by Gurumi432** [comment]
I have setup.py in anancond3 file and I run ```python3.8 setup.py build_doc```  at C:\Users\espre\anaconda3\pkgs\numpy-1.20.2-py39h6635163_0\Lib\site-packages\numpy\matrixlib

I get error message ```Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray' from partially initialized module 'numpy.core' (most likely due to a circular import) (/usr/lib/python3/dist-packages/numpy/core/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from numpy.distutils.core import setup
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray' from partially initialized module 'numpy.core' (most likely due to a circular import) (/usr/lib/python3/dist-packages/numpy/core/__init__.py) ```

**Comment by fabianschenk** [comment]
Hi @Gurumi432 ,

Sorry for not beint clear enough.
- Yes, I mean running in the terminal.
- In my case, I have `python` version `3.8` installed on my system and then I can run: `python3.8 setup build_doc`. If this doesn't exist for you, then try `python3 setup build_doc`, `python setup build_doc` or any `python` + your installed version.
- The issue with the `multiarray` probably has something to do with your `numpy` installation. You could try following these [instructions](https://stackoverflow.com/questions/53135410/importerror-cannot-import-name-multiarray).

Best,
Fabian

**Comment by fabianschenk** [comment]
No answer in a while, closing this issue.
