### ISSUE TITLE
[Question] Normalizing points on detect features.

### ISSUE THREAD

**Issue by Matesanz** [mapillary/OpenSfM#749]
Hello, and thank you in advance for the info, and thanks for your efforts in this awesome opensource project. :smile: 

I would like to know why in:

 https://github.com/mapillary/OpenSfM/blob/e026b0bf76e205460b99007fdae11108a1ad466e/opensfm/features.py#L237-L238

0.5 is summed to x and y when normalizing.
It may be a really stupid question but I can't figure out why :sweat_smile: (maybe bc it's Monday).

Nice regards.

**Comment by fabianschenk** [comment]
Hi @Matesanz ,

Have a look at the [documentation](https://www.opensfm.org/docs/geometry.html). If you write it the formula in a slightly different way: `pixel_coords[:, 0] - (w - 1) / 2` you can easily see where the `0.5.` comes from. 
This conversion maps the image to a normalized space, with the origin `(0, 0)` at the center of the image and not in the top left corner like in OpenCV.

I hope this helps,
Fabian

**Comment by Matesanz** [comment]
Hello @fabianschenk. 
 Thank you again. 
 
 Yes, I did already checked the docs. 
 My fault was not considering that width and height were also normalized.
 
 Sorry for my naive question.
 Nice regards. :slightly_smiling_face:
