### ISSUE TITLE
[Question] Incremental Reconstruction.

### ISSUE THREAD

**Issue by Matesanz** [mapillary/OpenSfM#751]
Hello and thank you for this amazing project.

As it can be found in the docs [Incremental reconstruction is implemented in openSFM](https://opensfm.readthedocs.io/en/latest/reconstruction_module.html). I would like to know if this algorithm is the one implemented on the reconstruction stage, or if it's a different pipeline that takes an image at a time to perform SfM (like in vSLAM algorithms) rather than taking all images at once.

Thank you in advance.
Best regards.

**Comment by YanNoun** [comment]
Hi @Matesanz,

The reconstruction stage runs classic incremental SfM given pre-computed point tracks.

Yann

**Comment by Matesanz** [comment]
Thanks :)
