### ISSUE TITLE
Extension to equirectangular images

### ISSUE THREAD

**Issue by profdunny** [mapillary/OpenSfM#77]
There are some modules extended for equirectangular images in the source code.
I am really interested in sfm using panoramic images. 
Is there any plan to release a whole sfm system for equirectangular images in the future, or is it already possible to perform sfm for equirectangular images?

**Comment by paulinus** [comment]
The functionality is there already. It works with no changes as long as the images contain `gpano` information.
Things you may want to change to improve the results:
- Make sure images are detected as equirectangular. Look at the generated file `camera_models.json` and see if `projection_type` is `equirectangular`. If it is not, rename that file to `camera_models_overrides.json` and edit the projection type.
- Increase the image resolution and number of features to extract. For example set
```
feature_min_frames: 16000
feature_process_size: 4000
```
 in `config.yaml`

**Comment by dunny2016** [comment]
Thank you for your quick reply.
It was thanks to your advice that I can perform sfm for equirectangular images.
(It is necessary for me to edit the projection type.)

I like this the best in many sfm libraries.
I hope further development of this project!

**Comment by paulinus** [comment]
@salus-sage You need to use more than 1 image to run OpenSfM

closing the issue since the original problem is solved
