### ISSUE TITLE
Outdated documentation (viewer)

### ISSUE THREAD

**Issue by kwea123** [mapillary/OpenSfM#775]
In https://www.opensfm.org/docs/using.html the viewer is still called by "browsing http://localhost:8000/viewer/reconstruction.html#file=/data/berlin/reconstruction.meshed.json", but this instruction doesn't work at all now.

After looking around by myself, I found the correct way to work, which is going to [viewer](https://github.com/mapillary/OpenSfM/tree/master/viewer) directory and follow the instruction there. The viewer seems to be updated recently, so please update the doc to match the current code, thanks.

**Comment by fabianschenk** [comment]
Hi @kwea123 ,

Thanks for reporting this issue. We will try to update the documentation.
