### ISSUE TITLE
Triangulate image points based on the reconstruction

### ISSUE THREAD

**Issue by LukasBommes** [mapillary/OpenSfM#777]
First of all, thanks for developing OpenSfM. I just tried it out today for my application and it works very well.

I want to solve the following problem: Given a set of known image points (in pixel coordinates) in two adjacent shots, I want to triangulate them into the world frame. All my images are already undistorted before feeding them into OpenSfM.

I tried it using the following function. R1(2), t1(2) are taken from the reconstruction and inverted (R = R.T, t = -R.T.dot(t)) before being passed into this function. [The double inversion is only needed because I use the inverted convention and the function below at other points in my projects].

```
def triangulate_map_points(last_pts, current_pts, R1, t1, R2, t2, camera_matrix):
    """Triangulate 3D map points from corresponding points in two
    keyframes. R1, t1, R2, t2 are the rotation and translation of
    the two key frames w.r.t. to the map origin.
    """
    # create projection matrices needed for triangulation of 3D points
    proj_matrix1 = np.hstack([R1.T, -R1.T.dot(t1)])
    proj_matrix2 = np.hstack([R2.T, -R2.T.dot(t2)])
    proj_matrix1 = camera_matrix.dot(proj_matrix1)
    proj_matrix2 = camera_matrix.dot(proj_matrix2)

    # triangulate new map points based on matches with previous key frame
    pts_3d = cv2.triangulatePoints(proj_matrix1, proj_matrix2, last_pts.reshape(-1, 2).T, current_pts.reshape(-1, 2).T).T
    pts_3d = cv2.convertPointsFromHomogeneous(pts_3d).reshape(-1, 3)
    return pts_3d
```

The results I get are completely off. I tried using the camera matrix as per OpenCV convention and also one following the OpenSfM settings.

It would be great if you could hint me at how I could triangulate image points using the reconstruction output. Maybe, one of the OpenSfM internal functions could be a better choice also.

**Comment by LukasBommes** [comment]
It turned out, I made another mistake.

Triangulation works perfectly fine with the reconstructed poses and with using the camera matrix following OpenCV convention (i.e. focal length and image center in pixel units).

**Comment by sriramreddyM** [comment]
Hello @LukasBommes I’m also trying to find the 3D pts using the selected points from two adjacent images. I tried using the above function you have given, but I with struck with an error. Dimensions mismatch at “proj_matrix1 = np.hstack([R1.T, -R1.T.dot(t1)])”., (3x3) & (3,).

I got the R&t using,
```
R = shot.pose.get_rotation_matrix()
t = shot.pose.translation
```
Are they correct? And Can you explain why you take t = -R.T.dot(t) ?
