### ISSUE TITLE
dependency conflicts

### ISSUE THREAD

**Issue by johnwlambert** [mapillary/OpenSfM#790]
Hi all, thanks for making this great library. I'm seeing the following dependency conflict.

```
The conflict is caused by:
    The user requested Pillow>=8.1.1
    fpdf2 2.1.0 depends on Pillow<=8 and >=4
```
when installing requirements.txt. Looks like the versions may not be compatible.

**Comment by fabianschenk** [comment]
This will hopefully be resolved with this PR: https://github.com/mapillary/OpenSfM/pull/772

**Comment by lthiet** [comment]
In the meantime, using Pillow 8.0.0 seems to cause no problem.
