### ISSUE TITLE
Spherical Coordinate System and Pose Format

### ISSUE THREAD

**Issue by johnwlambert** [mapillary/OpenSfM#793]
Hi OpenSfM maintainers, thanks for the excellent library. Two questions for you:

1. What is the camera coordinate system for a reconstruction from equirectangular projection images? i.e. how do x, y, z map to the panorama pixels?

2. I wanted to confirm that the (R,t) parameterized in the poses of reconstruction.json represents the camera extrinsics (cTw) not world poses (wTc) i.e. 
```
p_camera = cTw * p_world
```
(from "rotation" and "translation" fields).

Thanks!

**Comment by YanNoun** [comment]
Hi @johnwlambert,

1. You can refer to https://opensfm.readthedocs.io/en/latest/geometry.html#spherical-camera for modeling of equirectangular projection and this issues for another answer : https://github.com/mapillary/OpenSfM/issues/794.

2. Yes, poses of `reconstruction.json` represents the camera extrinsics as you can see here : https://github.com/mapillary/OpenSfM/blob/main/opensfm/io.py#L106 and also here https://github.com/mapillary/OpenSfM/blob/main/opensfm/src/geometry/pose.h#L27

Let me know if that answer your questions.

Yann

**Comment by johnwlambert** [comment]
Yes, this helps, thank you very much @YanNoun.
