### ISSUE TITLE
Spherical camera convention

### ISSUE THREAD

**Issue by melhashash** [mapillary/OpenSfM#794]
Could you please explain the axes of the spherical camera and the representation [here](https://opensfm.readthedocs.io/en/latest/geometry.html#spherical-camera)?

**Comment by YanNoun** [comment]
Hi @melhashash,

For a spherical camera, you should see it as a sphere with arbitrary radius in space having the image mapped onto it. The center of the sphere is the camera position with the Z axis pointing towards the pixel of the center of the 2D image, and X/Y pointing left/up in the 2D image.

Maybe a picture is worth these words :
![screenshot-devvm1465 cln0 facebook com_8087-2021 09 20-10_54_06](https://user-images.githubusercontent.com/39743653/133987566-20b8c5bd-7ad9-49cf-9769-22ba5d621c52.png)


Let me know if that's more clear.

Yann

**Comment by melhashash** [comment]
Thanks for your response. The image shows X right, but in the description you mentioned X left.

**Comment by melhashash** [comment]
@YanNoun Thanks for your reply!

BTW, are you familiar with an existing pipeline that supports dense reconstruction for spherical cameras?

**Comment by YanNoun** [comment]
Hi @melhashash,

OpenSfM can run dense reconstruction with spherical cameras.

As an alternative, you can also export OpenSfM's SfM reconstruction to OpenMVS using OpenMVS exporter (`opensfm export_openmvs`) and run OpenMVS instead. 

Yann

**Comment by YanNoun** [comment]
Yes, exactly, in both cases, OpenSfM's `undistort` command will generate undistorted perspective views first and foremost. For spherical, it will extract 4 perspective views (top and bottom views are ignored).
