### ISSUE TITLE
Help about the opensfm module can not be found

### ISSUE THREAD

**Issue by xialang2012** [mapillary/OpenSfM#80]
Hi, @paulinus 

I am a new one about the python and I have a problem when I try to run the OpenSfM on Windows.
The command like this

`python ./bin/opensfm detect_features data/lund/`

and it showed me

> ImportError: No module named opensfm
>     file, path_name, etc = imp.find_module(main_name, dirs)
> ImportError: No module named opensfm
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "D:\python27\lib\multiprocessing\forking.py", line 380, in main
>     Traceback (most recent call last):
> prepare(preparation_data)
>   File "<string>", line 1, in <module>
>   File "D:\python27\lib\multiprocessing\forking.py", line 503, in prepare
>   File "D:\python27\lib\multiprocessing\forking.py", line 380, in main
>         file, path_name, etc = imp.find_module(main_name, dirs)
> prepare(preparation_data)
> ImportError  File "D:\python27\lib\multiprocessing\forking.py", line 503, in pre
> pare
> : No module named opensfm
> forrtl: error (200): program aborting due to control-C event
> Image              PC                Routine            Line        Source
> 
> kernel32.dll       00000000771E4B93  Unknown               Unknown  Unknown
> kernel32.dll       00000000771A59ED  Unknown               Unknown  Unknown
> ntdll.dll          00000000773DB371  Unknown               Unknown  Unknown
>     file, path_name, etc = imp.find_module(main_name, dirs)
> ImportError: No module named opensfm

I have built the csfm.pyd on Windows, and I run 
`python setup.py build `
and 
`python setup.py install`
to install the opensfm to the site-packages
Then I tried to find_module
`>>> imp.find_module(cv)`
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'cv' is not defined

`>>> imp.find_module('cv')`

> (<open file 'D:\\python27\\DLLs\\cv.py', mode 'U' at 0x0000000002362420>, 'D:\\p
> ython27\\DLLs\\cv.py', ('.py', 'U', 1))

`>>> imp.find_module('opensfm')`

> (None, 'opensfm', ('', '', 5))

`>>> imp.find_module('csfm')`
> (<open file 'D:\\python27\\DLLs\\csfm.pyd', mode 'rb' at 0x0000000002362420>, 'D
> :\\python27\\DLLs\\csfm.pyd', ('.pyd', 'rb', 3))

**Comment by paulinus** [comment]
I looks like opensfm is installed in a path that is not on your `PYTHONPATH`.  You will need to find the path where opensfm is installed and add it to the `PYTHONPATH`. I've never done that in windows, but these instructions should help https://docs.python.org/2/using/windows.html

Alternatively, you can add the path to the opensfm source code, and skip the installation.

Also, the tests importing `cv` probably fail because the opencv package is called `cv2`.

Thanks for trying to build on windows!

**Comment by xialang2012** [comment]
I have check the pythonpath, it is all right, as shown below

> Microsoft Windows 
> C:\Users\xialang2012>python
> Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (
> AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import opensfm
> >>>
> >>> import pyopengv
> >>>
> >>> import cv
> >>>
> >>> import csfm
> >>>
> 

But when I run `python ./bin/opensfm detect_features data/lund/`, it does not work.

**Comment by xialang2012** [comment]
The result for
` imp.find_module('opensfm')` 

> (None, 'opensfm', ('', '', 5))

is resonable, for the document from the https://docs.python.org/2/library/imp.html

> If the module is a package, file is None, pathname is the package path and the last item in the description tuple is PKG_DIRECTORY.

**Comment by paulinus** [comment]
It looks like importing does not work when using multiprocessing. It might be that the pythonpath is set differently on the forked processes. I have no experience with that.

Could you try using a single process by setting
```
processes: 1                  # Number of threads to use
```
in `data/lund/config.yaml`?

**Comment by xialang2012** [comment]
Yes, when setting the process to 1, it works well.

> C:\Users\xialang2012\Documents\Visual Studio 2013\Projects\ODM-Win\OpenSf
> n ./bin/opensfm detect_features data/lund/
> 2016-06-14 16:32:07,628 Extracting ROOT_HAHOG features for image 001.jpg
> Namespace(command='detect_features', dataset='data/lund/')
> 2016-06-14 16:32:07,628 Extracting ROOT_HAHOG features for image 002.jpg
> Namespace(command='detect_features', dataset='data/lund/')
> 2016-06-14 16:32:07,628 Extracting ROOT_HAHOG features for image 003.jpg
> 2016-06-14 16:32:10,015 Found 9906 points in 2.35800004005s
> Namespace(command='detect_features', dataset='data/lund/')
> 2016-06-14 16:32:10,875 Extracting ROOT_HAHOG features for image 004.jpg
> 2016-06-14 16:32:13,253 Found 9755 points in 2.33899998665s

**Comment by xialang2012** [comment]
Using pool on Windows : http://bugs.python.org/issue10845

**Comment by kjkim-kr** [comment]
hello, @xialang2012 

It's too late to ask you something, but I have troubles when I install OpenSfM at Windows 10.
So.,. can I get some tips or guides, how can I install opensfm at win10 successfully?

I have, and did with these items
Visual Studio - Fail
mingw - Fail

Thanks:)
