### ISSUE TITLE
[Question] Rolling Shutter Correction ?

### ISSUE THREAD

**Issue by pierotofy** [mapillary/OpenSfM#803]
Hey all :hand:

just wondering if rolling shutter correction is going to eventually be implemented in OpenSfM (is it on the roadmap?)

I think this might be beneficial to improve accuracy for certain cases where cheap CMOS cameras are used to collect linear corridor datasets.

**Comment by YanNoun** [comment]
Hi @pierotofy ,

We don't have short-mid -terms plans to do so.

Yann

**Comment by pierotofy** [comment]
Thanks @YanNoun :pray:
