### ISSUE TITLE
Simple question about OpenSfM algorithm

### ISSUE THREAD

**Issue by ghost** [mapillary/OpenSfM#81]
Hello. I'm one of OpenDroneMap users, and I want to study and understand the OpenSfM's algorithm exactly. I wonder there is the academic paper or algorithm explanation document about it. I'll also thank you if you suggest some adequate documents for my studying.

**Comment by EderSantana** [comment]
It is all based on the Structure from Motion pipeline, here is quick video explanation https://www.youtube.com/watch?v=i7ierVkXYa8
a more detailed explanation can be found in the book "multiple view geometry in computer vision" and other tutorials online
