### ISSUE TITLE
Error: Building on windows 10

### ISSUE THREAD

**Issue by Alotaibiuop** [mapillary/OpenSfM#839]
using:
VS 2017
windows 64bit
python 3.8
-----------------------

I am getting below error while trying to 
python setup.py build
-----------------------

`"F:\development\OpenSfM\cmake_build\ALL_BUILD.vcxproj" (default target) (1) ->
"F:\development\OpenSfM\cmake_build\bundle\bundle_test.vcxproj" (default target) (6) ->
"F:\development\OpenSfM\cmake_build\geometry\geometry.vcxproj" (default target) (7) ->
(ClCompile target) ->
  f:\development\opensfm\opensfm\src\geometry\src\triangulation.cc(207): error C2039: 'int32': is not a member of 'ceres' [F:\development\OpenSfM\
cmake_build\geometry\geometry.vcxproj]
  f:\development\opensfm\opensfm\src\geometry\src\triangulation.cc(207): error C2065: 'int32': undeclared identifier [F:\development\OpenSfM\cmake
_build\geometry\geometry.vcxproj]
  f:\development\opensfm\opensfm\src\geometry\src\triangulation.cc(207): error C2923: 'std::vector': 'int32' is not a valid template type argument
 for parameter '_Ty' [F:\development\OpenSfM\cmake_build\geometry\geometry.vcxproj]
  f:\development\opensfm\opensfm\src\geometry\src\triangulation.cc(207): error C3203: 'allocator': unspecialized class template can't be used as a
 template argument for template parameter '_Alloc', expected a real type [F:\development\OpenSfM\cmake_build\geometry\geometry.vcxproj]
  f:\development\opensfm\opensfm\src\geometry\src\triangulation.cc(166): error C2512: 'std::vector': no appropriate default constructor available
[F:\development\OpenSfM\cmake_build\geometry\geometry.vcxproj]

    7 Warning(s)
    5 Error(s)

Time Elapsed 00:00:14.50
Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    build_c_extension()
  File "setup.py", line 51, in build_c_extension
    subprocess.check_call(['cmake', '--build', '.', '--config', 'Release'], cwd='cmake_build')
  File "f:\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release']' returned non-zero exit status 1.`

**Comment by fabianschenk** [comment]
HI @Alotaibiuop ,

could you try with the most recent version? 
#840 should solve your issue

Best,
Fabian

**Comment by Alotaibiuop** [comment]
Hi @fabianschenk,
Thank you, Working now.
