### ISSUE TITLE
Camera Intrinsic

### ISSUE THREAD

**Issue by zxcv0258tw** [mapillary/OpenSfM#84]
Hello, I wonder to know how to get the camera Intrinsic matrix in reconstruction.json 
Thanks!

**Comment by EderSantana** [comment]
look for camera_models.json actually

**Comment by paulinus** [comment]
`camera_models.json` contains the initial values of the intrinsic camera parameters. You can find the optimized values after the SfM in the `reconstruction.json` file.
The file will have a section with the cameras and the corresponding values. For Berlin, you should get something similar to
```
        "cameras": {
            "v2 apple iphone 4s back camera 4.28mm f/2.4 3264 2448 perspective 0.9722": {
                "focal_prior": 0.9722222222222222, 
                "width": 3264, 
                "k1": 0.013892053518536781, 
                "k2": 0.0011525471316393722, 
                "k1_prior": 0.0, 
                "k2_prior": 0.0, 
                "projection_type": "perspective", 
                "focal": 0.9587140578983568, 
                "height": 2448
            }
        }, 
```
The focal here corresponds to the ratio between the focal length and the sensor size. So if you need the focal length in pixel you should compute `focal * max(width, height)`. The way you build the camera matrix from these values depends on the coordinate system you use for the images. If you use pixel coordinates with (0,0) on the top left, you would use something similar to
```
K = [ [focal * width, 0, width / 2],
      [0, focal * width, height / 2],
      [0, 0, 1] ]
```
(assuming `width = max(width, height)`)

**Comment by zxcv0258tw** [comment]
Thanks a lot !

**Comment by fasiha** [comment]
I asked this question in a [comment on the Mapillary blog](http://blog.mapillary.com/update/2016/10/31/denser-3d-point-clouds-in-opensfm.html#comment-3032382861) but, what are `k1` and `k2`? Do they enter the intrinsic matrix at all?
