### ISSUE TITLE
Undistorted images have shift offset

### ISSUE THREAD

**Issue by VagosGrigoropoulos** [mapillary/OpenSfM#844]
[](url)Running opensfm pipeline throught ODM , and i use undistorted images to some reverse colinearity function.I reallized that for some reason undistorted image have shift black offset that seems to be the same for all the images.Is this shift offset normal?and if yes is there a way to define it.If i can define this shift for x and y ,then i can reshift the image back to normal.Sample 
![P5714505 jpg](https://user-images.githubusercontent.com/39879424/148041508-72fccda5-39e5-45fe-ac31-67f080fab592.jpg)

Best regards

**Comment by fabianschenk** [comment]
Hi @VagosGrigoropoulos ,

The black border comes from the undistortion process. Why it looks like that I cannot say without knowing anything about the camera model or seeing the original image.
We use OpenCV's undistortion as you can see:
https://github.com/mapillary/OpenSfM/blob/7b455d9c424c82d96fc60d57a9c1dbf024aa8b3b/opensfm/undistort.py#L157-L166

It's probably best if you just copy the camera parameters and the map and experiment in a separate python script.

Good luck

**Comment by YanNoun** [comment]
Hi @VagosGrigoropoulos,

This is expected if the camera model you're using has any non-zero principal point shift (`cx`/``cy`). When mapping from the undistorted image to the distorted image, some pixels might be out of the domain of the distorted image and we use a black value as default value for such pixels.

The shift in pixels is {`cx`, `cy`} . max(width, height).

Let me know if that helps,

Yann

**Comment by VagosGrigoropoulos** [comment]
Thanks @YanNoun ,indeed this is the shift values and i guess negative values applying respectivelly.For now i have only brown camera sample data to test.Is this standard apply for all camera types?
