### ISSUE TITLE
Unable to load reconstruction info from dataset.py

### ISSUE THREAD

**Issue by siddharthbhushan** [mapillary/OpenSfM#845]
Hi, 

I am pretty new to this and trying this for the first time. So please bear with me if my question is dumb. 

I am trying to use the dataset script to use the reconstruction info for the berlin dataset. However, when I run the script I keep running into one error : 

 ```
 File "/home/OpenSfM/opensfm/dataset.py", line 60, in load_config
    if self.io_handler.isfile(config_file_path):
AttributeError: 'str' object has no attribute 'isfile'
```

I understand that the string object doesn't know what to do with 'isfile' attribute. But I do not know how to fix it. I tried a few ideas that I got of some other forums but nothing seems to work. I would be grateful if anyone could provide me with any kind of guidance on this. 

BTW, I am using this on Ubuntu20.04 with python 3.8, if that info helps.

**Comment by fabianschenk** [comment]
Hi @siddharthbhushan ,

Could you please clarify what command you ran? `dataset.py` by itself is not a script but a bunch of class definitions.
There's also the `compute_statistics` action that you can run similar to `create_tracks`, `extract_features`,...

If you want to get information about a reconstruction you could write a script that looks something like this (untested!):
```
from opensfm import dataset

data = dataset.DataSet("/home/..../data/berlin")

reconstructions = data.load_reconstruction()
reconstruction = reconstructions[0] 

print(f"Number of Shots: {len(reconstruction.shots)}")
```

**Comment by siddharthbhushan** [comment]
Hi @fabianschenk,

Thank you for those ideas. I will try them.  But what I am doing right now is quite similar to this. Here is a small code fragment. 

```import os
import os.path
import time

import numpy as np
import open3d as o3d
import torch
from opensfm import dataset, features

image_dir = '/home/OpenSfM/data/berlin/images'
sfm_dir = '/home/OpenSfM/data/berlin/undistorted'
save_dir = '/home/OpenSfM/data/berlin/output'
print('Importing ply file')
now = time.time()
if ply_filename is None:
        ply_filename = '%s/depthmaps/merged.ply' % (sfm_dir)
xyz_all, rgb_all = ply_reader(ply_filename)
print('Imported in', time.time() - now, "seconds")
point_idx_all = np.array([idx for idx in range(xyz_all.shape[0])])
print('Found %d points' % (xyz_all.shape[0]))

ds = dataset.DataSet(image_dir, sfm_dir)
reconstruction = ds.load_reconstruction()[0]

os.makedirs(output_dir, exist_ok=True)
```

I am actually using this for wc-vid2vid project published by NVidia on some custom data. So once the data is loaded, we play around little with the points to create unprojections as input for a neural network along with the segmentation maps. But I am stuck because I cannot load the reconstruction to create those unprojections. The code fragment above is a part of a larger code with a lot other functions that are working fine, so I skipped those. I can share those also if you think they will help in better assessing the problem.

**Comment by siddharthbhushan** [comment]
[project_points.zip](https://github.com/mapillary/OpenSfM/files/7825247/project_points.zip)
Here's the complete script anyway.

**Comment by fabianschenk** [comment]
Hi @siddharthbhushan ,

Thanks for sharing the code. Now it's obvious why it doesn't work.

You construct the `Dataset` with two parameters and the second one is for the `io_handler`. So you set the `io_handler` to a `str` (`sfm_dir`) and that's why it throws. 

Here's the definition:
```
class DataSet(DataSetBase):
    ....
    def __init__(self, data_path: str, io_handler=io.IoFilesystemDefault) -> None:
    ...
```

Just use:
```
...
ds = dataset.DataSet("/home/OpenSfM/data/berlin")
...
```

Best,
Fabian

**Comment by siddharthbhushan** [comment]
Hi @fabianschenk 

Now that you point it out, it was a pretty dumb mistake to make. Thank you for pointing it out. It working fine now.
