### ISSUE TITLE
Mistake in Geometry Documentation Equations for Brown-Conrady Distortion

### ISSUE THREAD

**Issue by goodsman** [mapillary/OpenSfM#846]
The equations for tangential distortion in the x and y dimensions are incorrect under the Brown Camera heading in the Geometry documentation page.  These are the fifth and sixth equations under the Brown Camera heading. The final term for tangential distortion in the x dimension should be (p2)(r^2 + 2x^2). Similarly the final term for tangential distortion in the y dimension should be (p1)(r^2 + 2y^2). In both cases the x and y are not squared in the documentation but they should be. This can be verified by going back to the Brown-Conrady formulation and also by looking at lines 817 to 825 in the C code: camera_distortions_functions.h

**Comment by fabianschenk** [comment]
Hi @goodsman ,

Thanks for pointing this out.

For the sake of completeness, [this](https://opensfm.org/docs/geometry.html#brown-camera) the problematic section in the documentation
![image](https://user-images.githubusercontent.com/13796836/148745896-6a247a20-3468-4945-89e7-5dd2f2fec635.png)

I'll try to fix it asap.

Thanks

**Comment by thaytan** [comment]
Shouldn't the last terms in equations 5 & 6 be `x_n^2` and `y_n^2` (normalised x,y) ?
