### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by oradzhabov** [mapillary/OpenSfM#851]
Hi.
Starting from tag 268 I see not matching interfaces between calling method
https://github.com/OpenDroneMap/OpenSfM/blob/c90b0344a725c6048883e390b771da46999400fc/opensfm/commands/undistort.py#L11

and implementation
https://github.com/OpenDroneMap/OpenSfM/blob/c90b0344a725c6048883e390b771da46999400fc/opensfm/actions/undistort.py#L15

param imageFilter becames False and then raise exception in 
https://github.com/OpenDroneMap/OpenSfM/blob/c90b0344a725c6048883e390b771da46999400fc/opensfm/undistort.py#L113

**Comment by pierotofy** [comment]
The code in question is part of modifications made on OpenDroneMap's fork of OpenSfM; the mapillary team probably cannot help here, so this issue should probably be closed. For questions about OpenDroneMap's forks, visit https://community.opendronemap.org/c/developers-chat/21 :pray:

**Comment by fabianschenk** [comment]
Thanks @pierotofy for pointing this out.
@oradzhabov Please, ask in the relevant `OpenDroneMap` github issues.

Closing this issue. now
