### ISSUE TITLE
Does this works with the Python 3?

### ISSUE THREAD

**Issue by hilman-dayo** [mapillary/OpenSfM#86]
I am using a Python 3 wrapped virtual environment for my OpenCV related works. Means all of my packages is inside the environment's site-packages. Tried to build this project, but it seems that OpenGV python wrapper is just for the Python 2. Is this correct? Means that I must use Python 2 for this?

I am beginner in this whole thing, so pardon me if I am wrong, or this question is too trivial.

**Comment by paulinus** [comment]
Yes, opensfm is currently Python 2 only. I would love to see it working in Python 3, but never tried it.

It has to be possible to build OpenGV wrapper for Python 3. It requires some time and investigation.

**Comment by hilman-dayo** [comment]
OK. Thanks for the reply.
