### ISSUE TITLE
Could I get some code information of matching point from this library ?

### ISSUE THREAD

**Issue by BaeSukkyoung** [mapillary/OpenSfM#869]
Could I get some code information of matching point from this library ?
Matching point is that overlapped parts in photos for 3D modeling.

**Comment by fabianschenk** [comment]
Hi @BaeSukkyoung ,

Understanding the code base requires effort from your side, so just look at the action [`match_features.py`](https://github.com/mapillary/OpenSfM/blob/main/opensfm/actions/match_features.py) and then [`matching.py`](https://github.com/mapillary/OpenSfM/blob/main/opensfm/matching.py) to see the code used for matching.
There's also the [documentation](https://opensfm.org/docs/using.html#reconstruction-commands).

Good luck,
Fabian
