### ISSUE TITLE
Can this library being used for SLAM like project?

### ISSUE THREAD

**Issue by hilman-dayo** [mapillary/OpenSfM#88]
I have one project in mind. Can I achieve something like [this](https://www.youtube.com/watch?v=QqnInxq1g0w&t=1m31s ) with this library? Kinda like give that 3D perception to it. Kind of like SLAM, but no need for mapping. Just self-localizing and detect objects in surrounding.

I want to experiment and try to search for a good methods for my project. I am still new to this, so still kind of lost.

**Comment by paulinus** [comment]
OpenSfM works with still images and does point matching without assuming any temporal continuity. You can sample a video and feed the images to OpenSfM, but it is going to be slower than using a SLAM tool.

If you want to work on realtime SLAM, I would recommend you using https://github.com/raulmur/ORB_SLAM2
