### ISSUE TITLE
Jinja 2 imports have been deprecated

### ISSUE THREAD

**Issue by Matesanz** [mapillary/OpenSfM#885]
# Description

Project can no longer be built due to [Jinja 2 (sphinx dependeny) imports have been deprecated](https://github.com/sphinx-doc/sphinx/issues/10291): 

# How to replicate:

```
git clone --recursive git@github.com:mapillary/OpenSfM.git
cd OpenSfm
docker build -t opensfm .
```

# Solution

Pint to `Jinja2<3.1` in requirements.txt

**Comment by mlopezantequera** [comment]
Thanks @Matesanz . Fixed by bumping sphinx instead here 151c3f5d31d611f2b6634a82247e7c414f4878e7
