### ISSUE TITLE
Depth information

### ISSUE THREAD

**Issue by zxcv0258tw** [mapillary/OpenSfM#89]
Hello, is there a way to get image's depth information?
In reconstruction.py, the function 'back_project' seems that it can return the 3D coordinate when input image coordinate (u, v).
But I don't how to get the depth information, thanks!

**Comment by nwcimaszewski** [comment]
I know that you can get the fronto-parallel depth of an individual point by feeding its coordinates into pose.transform in types.py.  This will give you the camera coordinates, and the third coordinate will be the depth in the image.  Not really sure if this is what you need but I was looking for something similar and this helped.

**Comment by paulinus** [comment]
Hi @zxcv0258tw, OpenSfM computes the position of the cameras, and the position of a sparse set of points. As of now, it does not compute the depth of all pixels, we are working on that on the `dense` branch, but it is not ready yet.

If you need some coarse depthmaps, you can interpolate the depth of the sparse point cloud using a Delaunay triangulation for example.

**Comment by paulinus** [comment]
The dense branch has been merged, and OpenSfM does compute depthmaps now. You can use the command `compute_depthmaps`, see http://opensfm.readthedocs.io/en/latest/using.html#quickstart
