### ISSUE TITLE
Questions about Normalized Image Coordinates

### ISSUE THREAD

**Issue by zpw6106** [mapillary/OpenSfM#891]
Hi Author, I have some doubts about that openSfM utilize the normalized coordinates. After I took a closer look at the functions for camera projection in the final step, The [Affine](https://github.com/mapillary/OpenSfM/blob/main/opensfm/src/geometry/transformations_functions.h#L15) functions will transform the distorted coordinates to pixel coordinates, so there is no step transform to normalized coordinates.  This means that we  are still using pixel coordinates in the BA optimization process not [normalized coordinates](https://opensfm.org/docs/geometry.html), and as your documentation says that normalized coordinates are independent of the resolution of the image and give better numerical stability for some multi-view geometry algorithms than pixel coordinates. Do I need to add an additional projection step to get it right? like the [code](https://github.com/mapillary/OpenSfM/blob/main/opensfm/src/geometry/camera.h#L97)  

 Hope to get your reply, thanks!

**Comment by YanNoun** [comment]
Hi @zpw6106 ,

OpenSfM's camera parameters are also normalized, so the Affine function will just apply a normalized focal length and a normalized principal point. OpenSfM never uses pixel coordinates.

Let me know if that helps,

Yann
