### ISSUE TITLE
It is possible to develop multi-camera reconstruction with openSFM?

### ISSUE THREAD

**Issue by oximi123** [mapillary/OpenSfM#895]
I am thinking about such a situation: we have serveral(let's say, 3) synchronized and calibrated cameras, at each time step we got 3 frames from these cameras, is it possible to create 3 threads to 1) read frames in parellel. 2) detection features in parelell using openSFM?
I have this question because I see openSFM also create multi-threads when perform single SFM pipeline , will these threads have collision with the 3 three parellel thread I've created?

**Comment by fabianschenk** [comment]
Hi @oximi123 ,

Reading the images and feature detection is already parallelized afaik.
OpenSfM is thought to run as an offline system, i.e. it's expected that you have all the images before you start.

If you plan to create an online system, then maybe check-out some SLAM implementations.

Best,
Fabian
