### ISSUE TITLE
Negative coordinate for Dataset.points

### ISSUE THREAD

**Issue by oximi123** [mapillary/OpenSfM#896]
I found negative coordinate in **DataSet.points** when loading features of berlin dataset. After I apply **denormalized_image_coordinates**() to these points they still contain negative coordinate. I wonder what's the **orgin** of the image? Is it the left top or the center of the image?

**Comment by fabianschenk** [comment]
HI @oximi123,

You find the answers in the documentation: https://opensfm.org/docs/geometry.html

Normalized coordinates have the origin in the middle of the image, while pixel coordinates are in the top-left corner.
In case you mean `reconstruction.points`, then this refers to 3D points and image coordinates.

Best,
Fabian
