### ISSUE TITLE
Question about coordinate systems in OpenSFM

### ISSUE THREAD

**Issue by ZhipengCai** [mapillary/OpenSfM#897]
Hi,
In the reconstruction result (reconstruction.json), the pose are organized in 
1) A reference gps location (lat_r, lng_r, alt_r)
{
    "latitude": 37.78792552034548,
    "longitude": -122.40752822823013,
    "altitude": 0
}
2) A rotation (rotx, roty, rotz) and translation (tx, ty, tz)
 "rotation": [
                    1.3861826611802066,
                    0.4302363756364182,
                    -0.598522101985362
                ],
                "translation": [
                    -13.238108134524326,
                    6.379459122927627,
                    -1.856486585355776
                ],
3) A local gps location (lat_l, lng_l, alt_l)
              "gps_position": [
                  11.871415622462887,
                  11.182667637578561,
                  1.9999791318550706
              ],
I wonder how we can convert the rotation and translation and the local gps_position to
1) an absolute gps location and an absolute camera orientation (with specified camera orientation axes direction and the default camera orientation if no rotation is applied)
2) relative camera positions and orientation w.r.t. the reference, where the origin is at (lat_r, lng_r, alt_r), and the axes for translation and rotation are (x--> pointing to east,  y --> pointing north, z--> pointing up)?

Also, in Mapillary API, there are computed_geometry (lat, lng, alt) and computed_rotation (rot_xc, rot_yc, rot_zc) fields for each image, how can we convert the reconstruction pose to these values and how we can convert them back to the reconstructed coordinate system? 

Finally, the Mapillary API says that the computed_geometry (lat, lng, alt) and computed_rotation (rot_xc, rot_yc, rot_zc) are already from OpenSFM, so should we expect a similar level of accuracy as the computed poses if we run OpenSFM on the same set of images from Mapillary API? And if so, how can we convert a set of computed geometry and computed rotation to relative poses (currently I do not understand what the rotation axis is for each computed rotation) between multiple cameras?

Thanks!

**Comment by fabianschenk** [comment]
Hi @ZhipengCai ,

The reference gps location is typically the average of the GPS measurements of all the shots. This essentially constructs a new coordinate system at the center of the shots. All the GPS locations for the shots are now defined in this local reference system.

To get from the local GPS coordinates to the global ones, you can use the `reconstruction.reference.to_lla()` from `geo.py`:
```
    def to_lla(self, x, y, z):
        """Convert topocentric x, y, z to lat, lon, alt."""
        return lla_from_topocentric(x, y, z, self.lat, self.lon, self.alt) reconstruction.reference
```

**Comment by ZhipengCai** [comment]
> Hi @ZhipengCai ,
> 
> The reference gps location is typically the average of the GPS measurements of all the shots. This essentially constructs a new coordinate system at the center of the shots. All the GPS locations for the shots are now defined in this local reference system.
> 
> To get from the local GPS coordinates to the global ones, you can use the `reconstruction.reference.to_lla()` from `geo.py`:
> 
> ```
>     def to_lla(self, x, y, z):
>         """Convert topocentric x, y, z to lat, lon, alt."""
>         return lla_from_topocentric(x, y, z, self.lat, self.lon, self.alt) reconstruction.reference
> ```

Hi @fabianschenk,
Thanks for the clarification. There are two more questions:
1) Does the camera rotation/orientation provided by OpenSFM also w.r.t. the coordinate system at the center of the shots? And what would the x,y,z axis point towards, given that the origin is at the center of the shots?
2) From Mapillary API, we can also get the computed camera location and rotation for each image, but the reference for those images are not specified, and I think there should not be a uniform coordinate system for all images around the world right? So how should we interpolate the camera rotation for each image from Mapillary API? I think they are computed using OpenSFM. I do understand that the camera location can be translated to topocentric locations, but the rotation cannot without a reference coordinate system. So how can we translate those computed rotations to the same topocentric coordinate system?

**Comment by fabianschenk** [comment]
Hi @ZhipengCai,

1) The camera translation/rotation is typically given with respect to the first frame in the reconstruction
2) This will probably do what you want:
https://github.com/mapillary/OpenSfM/blob/1fcce830411583dc30f71667c78289693cab4661/opensfm/reconstruction.py#L1204-L1214
Also this little script might help: https://github.com/mapillary/OpenSfM/blob/1fcce830411583dc30f71667c78289693cab4661/bin/export_gps

Just study the code a bit more to figure out the details. If you feel that something's missing in the documentation, feel free to create a PR.

Best,
Fabian
