### ISSUE TITLE
3D point with improper GPS coordinate

### ISSUE THREAD

**Issue by zxdragon21** [mapillary/OpenSfM#901]
Dear Sir or Madam,
  I successfully reconstructed with openSFM, however the output GPS coordinate differs with the imput exif data(the pic above is the oringal one).
  Is there any method to aglin point clound xyz  to the origin GPS coordinate in reconstruction process?

![image](https://user-images.githubusercontent.com/68527116/169198853-181d9842-2696-4ade-a054-3c934e2304a3.png)
![image](https://user-images.githubusercontent.com/68527116/169198966-0b2322e2-766d-4745-8f9f-8f46bdb0f70d.png)

**Comment by fabianschenk** [comment]
Hi @zxdragon21 ,

The gps position is reported relative to the reference (the values are in the same json).
Just take a look at `TopocentricConverter` in `geo.py`.

**Comment by zxdragon21** [comment]
Dear Fabianschenk,
  I used geo.py to generate the file _reconstruction.geojson_, and I found the result coordinate is the one I want. However, the counterpart in _reconstruction.geojson_ is not. Therefore, is there any method to add GPS constraint of the coordinates in triangulation or global bundle adjustment? So that no need to transfrom the 3D points coordinates in an additional process.
  Thank you!

**Comment by fabianschenk** [comment]
Hi @zxdragon21 ,
The GPS coordinates are added to triangulation and BA but in a **local** reference frame with **local coordinates**. That's also the reason why this conversion from local to global coordinates is required for the export.
Maybe setting the reference to [0,0,0] directly in the code or maybe in the initial `.json` could achieve what you want.

Best,
Fabian

**Comment by YanNoun** [comment]
Hi,

If you want lat/lon coordinates, you can use the `export_gps` or `export_geojson` binaries : https://github.com/mapillary/OpenSfM/blob/main/bin/export_geojson and https://github.com/mapillary/OpenSfM/blob/main/bin/export_gps

Yann

**Comment by zxdragon21** [comment]
That sounds good! 
Thank you
----- 原始邮件 -----
发件人："Yann N." ***@***.***>
收件人：mapillary/OpenSfM ***@***.***>
抄送人：zxdragon21 ***@***.***>,  Mention ***@***.***>
主题：Re: [mapillary/OpenSfM] 3D point with improper GPS coordinate (Issue #901)
日期：2022年06月21日 17点15分


Hi,
If you want lat/lon coordinates, you can use the export_gps or export_geojson binaries : https://github.com/mapillary/OpenSfM/blob/main/bin/export_geojson and https://github.com/mapillary/OpenSfM/blob/main/bin/export_gps
Yann

&mdash;
