### ISSUE TITLE
Problems building for Ubuntu:Command '['make', '-j8']' returned non-zero exit status 2

### ISSUE THREAD

**Issue by AndresPrada** [mapillary/OpenSfM#903]
Hi,

I have followed the instructions to install OpenSfM on my local machine (Ubuntu 21.10) but, after installing: OpenCV, Ceres, and the consequent commands in the [Dockerfile](https://github.com/mapillary/OpenSfM/blob/main/Dockerfile), I get the following error when running `python3 setup.py build`:
```bash
[ 85%] Linking CXX static library libmap.a
[ 85%] Built target map
[ 86%] Linking CXX static library librobust.a
[ 86%] Built target robust
make: *** [Makefile:101: all] Error 2
Traceback (most recent call last):
  File "/home/andres/Documents/other_repos/OpenSfM/setup.py", line 60, in <module>
    build_c_extension()
  File "/home/andres/Documents/other_repos/OpenSfM/setup.py", line 54, in build_c_extension
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j8']' returned non-zero exit status 2.
```

Also, I had to upgrade sphinx from `4.1.2` to `4.2.0` to make it work.

Any ideas on this?

Thank you in advance!

**Comment by YanNoun** [comment]
Hi,

`sphinx` has been upgraded to `4.2.0` : https://github.com/mapillary/OpenSfM/commit/e2f3665b127a4f73979991a1463db9997176510f

Let me know if that helps,

Yann
