### ISSUE TITLE
Blank localhost:8080 page

### ISSUE THREAD

**Issue by shaharyuval** [mapillary/OpenSfM#907]
I followed the directions on downloading, compiling and installing the opensfm requirements.
I was able to preprocess the Berlin dataset successfully and create the reconstruction.meshed.json file.

But the web page comes up blank (black) when I run python viewer/server.py -d data/berlin

Am I missing something or could there be a package mismatch?  I had to fiddle with Flask to get rid of the jinja2/escape error.  Ended up upgrade to flask v2.1, then downgrading back to 1.1.2 (plus downgrading werkzeug, itsdangerous, jinja2 to < 2).  Either version produces the same blank screen.

I'm running on Windows 10, with an Anaconda virtual environment with Python 3.7.
Here's the package list:

Package                       Version
----------------------------- -----------
alabaster                     0.7.12
Babel                         2.10.1
certifi                       2022.5.18.1
charset-normalizer            2.0.12
click                         8.1.3
cloudpickle                   0.4.0
colorama                      0.4.4
cycler                        0.11.0
decorator                     5.1.1
docutils                      0.17.1
ExifRead                      2.1.2
Flask                         1.1.2
fonttools                     4.33.3
fpdf2                         2.4.6
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.4
itsdangerous                  1.1.0
Jinja2                        2.11.3
joblib                        0.14.1
kiwisolver                    1.4.2
MarkupSafe                    1.1.1
matplotlib                    3.5.2
networkx                      2.5
numpy                         1.21.6
opencv-python                 4.5.1.48
packaging                     21.3
Pillow                        9.1.1
pip                           22.1.2
py                            1.11.0
Pygments                      2.12.0
pyparsing                     3.0.9
pyproj                        3.2.1
pytest                        3.0.7
python-dateutil               2.8.2
pytz                          2022.1
PyYAML                        5.4
requests                      2.27.1
scipy                         1.7.3
setuptools                    62.3.2
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        4.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
typing_extensions             4.2.0
urllib3                       1.26.9
Werkzeug                      1.0.1
wheel                         0.37.1
xmltodict                     0.10.2
zipp                          3.8.0

**Comment by fabianschenk** [comment]
Hi @shaharyuval ,
From the top of my head, the main problem I can think of is that you're pointing to the wrong directory.
- Could try an absolute path like: `C:/.....`?
- Does the folder contain also a `reconstruction.json`?
- You can also look at the logs in your browser (I think F12 in Chrome)

Good luck,
Fabian

**Comment by shaharyuval** [comment]
Thanks @fabianschenk,
I confirmed the existence of ```reconstruction.json``` and I tried setting an absolute path, but am still getting a blank page.  

The Chrome logs reveal the following error:

```
opensfm.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

Looking inside opensfm.js, I see the following:

```
/**
 * @format
 */

export {CommandExplainerControl} from './control/CommandExplainerControl.js';
export {Copier} from './control/Copier.js';
export {InfoControl} from './control/InfoControl.js';
export {Popup} from './control/Popup.js';
export {ThumbnailControl} from './control/ThumbnailControl.js';

export {DatController, FolderName} from './controller/DatController.js';
export {FileController} from './controller/FileController.js';
export {KeyController} from './controller/KeyController.js';
export {ListController} from './controller/ListController.js';
export {OptionController} from './controller/OptionController.js';

export * as ProviderMath from './provider/math.js';
export {DataConverter} from './provider/DataConverter.js';
export {OpensfmDataProvider} from './provider/OpensfmDataProvider.js';

export {AxesRenderer} from './renderer/AxesRenderer.js';
export {CustomRenderer} from './renderer/CustomRenderer.js';
export {EarthRenderer} from './renderer/EarthRenderer.js';

export {FileLoader} from './ui/FileLoader.js';
export {FileSelecter} from './ui/FileSelecter.js';
export {OpensfmViewer} from './ui/OpensfmViewer.js';
export {OrbitCameraControls} from './ui/OrbitCameraControls.js';

export {CancelledError} from './util/Error.js';
export {EventEmitter} from './util/EventEmitter.js';
export * from './util/coords.js';
export * from './util/ids.js';
export * from './util/params.js';
export * from './util/types.js';
```

I'm pretty clueless about JavaScript, but the error above suggests this has to do with the headers rather than the content, no?

**Comment by shaharyuval** [comment]
Is there a particular version of Python that's been verified with this environment?

**Comment by fabianschenk** [comment]
Hi @shaharyuval ,

According to Google, the error you get is because your server doesn't tell the browser that it's a JS website, so it's neither a Python nor JavaScript problem. You can also try running a different browser.
You can also try to start the server with a different python version, e.g. `python3` instead of just `python`.

**Comment by shaharyuval** [comment]
Thanks @fabianschenk,
I followed your lead and did some more googling along these lines.  I found this Stackoverflow: https://stackoverflow.com/questions/68584547/flask-server-not-sending-js-module-script

And renamed viewer/src/opensfm.js -> opensfm.mjs (and adjusted the reference to the module in viewer/index.html according).  And... voila! Works like a charm on Windows.

**Comment by micat001** [comment]
All - I had a similar problem with a blank page and my root cause was directory permissions on the node_module folder. If you're running Linux, make sure your user has read/write permissions to that folder after running ./node_modules.sh. 

Looking at the log output of F12/inspection in the browser was the perfect troubleshooting step though! Those logs led me right to the issue.
