### ISSUE TITLE
Is it OK to use ceres-solver compiled without the -fPIC flag?

### ISSUE THREAD

**Issue by hilman-dayo** [mapillary/OpenSfM#91]
The ceres-solver is already installed in my system because I was building my OpenCV with its SfM module. At that time, I didn't use the `-fPIC` compilation flag. So, must I build a new ceres-solver (with the `-fPIC` flag? If that is the case, how can I install two same library at the same time? If I uninstall the old one, would it affect my built with SfM module OpenCV?

**Comment by paulinus** [comment]
Python needs to load modules using Position Independend Code (PIC). So you need to compile Ceres with the `-fPIC` option.
If you use Ceres for other libraries like OpenCV, you can recompile them, but it should not be needed. Specially if you used Ceres as a static library.
