### ISSUE TITLE
project ground control point to image

### ISSUE THREAD

**Issue by cbtogu** [mapillary/OpenSfM#918]
Sorry for closing the last issue [#915](https://github.com/mapillary/OpenSfM/issues/915) for mistake. Reopen it because my problem is not solved. The following is my last post. Hope somebody can help me. @YanNoun @fabianschenk . Thank you.

Hi folks, I have some progress here, First, we need to transform the gcp coordinates to WGS84, we get lat, lon, alt. Then use the following code to project the ground control point to image.
```
pt3D= reference.to_topocentric(lat, lon, alt)
pt2D= shot.project(pt3D)
pt2D_px = cam.normalized_to_pixel_coordinates(pt2D)
```
then check if the pt2D_px is inside the camera frustum.
I only have one problem here is that the altitude of pt3D is NOT right, resulting in the wrong pt2D_px . But I don't know how to get the right altitude since the reference altitude is set to 0 in function invent_reference_from_gps_and_gcp of dataset.py, and the height of ground control point ususally near 0, so we always get ~0 altitude of pt3D.
I checked the point altitude of reconstruted point cloud using Meshlab. The point altitude has a value of -90 ~ -70 m。If we use this altitude to project gcp to image, we can get the right coordinates.
So how can I get the right altitude when transform the gcp to topocentric?

**Comment by fabianschenk** [comment]
Hi @cbtogu ,
One thing to keep in mind is that the reference at altitude 0 assumes that the images are taken more or less on street-level. So if you have aerial images, they are at altitude ~0 and then the reconstructed points are at e.g. -70 to -90 m. Could you try to rerun with the `use_altitude_tag = True` option:
https://github.com/mapillary/OpenSfM/blob/8e7b11c19b76ce39ee7598109087ddffc4502171/opensfm/config.py#L284

You should be able to just create a `config.yaml` file in your images folder with `use_altitude_tag: 1`.

Best,
Fabian

**Comment by YanNoun** [comment]
Hi @cbtogu,

@fabianschenk is right, you should set `use_altitude_tag = True`, then the camera should be at the right place. The fact that the topoframe has zero altitude is purely arbitrary, but shouldn't impact any computation.

Yann

**Comment by cbtogu** [comment]
Thanks Fabian and Yan, Sorry for my late reply. I've already set `use_altitude_tag = True` in my test. But after discussing with the folks from ODM community, maybe the problem coms from that the altitude of the ground control point is inconsistent  with the camera gps. I'll continue dig into it. Hope I'll get some findings and get back to you. 
Thanks for your help.

**Comment by cbtogu** [comment]
Thanks Fabian and Yan, Sorry for my late reply. I've already set `use_altitude_tag = True` in my test. But after discussing with the folks from ODM community, maybe the problem coms from that the altitude of the ground control point is inconsistent  with the camera gps. I'll continue dig into it. Hope I'll get some findings and get back to you. 
Thanks for your help.

**Comment by teiminryu** [comment]
Is there any solution for this issue? I am also trying to project ground control points back to images, but the altitude is affecting the projected 2D coordinates. By the way, setting "use_altitude_tag = True" does not solve the problem. 

My current way is to adjust the altitude manually and see the projected 2D points. However, this is not clever at all. It has better to know the defined datum and convert the altitude at once.
