### ISSUE TITLE
Install opencv-python on all systems

### ISSUE THREAD

**Issue by darrenwiens** [mapillary/OpenSfM#919]
Following documentation [here](https://opensfm.org/docs/building.html#installing-dependencies-on-macosx), `opencv-python` appears to only install, via `requirements.txt`, on win32: https://github.com/mapillary/OpenSfM/blob/main/requirements.txt#L19

Result running `bin/opensfm_run_all data/berlin` (from Quickstart) is: `No module named 'cv2'`

Is the assumption that `opencv-python` should be installed some other way on other systems? Problem solved by `pip install opencv-python`, but seems like it may as well install through `requirements.txt`.

**Comment by fabianschenk** [comment]
Hi @darrenwiens ,
Does removing the win32 part at this line solve your issue?
https://github.com/mapillary/OpenSfM/blob/c91ed5547075a06c6da721d1dbdbb875d5ee2c23/requirements.txt#L19 
If yes, then you can just create a PR.

Best, 
Fabian

**Comment by fabianschenk** [comment]
Hi @darrenwiens,
this should be fixed by:
https://github.com/mapillary/OpenSfM/pull/910
