### ISSUE TITLE
changes in requirements.txt including not existing flask version

### ISSUE THREAD

**Issue by matanPercepto** [mapillary/OpenSfM#928]
in the last commit to requirements.txt (commit hash 3b3e236), one of the changes inserted was changes of flask version from 1.1.2 to 2.1.2, but this version does not exist, or isn't supported. when trying to install the requirements file, I recieved the following error:
ERROR: Could not find a version that satisfies the requirement flask==2.1.2 (from versions: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.5, 0.5.1, 0.5.2, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.9, 0.10, 0.10.1, 0.11, 0.11.1, 0.12, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.0.3)
ERROR: No matching distribution found for flask==2.1.2

**Comment by fabianschenk** [comment]
Hi @matanPercepto,

It does indeed exist https://pypi.org/project/Flask/
![image](https://user-images.githubusercontent.com/13796836/177722033-d6348823-7ba7-4fa7-8203-511a7c49d583.png)

Maybe you have to update pip or your package list? I'm not really familiar with pip but maybe try a Google seach.

Best,
Fabian

**Comment by mauri101-Ar** [comment]
The same thing happened to me with Python 3.6 and Flask 2.1.0. 
I fixed it by upgrading python to 3.8.
