### ISSUE TITLE
OpenCV Fisheye documentation incorrect

### ISSUE THREAD

**Issue by thaytan** [mapillary/OpenSfM#929]
In the same vein as https://github.com/mapillary/OpenSfM/issues/846, the documentation for the OpenCV Fisheye camera is incorrect.

The OpenSFM documentation formulae contain tangential distortion correction, but the OpenCV fisheye model only has 4 radial distortion parameters (which is what the OpenSFM code implements)

Incorrect OpenSFM documentation:
![image](https://user-images.githubusercontent.com/74973/178103526-7dc7b053-a3ce-4217-9c9d-20b5147a2243.png)

OpenCV documentation: https://docs.opencv.org/4.6.0/db/d58/group__calib3d__fisheye.html

**Comment by fabianschenk** [comment]
Hi @thaytan ,

Thanks, I'll update the documentation.
