### ISSUE TITLE
New sensor for database

### ISSUE THREAD

**Issue by pulquero** [mapillary/OpenSfM#93]
Please could you add the following sensor/camera to your database:

**Sony Exmor R IMX206** (used in Gitup Git2 action camera amongst others)
Spec: http://www.sony.net/Products/SC-HP/new_pro/december_2013/imx206_e.html
diagonal 7.77mm (from spec)
width 6.216 mm (calculated)
height 4.662 mm (calculated)
res width 4608 (from spec/actual photo)
res height 3456 (from spec/actual photo)
type 1/2.3 (from spec)

Not sure what resolution "sensor res" refers to, so in case I picked the wrong one here is the full list: Total number of pixels 	4768 (H) × 3516 (V), Approx. 16.76M
Number of effective pixels 	4672 (H) × 3500 (V), Approx. 16.35M
Number of active pixels 	4632 (H) × 3492 (V), Approx. 16.17M
Actual photo 4608 (H) x 3456 (V), Approx 15.92M

**Comment by pulquero** [comment]
Forgot the values of the make/model EXIF headers:
GITUP
GIT2

Based on the ratio of actual photo pixels to total pixels here is what is usable, if these are more relevant numbers to use:
usable width 6.007
usable height 4.582
usable diagonal 7.556

**Comment by paulinus** [comment]
Added to the database. Thanks!
The sizes you picked look fine. Also, note that the only number that is actually used for SfM is the sensor width in mm, which we store in the `sensor_data.json` file.
