### ISSUE TITLE
Stereographic Image Problem

### ISSUE THREAD

**Issue by edent** [mapillary/OpenSfM#94]
([Jan asked me to post this here](https://twitter.com/jesolem/status/769543101841084416).)

I have a set of stereo images which I'm trying to convert into 3D models.

Here's a sample image
![women-eating-1](https://cloud.githubusercontent.com/assets/837136/18032295/0d808936-6cf9-11e6-9c23-c4d02dec01dd.gif)

I've split this into two separate images and placed them in `data/japan/images`:
![01](https://cloud.githubusercontent.com/assets/837136/18032306/2b481f6a-6cf9-11e6-88b9-3b9deb6d6948.jpg)
![02](https://cloud.githubusercontent.com/assets/837136/18032305/2b46af4a-6cf9-11e6-8544-004fb4756973.jpg)

I've added the `config.yaml` file and run `./bin/run_all data/japan/`.

When I go to view the result in the browser, I get this:
![japan0](https://cloud.githubusercontent.com/assets/837136/18032427/535cf892-6cfc-11e6-871b-88cb95ed3f45.png)

![screenshot from 2016-08-27 15 13 58](https://cloud.githubusercontent.com/assets/837136/18032319/742b1228-6cf9-11e6-8ed9-af1a0c9fc05d.png)
![screenshot from 2016-08-27 15 13 22](https://cloud.githubusercontent.com/assets/837136/18032318/7427ef1c-6cf9-11e6-9b35-32b7d11e0c27.png)

If I use exactly the same images in [AgiSoft's PhotoScan](http://www.agisoft.com), I'm able to get depth information.
![illegalpowerfulbelugawhale-size_restricted](https://cloud.githubusercontent.com/assets/837136/18032377/beb0857a-6cfa-11e6-9a95-1b8a60dab5ac.gif)

Using the demo set "lund" seem to work - so I think I've installed everything correctly.
![lund3](https://cloud.githubusercontent.com/assets/837136/18032430/7979d518-6cfc-11e6-99fc-df548022b53d.png)
![lund2](https://cloud.githubusercontent.com/assets/837136/18032431/797b9768-6cfc-11e6-86d6-cafc6c3c54ec.png)

Can anyone tell me what I might be doing wrong here? I appreciate that I am using "difficult" images with no GPS or EXIF data.

Ubuntu 14.04, same issue in Chrome and Firefox.

**Comment by YanNoun** [comment]
This is caused by very distants points, due to the small baseline of your images.
