### ISSUE TITLE
Is it possible to maually input intrinsic parameters?

### ISSUE THREAD

**Issue by pengsongyou** [mapillary/OpenSfM#95]
Hello! I am doing a project about camera calibration and now want to use OpenSfM to evaluate the calibration results. I have successfully make OpenSfM run and the reconstruction is awesome but it seems we cannot specify the intrinsic and distortion parameters as the input. Just add this issue to make sure if it is possible to input our known intrinsic and distortion parameters in OpenSfM? 

Thank you very much!

**Comment by edgarriba** [comment]
not sure if there's any interface to do so, but you could hack the algorithm and feed the camera object with your intrinsics
https://github.com/mapillary/OpenSfM/blob/master/opensfm/types.py#L153-L178

**Comment by pengsongyou** [comment]
@edgarriba Thanks for replying! I tested what you mentioned and it turned out not working still. I changed the initial intrinsics parameters, which affects nothing to neither camera_models.json (initial values of the intrinsic camera parameters) nor reconstruction.json (final values).

**Comment by edgarriba** [comment]
mmm, maybe @paulinus can give you a better solution.

**Comment by paulinus** [comment]
You can set the camera parameters (focal, k1 and k2) manually by creating a `camera_models_overrides.json` file on the dataset folder.  The simples way is to rename the automatically generated `camera_models.json` and edit the values.

You can then run `bin/clean path_to_dataset` to remove the previous results and then `bin/run_all path_to_dataset`.  This time, any cameras defined in `camera_models_overrides.json` will use the parameters defined on that file as a prior.

**Comment by pengsongyou** [comment]
Hi @paulinus , sorry for my late reply... I have tried what you said and it is not working very well, because my estimation of k1 and k2 is not quite accurate . I still have another two small questions.

1. Just to make sure, is the `focal` or `focal_prior` in centimeter? 
2. Is your system possible to deal with fisheye camera model? 

Thanks in advance!

**Comment by BrookRoberts** [comment]
If you set focal parameters, whether in config.yaml or camera_models_overrides.json, will opensfm always improve the estimates?  I'm seeing quite a few situations where I believe I know the focal for the camera, pass it to opensfm, and then I see in the final reconstruction opensfm has substantially changed it (e.g. changing a prior of 0.4 to 0.8!).  I'm also seeing some camera poses where the path of the camera (for reconstructing a video) is depicted in a much tighter curve than it should be, and suspect this may be related.

**Comment by YanNoun** [comment]
@BrookRoberts you can constraint the focal length more tightly by increasing the value of `exif_focal_sd` : it is `0.01` by default, try setting it to `0.001`.
