### ISSUE TITLE
Viewer doesn't load in browser

### ISSUE THREAD

**Issue by nwcimaszewski** [mapillary/OpenSfM#96]
I'll enter the correct URL while I'm serving from the right directory, but it just doesn't load.  I've been waiting for a while.  I've been using this pipeline for more than two months now and I did the same I've always done.  I changed part of the code in reconstruction.py, but it all executes without error.  It creates the reconstruction without a problem, it's just viewing it that's the issue.

Any tips?

**Comment by ableade** [comment]
did you solve this problem?

**Comment by nwcimaszewski** [comment]
Don't quite remember, but I think it was just a mistake of my own.  I was able to get the results I wanted in the end.
