### ISSUE TITLE
Error with setup.py on Windows

### ISSUE THREAD

**Issue by Fsamhouri** [mapillary/OpenSfM#967]
I run into this error when calling setup.py:

![image](https://user-images.githubusercontent.com/60676580/204957165-22e05689-b75b-422c-8fdb-44872d3de9ea.png)

I managed to install all dependencies as shown below:

![image](https://user-images.githubusercontent.com/60676580/204957292-7eaffc05-b869-47d2-80ea-2da3c275ca24.png)

So I'm not sure any dependency is missing. Any other reason this issue arises?

**Comment by hirleman** [comment]
I have the same error in line 1420 on this final build step.  And everything else seemed correct.  

Did you solve this?

**Comment by zhuangqirong** [comment]
> I have the same error in line 1420 on this final build step. And everything else seemed correct.
> 
> Did you solve this?

Did you solve this?I have the same error

**Comment by fabianschenk** [comment]
Hi @zhuangqirong , @hirleman , @zhuangqirong ,

Did anyone ever do a simple google search for this? What have you tried to resolve it?

Here are some suggestions that might do the trick:
- [Suggestion #1](https://stackoverflow.com/questions/55153818/the-system-cannot-find-the-file-specified-when-trying-to-build-python-c-extens) -> Make sure that the python version and the compiler have compatible versions
- [Suggestion #2](https://stackoverflow.com/questions/36048769/error-the-system-cannot-find-the-file-specified-when-running-python-with-subli) -> Make sure to set the PATH variable correctly
