### ISSUE TITLE
Adjusting "confidence" of reconstruction

### ISSUE THREAD

**Issue by nwcimaszewski** [mapillary/OpenSfM#97]
Is there a way to adjust how "confident" the pipeline must be to spawn a given point?  My problem is that I have too many outliers and I'd be willing to trade fewer points for fewer outliers.  Is there something in the code or configurations I could change to do this?

**Comment by paulinus** [comment]
There are a number of thresholds that can be set in a `config.yaml` file. The complete list is in [`config.py`](https://github.com/mapillary/OpenSfM/blob/master/opensfm/config.py)

If you want to get fewer outliers you can reduce the threshoulds on the [geometric estimation section](https://github.com/mapillary/OpenSfM/blob/master/opensfm/config.py#L58-L65) from 0.004 to 0.002 for example.
