### ISSUE TITLE
Point Cloud Segmentation from Masks

### ISSUE THREAD

**Issue by PPrange** [mapillary/OpenSfM#977]
Hello 
I would like to assign classes/labels to the points in the PointCloud. 
I read this [post](https://blog.mapillary.com/update/2016/10/31/denser-3d-point-clouds-in-opensfm.html) and know #506.
I still don't understand how to do the segmentation. 

I have:
- RGB images from which point clouds can be created
- masks for the pictures that only contain the values of the classes

As far as I understand, there is a mask folder in the Berlin example. However, this serves much more to avoid reconstructing certain objects.

So my question is what do I have to do to have the classes in the merged.ply file?

**Comment by PPrange** [comment]
Ok I figured it out myself.

You have to create a "segmentations" folder next to the images folder. The class masks must be in there. Strangely they must be called "filename.png.png".  I think it would work with "filename.jpg.png" too. 
Whatever the reason?

**Comment by CassielMapersive** [comment]
@PaulSchuler could you give examples of your segmentations folder? Once I run the merged.ply file I do not get a point cloud segmentation as I had hoped.

**Comment by PaulSchuler** [comment]
The segmentation folder contains one mask file (filename.png.png) for each image (filename.png) in the images folder. This mask contains the class values for each pixel. For example, if the image file has the shape [256,256,3] [x,y,{rgb}], the mask has the shape [256,256,1] [x,y{class}].

I hope that helps.

**Comment by CassielMapersive** [comment]
> The segmentation folder contains one mask file (filename.png.png) for each image (filename.png) in the images folder. This mask contains the class values for each pixel. For example, if the image file has the shape [256,256,3] [x,y,{rgb}], the mask has the shape [256,256,1] [x,y{class}].
> 
> I hope that helps.

@PaulSchuler Thank you for answering so quickly, although I am still slightly confused. I thought the masks needed to be greyscaled, and if they do how can we visualize the dense or sparse point clouds with their segmentation labels. I looked through meshlab with no luck. Are there any resources that can point me to point cloud segmentation using the dense point clouds reconstructed by OpenSfM?
