### ISSUE TITLE
How can I use rig camera reconstruction correctly?

### ISSUE THREAD

**Issue by zxiaomzxm** [mapillary/OpenSfM#985]
Hi, I have found the rig class in this lib, but I don't understand how to use rig camera reconstruction correctly. Especially the reconstuction pipeline with rig cameras. Is there any examples available? Thanks.

**Comment by fabianschenk** [comment]
Hi @zxiaomzxm ,

What have you tried so far to understand this? I'd suggest a simple search for `rig` in the repo. Then you'll find [documentation](https://github.com/mapillary/OpenSfM/blob/379962a4e048438a898c985a136e7ffe6e3891c8/doc/source/rig.rst) and see how it is used in the code.

**Comment by zhangsongdmk** [comment]
> 

Hi, can you give a real example or project file on the rig camera? the documantation is too simple.
