### ISSUE TITLE
Missing observations for inital shots (bootstrap_reconstruction)

### ISSUE THREAD

**Issue by kielnino** [mapillary/OpenSfM#986]
When using the **incremental reconstruction** the reconstruction is seeded with a first inital camera-pair ([bootstrap_reconstruction](https://github.com/mapillary/OpenSfM/blob/main/opensfm/reconstruction.py#L608)) and afterwards grown by adding single images ([grow_reconstruction](https://github.com/mapillary/OpenSfM/blob/main/opensfm/reconstruction.py#L1385)). I noticed that in the grow-phase the images are resected and on success the shots are [added](https://github.com/mapillary/OpenSfM/blob/main/opensfm/reconstruction.py#L720), [triangulated](https://github.com/mapillary/OpenSfM/blob/main/opensfm/reconstruction.py#L725) and the [observations added](https://github.com/mapillary/OpenSfM/blob/main/opensfm/reconstruction.py#L730) to the tracks_manager.

This last step (`add_observation_to_reconstruction`) however is never called on the first two shots which are used to initialize the reconstruction. Now I'm wondering if this is intended?

If this is a mistake, I'm happy to submit a PR.

**Comment by kielnino** [comment]
@fabianschenk Hej Fabian, any idea, who can answer my question resp. decide if a PR is desired?

**Comment by fabianschenk** [comment]
Hi @kielnino ,

I don't know if this is a bug or intended. Have you tried adding the observations and did you see any difference in quality? 
Shouldn't this just be a 2-3 line PR, so quite easy to test?

Just to mention it again: Our priorities have changed and we're not actively developing OpenSfM anymore, so you'll likely not get much feedback from anybody else. If you set up a PR, I can add it but that's about it.

Best Fabian

**Comment by kielnino** [comment]
I've tested the supposed change and didn't noticed any differences. So I'm closing the issue.
